- .eslintignore
- packages/map/src/index.tsx
- packages/map/src/marker/index.ts
- packages/map/src/marker/with-type-circle-marker.tsx
- packages/map/src/utilities.ts
> map 디렉토리의 ESLint 검사를 활성화하고 오류를 수정합니다.

- packages/ad-banners/src/list-top-banners.tsx
- packages/ad-banners/src/typing.ts
Breaking Change를 일으키기 때문에 #1786 에서 수정하지 못한 린트 오류를 수정합니다.
- `ListDirection.VERTICAL` => `ListDirection.Vertical`
- `ListDirection.HORIZONTAL` => `ListDirection.Horizontal`
> 💥 ad-banners의 ListDirection enum의 멤버 네이밍 변경

- docs/stories/triple-document/triple-document.stories.tsx
- packages/triple-document/src/elements/external-video.tsx
- packages/triple-document/src/elements/itinerary/itinerary-map.tsx
> [triple-doucment] 불필요한 영역의`snapshot`을 ignore합니다.

- .eslintignore
- packages/ui-flow/src/auth-guard/index.test.ts
- packages/ui-flow/src/auth-guard/index.ts
- packages/ui-flow/src/guarded-scraps-provider.tsx
- packages/ui-flow/src/use-app-callback.ts
- packages/ui-flow/src/use-session-callback.test.tsx
- packages/ui-flow/src/use-session-callback.ts
> packages/ui-flow 디렉토리의 ESLint 검사를 활성화합니다.

- package-lock.json
- packages/fetcher/package.json
- packages/fetcher/src/response-handler.ts
- packages/triple-document/package.json
- packages/ui-flow/src/auth-guard/index.test.ts
triple-document 패키지에서 `@sentry/browser` 의존성을 제거합니다.
그리고 fetcher의 `@sentry/browser` 의존성을 `@sentry/nextjs`로 변경합니다.
> sentry 패키지 의존성을 정리합니다.

- package-lock.json
> 📦 update package-lock.json

- packages/replies/src/list/reply.tsx
- packages/replies/src/replies-api-clients.ts
- packages/replies/src/reply.test.tsx
작성된 댓글&답글에 유저가 공감할 수 있도록 반응(좋아요 / 좋아요 취소) 기능을 추가합니다.
- 반응 (좋아요 / 좋아요 취소) Services 로직을 추가합니다.
- 반응 (좋아요 / 좋아요 취소) onClick 로직을 추가합니다.
> [replies] 댓글&답글 좋아요 반응 기능을 추가합니다.

- package-lock.json
- packages/replies/package.json
- packages/replies/src/list/reply.tsx
- packages/replies/src/replies-api-clients.ts
- packages/replies/src/reply.test.tsx
- packages/replies/tsconfig.build.json
- packages/replies/tsconfig.json
작성된 댓글&답글이 부적절한 내용일 때, 신고할 수 있도록 기능을 추가합니다.
- 신고하기 Services 로직 추가
- 신고하기 onClick 로직 추가
> [replies] 댓글&답글에 신고하기 기능을 추가합니다.

- packages/poi-detail/src/image-carousel/carousel-section.tsx
- packages/poi-detail/src/image-carousel/note.tsx
- `image-carousel` 내부 컴포넌트인 `Note` 컴포넌트를 수정합니다. (폐업 여부, 혹은 영업시간을 노출하는 컴포넌트입니다.)
- 호텔 및 투어티켓 영역에서의 `image-carousel` 컴포넌트는 border-radius = 0 이기 때문에, 해당 컴포넌트를 수정하빈다.
- `Note` 컴포넌트 내부의 불필요한 컨테이너를 제거합니다. 
- 관련 피그마: https://www.figma.com/file/F1C8phEOjueBtlG53UghVp/20210520_v5.x.x_%EC%97%94%EB%93%9C%ED%8E%98%EC%9D%B4%EC%A7%80-%EA%B3%B5%ED%86%B5%EC%9A%94%EC%86%8C-%EC%9E%91%EC%97%85?node-id=1103%3A11878
> [poi-detail] `image-carousel` 내부의 노트 컴포넌트를 수정합니다

- .github/workflows/ci.yaml
CI 워크플로의 build 잡을 제거하고 lint 잡을 추가합니다.
의존성 변경을 감지하는 잡을 다듬습니다.
각 잡이 체크하는 내용이 실패했을 때 슬랙 알림을 보냅니다.
> CI 워크플로의 job을 정리합니다.

- .github/workflows/ci.yaml
실패 알림을 보내는 step이 실행되지 않는 문제를 수정합니다.
> 🐛 실패 알림을 보내는 step이 job이 실패했을 때 실행되도록 처리

- MIGRATION.md
v6 마이그레이션 가이드에서 언급하지 않는 Breaking Change가 있습니다. 이를 설명하는 내용을 추가합니다.
> v6 마이그레이션 가이드에 누락된 내용을 채웁니다.

- MIGRATION.md
- packages/map/src/overlay/markers/primary-marker/index.ts
- map 패키지 관련하여 v6 마이그레이션 가이드에서 누락된 Breaking Change를 추가 작성합니다.
> v6 마이그레이션 가이드에 누락된 map 패키지 내용을 작성합니다.

- docs/stories/replies/replies.stories.tsx
- packages/replies/src/guide-text.tsx
- packages/replies/src/list/index.tsx
- packages/replies/src/list/reply.tsx
- packages/replies/src/register.tsx
- packages/replies/src/replies-api-clients.ts
- packages/replies/src/replies.tsx
- packages/replies/src/reply-tree-manipulators.test.tsx
- packages/replies/src/reply-tree-manipulators.ts
- packages/replies/src/reply.test.tsx
- packages/replies/src/utils.ts
새로고침을 해야 작성/수정/삭제된 댓글이 보이는 오류를 수정 
- 원인: 상태를 업데이트하는 로직의 부재
> [replies] 새로고침 이슈를 해결합니다.

- MIGRATION.md
- packages/map/README.md
마커에 대한 설명이 빠져있어 리드미 및 마이그레이션 가이드를 수정합니다.
> 맵 패키지의 리드미 및 마이그레이션 가이드를 수정합니다.

- packages/poi-detail/src/image-carousel/carousel-section.tsx
- packages/poi-detail/src/image-carousel/note.tsx
- [poi-detail] PoiDetail 의 NoteContainer 수정으로 인해 생겼던 버그를 수정합니다.
- #1874  해당 PR 에서 제거 되었던 `Container` 컴포넌트를 복구합니다. => 해당 컴포넌트가 존재 하지 않을 때 부모 컨테이너의 섹션을 넘어 서는것을 수정합니다. 
- `borderRaiuds = 0` 값일 때 `&&` 연산으로 인해 css 안에 0 값이 들어가게 되어 z-index 가 제대로 작동하지 않는 문제르 수정합니다.
> [poi-detail] PoiDetail 의 NoteContainer 수정으로 인해 생겼던 버그를 수정합니다.

- packages/map/src/overlay/markers/flexible-marker.tsx
-`flexibleMarker`에 누락된 CircleMarekrProps을 추가합니다.
> [map] `flexibleMarker`에 누락된 props을 추가합니다

- MIGRATION.md
https://titicaca.slack.com/archives/CEEPB4TDY/p1644310495041719
> 📝 `LocalLink`, `ExternalLink` 내용 보충

- docs/stories/core-elements/flex-box.stories.tsx
- packages/core-elements/src/elements/flex-box.test.tsx
- packages/core-elements/src/elements/flex-box.tsx
> [core-elements] gap props추가

- docs/package.json
- docs/stories/triple-email-document/heading.stories.tsx
- docs/stories/triple-email-document/hr.stories.tsx
- docs/stories/triple-email-document/images.stories.tsx
- docs/stories/triple-email-document/link.stories.tsx
- docs/stories/triple-email-document/note.stories.tsx
- docs/stories/triple-email-document/text.stories.tsx
- docs/tsconfig.json
- package-lock.json
- packages/triple-email-document/src/elements/images.tsx
triple-email-document storybook 코드를 추가합니다.
#1895 작업 완료 후에 이어서 진행합니다.
storybook 추가목록
1. heading
2. hr
3. 이미지
4. 링크
5. 노트
6. 텍스트
> [storybook] triple-email-document 관련 storybook 코드를 추가합니다.

- docs/stories/triple-email-document/footer.stories.tsx
- docs/stories/triple-email-document/heading.stories.tsx
- docs/stories/triple-email-document/hr.stories.tsx
- docs/stories/triple-email-document/images.stories.tsx
- docs/stories/triple-email-document/link.stories.tsx
- docs/stories/triple-email-document/note.stories.tsx
- docs/stories/triple-email-document/preview.stories.tsx
- docs/stories/triple-email-document/text.stories.tsx
- packages/triple-email-document/src/common/handlebars-anchor.tsx
- packages/triple-email-document/src/common/index.ts
- packages/triple-email-document/src/components/footer.test.tsx
- packages/triple-email-document/src/components/footer.tsx
- packages/triple-email-document/src/components/index.ts
- packages/triple-email-document/src/components/preview.test.tsx
- packages/triple-email-document/src/components/preview.tsx
- packages/triple-email-document/src/index.ts
Footer와 Preview를 추가합니다. 
- 데이터 구조 타입이 아님으로 별도 components directory 생성
- Add EmailFooter Component & Test code
- Add EmailPreview Component & Test code
> [triple-email-document] Footer, Preview를 추가합니다.

- packages/triple-email-document/src/elements/text.test.tsx
- packages/triple-email-document/src/elements/text.tsx
Text Element를 최신화합니다.
- rawHTML, text를 value로 받도록 합니다.
> [triple email document] Text Element를 최신화합니다.

- packages/standard-action-handler/README.md
Standard Action Handler의 README를 작성합니다.
> Standard Action Handler ReadMe 작성

- packages/modals/README.md
업데이트된 `session-context`에서는 더 이상 `useSessionContext`를 지원하지 않기에 혼동이 있을 수 있으므로 수정합니다.
- `useSesstionContext`를 `useSessionAvailability`로 수정합니다.
> [modal] 업데이트된 session-context를 반영하여 README를 수정합니다.

- packages/triple-email-document/src/common/index.ts
- packages/triple-email-document/src/common/reset.ts
- packages/triple-email-document/src/full-email-template.tsx
- packages/triple-email-document/src/index.ts
`triple-email-template-admin`, `triple-email-api` 프로젝트에서 공용으로 사용되고 있는 `FullEmailTemplate` 레이아웃을 추가합니다.
- Reset Style을 추가합니다.
- FullEmailTemplate을 추가합니다.
> [triple-email-template] FullEmailTemplate를 추가합니다.

- packages/triple-email-document/src/full-email-template.tsx
위의 오류를 해결하기 위해 triple-email-document 패키지 안에 있는 React 참조 코드를 제거합니다.
> [triple-email-document] React 참조 코드를 제거합니다.

- packages/replies/src/list/reply.tsx
닉네임이 9자 이상일 때, 말줄임표로 표기합니다.
as-is : 닉네임 전체 표기
to-be : 닉네임이 9자 이상일 때, 말줄임표로 표기
[매거진에 댓글달기 테스트 시트 8번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- Nickname style max-width. : 135px 추가
> [replies] 닉네임이 9자 이상일 때, 말줄임표로 표기합니다.

- docs/stories/router/styled-local-link.stories.tsx
- packages/core-elements/src/elements/select.tsx
- packages/core-elements/src/elements/tooltip.tsx
- packages/core-elements/src/global-style.ts
- packages/footer/src/default-footer.tsx
- packages/recommended-contents/src/index.tsx
- packages/router/src/common/router-guarded-link.tsx
- packages/triple-document/src/elements/itinerary/badge.ts
global-style 개선
https://github.com/titicacadev/triple-frontend/issues/870
CSS 작성을 좀 더 쉽고 예측 가능하게 하기 위해서 global reset css를 개선합니다.
https://tailwindcss.com/docs/preflight 기반으로 만들어졌습니다.
- preflight는 [modern-normalize](https://github.com/sindresorhus/modern-normalize) 기반입니다. 브라우저별로 서로 다른 user agent stylesheet 스타일을 동일하게 보정하고, 특정 브라우저의 버그를 고치는 스타일이 들어가 있습니다.
- 일부 기본 스타일을 초기화 해줍니다.
예상하지 못한 ui 변경이 많을 것으로 예상해서 ui-renewal이라는 베이스 브랜치를 하나 만들어서 여기에서 작업합니다
chromatic에서 확인된 영향을 받은 컴포넌트들의 스타일을 수정합니다.
> [core-elements] global-style 개선

- packages/replies/src/list/reply.tsx
액션시트 타이틀을 댓글/답글 상태와 작성자를 이용해서 세밀화합니다.
**as-is** 
작성자를 이용해서 구분합니다. 
- 댓글 / 답글을 구분할 수 없는 어려움이 존재
1. 내 댓글
2. 댓글 
**to-be**
작성자와 ParentId를 이용해서 구분합니다.
- 댓글 / 답글 / 내가 작성한 것인지 구분이 가능합니다.
1. 내 댓글 
2. 내 답글
3. 댓글 
4. 답글
[매거진에 댓글달기 테스트 시트 15번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- action sheet title code
> [replies] 액션시트 타이틀을 수정합니다.

- docs/stories/replies/replies.stories.tsx
- package-lock.json
- packages/replies/package.json
- packages/replies/src/list/index.tsx
- packages/replies/tsconfig.build.json
- packages/replies/tsconfig.json
삭제 완료 toast를 렌더링합니다.
[매거진에 댓글달기 테스트 시트 14번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- @titicaca/react-triple-client-interfaces 패키지 추가
- handleReplyDelete 함수에 toast 관련 로직 추가
> [replies] 삭제 완료 toast를 렌더링합니다.

- packages/replies/src/replies.tsx
- packages/replies/src/utils.ts
답글을 생성 시간 기준으로 오름차순 정렬합니다.
[매거진에 댓글 달기 테스트 시트 1번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- 댓글을 fetchAndSet 하는 부분에서 답글을 정렬하도록 코드를 수정합니다.
> [replies] 답글을 생성 시간 기준으로 오름차순 정렬합니다.

- docs/stories/replies/replies.stories.tsx
- packages/replies/src/auto-resizing-textarea.tsx
- packages/replies/src/register.tsx
- packages/replies/src/replies.tsx
- packages/replies/src/types.ts
1 _ placeholder를 댓글과 답글에 따라 다르게 표현합니다.
as-is
- 댓글&답글 : 이 일정에 궁금한 점은 댓글로 써주세요.
to-be 
- 댓글 : 댓글을 입력하세요.
- 답글 : 답글을 입력하세요.
[매거진에 댓글달기 테스트 시트 7번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
2 _ 등록 버튼 위치 및 깨찌는 오류를 수정합니다.
[매거진에 댓글달기 테스트 시트 6번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- placeholder props 제거
- placeholder text 수정
- 등록 버튼 디자인 수정
> [replies] 입력창의 placeholder를 수정합니다.

- packages/replies/src/list/index.tsx
- packages/replies/src/replies-api-clients.ts
- packages/replies/src/replies.tsx
- packages/replies/src/types.ts
API를 2번 호출하는 방식을 이용하여 이전 댓글 더보기를 수정합니다.
[매거진에 댓글 달기 테스트 시트 10번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- 이전 댓글 더보기 렌더링 조건문 수정
> [replies] 이전 댓글 더보기 렌더링 조건을 수정합니다.

- packages/triple-fallback-action/src/index.tsx
https://gist.github.com/gaearon/e7d97cdf38a2907924ea12e4ebdf3c85
서버에서 useLayoutEffect를 호출했을 때 발생하는 워닝을 제거합니다.
> 🩹 서버에서 useLayoutEffect를 호출하지 않도록 변경

- codecov.yml
`codecov/project` 체크를 통과하지 못하는 PR이 많습니다.
codecov 기본 컨픽으로는 코드 커버리지가 이전보다 줄어들면 실패하게 되는데
몇몇 PR에서 -0.01% 같은 유의미하지 못한 정도의 오차가 종종 있습니다.
codecov 컨픽을 추가하고 threshold 값을 지정해서 이런 fail은 발생하지 않게 느슨하게 풀어줍니다.
https://docs.codecov.com/docs/common-recipe-list#ease-target-coverage
> codecov 컨픽을 추가하고 threshold을 조금 느슨하게 설정

- docs/stories/triple-email-document/images.stories.tsx
- packages/action-sheet/src/components/action-item.tsx
- packages/app-installation-cta/src/image-banner.tsx
- packages/core-elements/src/elements/spinner/spinner.tsx
- packages/core-elements/src/elements/video/mute-unmute-button.tsx
- packages/core-elements/src/elements/video/play-pause-button.tsx
- packages/core-elements/src/elements/video/seeker.tsx
- packages/core-elements/src/elements/video/use-video-control.ts
- packages/core-elements/src/elements/video/video-frame.tsx
- packages/form/src/select/index.tsx
- packages/i18n/src/provider.tsx
- packages/modals/src/actions.tsx
- packages/poi-detail/src/recommended-articles/recommended-articles.tsx
- packages/pricing/src/fixed-pricing-v2/index.tsx
- packages/pricing/src/fixed-pricing.tsx
- packages/pricing/src/index.tsx
- packages/recommended-contents/src/index.tsx
- packages/review/src/review-element/images/index.tsx
- packages/review/src/review-element/images/penta-images.tsx
- packages/review/src/sorting-options.tsx
- packages/search/src/index.tsx
- packages/static-map/src/index.tsx
- packages/triple-document/src/types.ts
- packages/triple-media/src/index.tsx
- TF 패키지 내 남아 있는 react 참조를 제거합니다.
> TF 패키지 내 react 참조를 제거합니다.

- package-lock.json
- packages/modals/package.json
- packages/modals/src/login-cta-modal.tsx
- packages/review/package.json
- packages/review/src/review-element/images/index.tsx
- packages/review/src/review-element/images/multiple-images.tsx
- packages/review/src/review-element/images/penta-images.tsx
- packages/review/src/review-element/images/single-image.tsx
- packages/review/src/review-element/index.tsx
- packages/review/src/reviews-list.tsx
- packages/review/src/use-client-actions.tsx
- packages/triple-document/package.json
- packages/triple-document/src/elements/images.tsx
- packages/triple-document/src/elements/tna/product.tsx
- 기존에 몇몇 기능들 중 semver로 버전 분기에 따라 사용되었던 부분들을 제거합니다.
> 구버전 클라이언트 대응 분기(semver)를 제거합니다.

- .eslintignore
- docs/stories/poi-list-elements/poi-card-element.stories.tsx
- packages/poi-list-elements/src/carousel-element.tsx
- packages/poi-list-elements/src/compact-poi-list-element.tsx
- packages/poi-list-elements/src/extended-poi-list-element.tsx
- packages/poi-list-elements/src/index.tsx
- packages/poi-list-elements/src/poi-card-element/poi-card-element.tsx
- packages/poi-list-elements/src/types.ts
Related to #1755 
#1737  에서 비활성화했던 poi-list-elements 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
`POICardElement` => `PoiCardElement`로 네이밍 변경 
`POIListElementBaseProps` => `PoiListElementBaseProps`로 네이밍 변경
> [poi-list-elements] ESLint 검사를 활성화하고 오류를 수정합니다. 

- .eslintignore
- packages/hub-form/src/cell.tsx
- packages/hub-form/src/cta.tsx
- packages/hub-form/src/hub-form.tsx
#1755
#1737 에서 비활성화했던 hub-form 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [hub-form] ESLint 검사를 활성화하고 오류를 수정합니다.

- .eslintignore
- .stylelintignore
- packages/form/src/action-sheet-selector/action-sheet.tsx
- packages/form/src/confirm-checkbox/index.tsx
- packages/form/src/input/index.tsx
- packages/form/src/select/index.tsx
- packages/form/src/textarea/index.tsx
#1755
#1737 에서 비활성화했던 form 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [form] 디렉토리의 ESLint, Stylelint 검사를 활성화합니다.

- .eslintignore
- packages/search/src/index.tsx
#1755
#1737 에서 비활성화했던 search 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [search] ESLint 검사를 활성화하고 오류를 수정합니다.

- .eslintignore
- packages/slider/src/handle.tsx
- packages/slider/src/range-slider.tsx
- packages/slider/src/single-slider.tsx
- packages/slider/src/slider-base.tsx
- packages/slider/src/track.tsx
#1755
#1737에서 비활성화했던 slider 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [slider] 디렉토리의 ESLint 검사를 활성화하고 오류를 수정합니다.

- .eslintignore
- packages/pricing/src/fixed-pricing-v2/index.tsx
- packages/pricing/src/fixed-pricing.tsx
#1755
#1737 에서 비활성화했던 pricing 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [pricing] ESLint 검사를 활성화하고 오류를 수정합니다.

- .eslintignore
- packages/recommended-contents/src/index.tsx
#1755
#1737  에서 비활성화했던 recommended-contents 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [recommended-contents] ESLint 검사를 활성화하고 오류를 수정합니다. 

- .eslintignore
- packages/image-carousel/src/carousel.tsx
- packages/image-carousel/src/index.tsx
#1755
#1737 에서 비활성화했던 image-carousel 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [image-carousel] ESLint 검사를 활성화하고 오류를 수정합니다.

- MIGRATION.md
네이밍 변경에 대한 마이그레이션 가이드를 추가합니다.
- POICardElement => PoiCardElement
- POIListElementBaseProps => PoiListElementBaseProps
> [migration] poi-list-elements 누락된 마이그레이션 가이드를 추가합니다.

- .eslintignore
- packages/content-sharing/src/index.tsx
#1755
#1737 에서 비활성화했던 content-sharing 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
> [content-sharing] ESLint 검사를 활성화하고 오류를 수정합니다.

- .eslintignore
- packages/poi-detail/src/copy-action-sheet-item.tsx
- packages/poi-detail/src/detail-header-v2/index.tsx
- packages/poi-detail/src/detail-header/index.tsx
- packages/poi-detail/src/image-carousel/carousel.tsx
- packages/poi-detail/src/image-carousel/index.tsx
- packages/poi-detail/src/recommended-articles/article-entry.tsx
- packages/poi-detail/src/recommended-articles/recommended-articles.tsx
`poi-detail` 패키지에 react-triple-client-interfaces 적용을 준비중입니다. 린팅부터 활성화합니다.
- `.eslintignore`에서 `poi-detail`을 제거합니다.
- `eslint:fix`를 실행하고, Naming convention 오류에 대응합니다.
- Props 스키마에 변화가 있습니다. Breaking change입니다.
> [poi-detail] Linting을 활성화합니다.

- .eslintignore
- packages/i18n/src/backend.ts
- packages/i18n/src/i18next.ts
> [i18n] Lint error를 수정합니다.

- package-lock.json
- package.json
https://github.com/titicacadev/triple-frontend/pull/1980 의 오류가 수정되었습니다. 🎉
- @swc/core 1.2.148 -> 1.2.159
> [etc] update dependency @swc/core to v1.2.159

- packages/user-verification/README.md
> [user-verifications] docs의 오타를 수정합니다.

- packages/triple-document/src/elements/coupon/coupon-download-buttons.tsx
- packages/triple-document/src/elements/coupon/index.tsx
- `CouponGroupDownloadButton`에 타이머 적용
- `CouponDownloadButton`의 `disabledButton` 로직 변경
> [triple-document] 타이머 기능 그룹 다운로드 버튼에 적용

- docs/stories/__mocks__/slots.sample.json
- packages/triple-document/src/elements/tna/product.tsx
- packages/triple-document/src/elements/tna/types.ts
관련 쓰레드 : [https://titicaca.slack.com/archives/C9WMUE9DX/p1648522879160739](https://titicaca.slack.com/archives/C9WMUE9DX/p1648522879160739)
- bestSelfPackageDiscountSpec 인터페이스 추가
> Tna Slot에 셀프패키지 노출

- codecov.yml
codecov patch check를 끕니다.
몇몇 PR에서 `codecov/patch` 체크가 실패합니다.
patch는 PR에서 새로 추가하는 코드가 테스트로 되었는지 확인하는 기능입니다.
하지만 이게 현재 저희의 커버리지 목표는 아니기 때문에 이 기능을 꺼둡니다.
related to https://github.com/titicacadev/triple-frontend/pull/1958
> codecov patch check를 끕니다.

- packages/color-palette/src/colors.ts
- packages/core-elements/src/global-style.ts
소소한 컬러 추가 이슈입니다
항공편 무료수화물 안내 문구 배경색에 사용됩니다
- red50 color 추가
> feat: red50 Color 추가

- docs/stories/poi-detail/detail-header.stories.tsx
- packages/poi-detail/src/detail-header/business-hours-icons.tsx
- packages/poi-detail/src/detail-header/business-hours-note.tsx
- packages/poi-detail/src/detail-header/index.tsx
운영시간, 휴무일을 조건에 따라 렌더링합니다.
[기획](https://titicaca.atlassian.net/wiki/spaces/SPC/pages/2945286251/POI)
> [poi-detail] 운영시간, 휴무일을 조건에 따라 렌더링합니다.

- package-lock.json
- packages/react-triple-client-interfaces/package.json
> [common] rollback pin dependency 

- docs/stories/react-contexts/images-context.stories.tsx
- packages/react-contexts/src/images-context/index.tsx
- 관련슬랙: https://titicaca.slack.com/archives/C6DNCMXUL/p1652847496043119
- #2045 여기서 놓쳤던 타입 및 로직 부분을 수정합니다.
> [react-contexts] `images-context` 내 `images`를 가져오는 `fetch`부분을 수정합니다.

- packages/review/src/review-element/index.tsx
- packages/review/src/reviews-list.tsx
> feature: 리뷰 이벤트에 review_id 추가

- package-lock.json
- packages/standard-action-handler/package.json
- packages/standard-action-handler/src/index.ts
- packages/standard-action-handler/src/scroll-to-element.ts
- packages/standard-action-handler/src/types.ts
- packages/standard-action-handler/tsconfig.build.json
- packages/standard-action-handler/tsconfig.json
hash를 이용한 스크롤 액션을 추가합니다.
#2053 작업 완료 후 진행합니다.
- `scrollToElement` 를 추가합니다.
- `@titicaca/scroll-to-element`를 의존합니다.
- `@titicaca/scroll-to-element`를 추가합니다.
https://user-images.githubusercontent.com/38130934/168212707-94ee8b6e-4fdf-4a96-a951-55c66970f9d8.mov
> [standard-action-handler] 스크롤 액션을 추가합니다.

- packages/core-elements/src/elements/navbar.tsx
- navbar title을 세로 중앙 정렬하기 위해 line-height를 활용합니다.
- 아이폰 등 일부 에이전트에서 이모지가 텍스트보다 크게 그려져 잘리는 현상을 해결합니다.
[`core-elements/src/elements/navbar.tsx`](https://github.com/titicacadev/triple-frontend/compare/fix/navbar-title-vertical-overflow?expand=1#diff-68858ac373584922aeaa7343bd1060e298dcfa13e82cf7bc47bdef954b651b92): 세로 정렬하기 위한 margin을 제거하고 navbar을 채우는 line-height을 설정합니다.
> navbar title을 세로 중앙 정렬하기 위해 line-height를 활용합니다.

- packages/triple-document/src/triple-document.tsx
`triple-document`에서 기본적으로 제공하는 `standard-action-handler`에 새 창 열기에 필요한 `routeExternally`를 추가합니다.
`standard-action-handler`의 `initialize`에 `routeExternally`를 추가합니다.
> [triple-document] StandardActionHandler 새 창 열기 기능에 필요한 props를 추가합니다.

- packages/review/src/services/use-reviews.ts
- 관련 슬랙 : https://titicaca.slack.com/archives/C9WMUE9DX/p1657534143836379?thread_ts=1657528396.950039&cid=C9WMUE9DX
- 각 호텔, 맛집, 관광지, 투어티켓 페이지 내에서 리뷰 삭제 및 수정 시 refetch가 가능하도록 `use-query` options을 수정합니다.
> [review] `use-reviews` 내 `useQuery` `options`을 수정합니다.

- .eslintrc.js
- packages/review/src/components/review-element/user.tsx
- packages/review/src/components/review-placeholder-with-rating.tsx
- packages/review/src/components/types.tsx
- packages/review/src/data/generated/graphql.ts
- packages/review/src/data/graphql/query.graphql
- packages/review/src/services/generated/query.ts
- 관련 피그마 : https://www.figma.com/file/KB5lESskvAavXvY8KgbfRP/20220502_%EB%A6%AC%EB%B7%B0-%EB%8F%99%EC%98%81%EC%83%81-%EC%B2%A8%EB%B6%80-%26-%EC%B5%9C%EA%B7%BC-%EB%B0%A9%EB%AC%B8-%EA%B5%AC%EB%B6%84?node-id=2105%3A29383
- 관련 슬랙 : https://titicaca.slack.com/archives/C03DA2QG3KK/p1657775174296529?thread_ts=1656921656.381319&cid=C03DA2QG3KK
- 디자인 QA를 적용하고 Review 스키마의 badges 쿼리 및 타입을 수정합니다.
> [review] `Review` 스키마의 `badges` 쿼리 및 타입을 수정하고 추가 디자인 QA를 적용합니다.

- packages/review/src/data/generated/graphql.ts
- packages/review/src/data/graphql/mutation.graphql
- packages/review/src/services/generated/query.ts
- 관련 슬랙 : https://titicaca.slack.com/archives/C03DA2QG3KK/p1657850076022139?thread_ts=1656586775.096919&cid=C03DA2QG3KK
- [graphql-server](https://triple-dev.titicaca-corp.com/api/graphql)에서 변경된 내용에 맞춰 mutation을 수정합니다.
> [review]`graphql mutation`을 수정합니다.

- packages/view-utilities/src/generate-deep-link/make-deep-link-generator.test.ts
- packages/view-utilities/src/generate-deep-link/make-deep-link-generator.ts
- 관련 슬랙 : https://titicaca.slack.com/archives/C6DNCMXUL/p1659664612575329?thread_ts=1658473609.183009&cid=C6DNCMXUL
- 기존유저 유입이 트래킹되지 않아 해당 파라미터의 default를 true로 적용합니다.
- 전체 웹에 적용하기 위해 해당 함수를 사용하는 곳에 모두 적용하고자 합니다.
- 현재 사용되는 곳이 [2곳](https://github.com/search?q=org%3Atiticacadev+isRetargeting&type=code)이 있는데  해당 부분을 단순히 제거만 하면 되는 부분이라 `breaking change`으로 구분하지 않고 버전 업하면 바로 이 2곳을 제가 직접 수정하는 방향으로 진행해봐도 될까요? 🤔
> `AppsFlyer` 파라미터 중 `is_retargeting` 값을 `true`로 설정합니다.

- docs/package.json
- package-lock.json
- packages/fetcher/package.json
- packages/router/src/local/base-path.test.ts
- packages/router/src/local/link.test.tsx
[#2083 chore(deps): update dependency next to v12.2.4](https://github.com/titicacadev/triple-frontend/pull/2083) 브랜치를 rebase하는 과정에서 오류가 생겨 새로운 브랜치로 다시 올립니다😅
> chore(deps): update dependency next to v12.2.4

- packages/footer/src/default-footer.tsx
> [footer] 대표자 변경: 김강세 --> 최휘영

- .github/workflows/renovate-pr-fix.yaml
- renovate PR 에서 의존성 에러가 발생하는 부분을 gha를 추가하여 해결하고자 합니다.
- renovate PR을 찾아 `npm install` 및 `npm run sync-deps`를 실행하고 commit 및 push를 진행합니다.
> renovate 의존성 에러를 fix하는 `GHA Workflow`를 추가합니다.

- .github/workflows/renovate-pr-fix.yaml
- https://github.com/titicacadev/triple-frontend/pull/2125 요게 조금 꼬여서 다시 PR을 작성했습니다! 🙇 
- renovate/* => 'renovate/**' 로 수정하여 적용합니다.
> `renovate-pr-fix GHA 동작` 중 `branches option`을 수정합니다. 

- .github/workflows/renovate-pr-fix.yaml
- `pull_requset`에서 `push`로 트리거를 변경합니다.
- 누락된 `NODE_AUTH_TOKEN` 추가 했습니다.
> `renovate-pr-fix GHA` 트리거를 수정하고 누락된 `NODE_AUTH_TOKEN`를 추가합니다.

- .github/workflows/ci.yaml
- .github/workflows/renovate-pr-fix.yaml
- https://github.com/titicacadev/triple-frontend/pull/2128 와 같이 `renovate-pr-fix GHA` 정상 동작하지만 required한 CI 동작들이 통과되지 않아 CI 동작을 추가합니다.
> `renovate-pr-fix GHA` 동작에 CI를 추가합니다.

- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/media/index.tsx
- packages/review/src/services/use-client-actions.tsx
[review] 리뷰 썸네일 클릭시 이미지 뷰어로 이동
리뷰 썸네일 클릭시 이미지 뷰어로 이동
> [review] 리뷰 썸네일 클릭시 이미지 뷰어로 이동

- packages/constants/src/regex.ts
지라 : [https://titicaca.atlassian.net/browse/AIR-2365](https://titicaca.atlassian.net/browse/AIR-2365)
> feat: PASSPORT_NUMBER_REGEX를 15개로 고정

- .github/workflows/ci.yaml
- .github/workflows/renovate-pr-fix.yaml
- 기존 workflow_call 방식은 CI 액션을 콜하는 과정에서 
```
- name: If working tree dirty, shutdown job
id: check-working-tree-clean
run: |
if [[ $(git diff --stat) != '' ]]; then
git diff --stat
exit 1
fi
```
해당 부분에서 shutdown이 이루어져 다른 방식의 workflow_call을 적용하고자 했습니다.
- 이욜이 말씀해주신 [workflow trigger](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow)를 적용합니다.
- `GHA_TOKEN`를 사용하여 트리거를 적용합니다.
- CI의 `workflow_call`를 제거합니다.
> `renovate-pr-fix GHA` 동작에서 `GHA_TOKEN`를 이용하여 트리거를 적용합니다.

- .github/workflows/ci.yaml
- .github/workflows/renovate-pr-fix.yaml
- 관련 슬랙 : https://titicaca.slack.com/archives/CEEPB4TDY/p1663827441364799
- #2147에서 불필요하게 `GHA_TOKEN`을 사용하여 revert 했고 해당 부분을 제외한 PR을 다시 올립니다.
> `renovate-pr-fix GHA 동작` 중 `commit action`에 `GHA_TOKEN`를 이용하여 트리거합니다.

- packages/core-elements/src/elements/video/video-element.tsx
- packages/core-elements/src/elements/video/video.tsx
- packages/image-carousel/src/content.tsx
- packages/image-carousel/src/image-carousel.tsx
- packages/image-carousel/src/image-content.tsx
- packages/image-carousel/src/video-content.tsx
- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/media/elements.ts
- packages/review/src/components/review-element/media/index.tsx
- packages/review/src/components/review-element/media/video.tsx
- packages/triple-document/src/elements/images.tsx
- packages/triple-media/src/index.tsx
https://titicaca.slack.com/archives/C03DA2QG3KK/p1663583741107319
https://titicaca.slack.com/archives/C01PZ4M58G2/p1663729898261629
동영상 리뷰 QA에서 발견된 버그 수정입니다.
> [review] 동영상 리뷰 QA

- .github/workflows/ci.yaml
- `check-working-tree-clean`가 skip 되는 경우에는 의존성 실패 메세지가 전송되지 않도록 합니다.
> `CI GHA`에서 `check-working-tree-clean` 액션이 skip 되는 경우 의존성 실패 메세지가 전송되지 않도록 합니다.

- .github/workflows/ci.yaml
- renovate-pr-fix 액션에 필요한 commit 관련 env 변수를 추가합니다.
> `CI GHA`동작에 누락된 ENV 변수 를 추가합니다.

- .github/workflows/renovate-pr-fix.yaml
- CI 내 renovate 액션을 넣어 적용해도 renovate-pr-fix 내에서 secrets.GHA_TOKEN을 사용하여 트리거해도 브랜치 룰을 통과할 수 없었습니다.
- 때문에 github 문서내 명시 되어 있는 방법을 사용하여 [브랜치 우회 전략](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#example) 시도하고자 합니다.
- `check-dependencies`를 제외한 나머지 동작들은 CI 액션에서도 통과하기에 단순 skip을 진행합니다.
> `renovate pr fix GHA`를 분리하고 `branch protection rule`를 우회합니다.

- .github/workflows/ci.yaml
- .github/workflows/renovate-pr-fix.yaml
- 기존 `GHA_TOKEN`에서 `TRIPLE_BOT_GITHUB_TOKEN`으로 토큰을 변경합니다.
- 트리거가 되어 `renovate-pr-fix GHA`가 2번 실행되는 걸 방지합니다.
> `renovate-pr-fix GHA`에서 `TRIPLE_BOT_GITHUB_TOKEN`를 사용하여 트리거합니다.

- package-lock.json
- packages/react-contexts/package.json
- packages/react-contexts/src/event-tracking-context/event-tracking-context.tsx
firebase의 버전을 v9로 업그레이드합니다.
- #1571 
- [firebase v9 업그레이드 가이드 문서](https://titicaca.atlassian.net/wiki/spaces/dev/pages/3202777132/TF+firebase+v9)
- triple-auth-web에 적용한 [업그레이드 예시 PR](https://github.com/titicacadev/triple-auth-web/pull/198)입니다.
> [react-context] firebase v9 업그레이드

- MIGRATION.md
v9 to v10 마이그레이션 문서에 파이어베이스 업그레이드 문서 링크를 추가했습니다.
> v9 to v10 마이그레이션 문서를 추가합니다.

- package.json
prettier 명령어를 js,ts,tsx도 검사하도록 수정합니다. 
- https://github.com/titicacadev/eslint-config-triple/issues/205
- https://titicaca.slack.com/archives/CEEPB4TDY/p1666838721566149
- eslint-config-triple 4.0.0부터는 프리티어로 체크해야 하므로 명령어를 변경합니다.
> [Fix] prettier 명령어를 js,ts,tsx도 검사하도록 수정합니다. 

- .github/workflows/cd.yaml
- package-lock.json
- packages/chat/README.md
- packages/chat/package.json
- packages/chat/src/bubble-info.stories.tsx
- packages/chat/src/bubble-info.tsx
- packages/chat/src/bubbles/__stories__/constants.ts
- packages/chat/src/bubbles/__stories__/image.stories.tsx
- packages/chat/src/bubbles/__stories__/rich.stories.tsx
- packages/chat/src/bubbles/__stories__/text.stories.tsx
- packages/chat/src/bubbles/image.tsx
- packages/chat/src/bubbles/index.ts
- packages/chat/src/bubbles/rich.tsx
- packages/chat/src/bubbles/text.ts
- packages/chat/src/chat-bubble-ui.stories.tsx
- packages/chat/src/chat-bubble-ui.tsx
- packages/chat/src/chat-bubble.tsx
- packages/chat/src/elements.tsx
- packages/chat/src/index.tsx
- packages/chat/src/types/index.ts
- packages/chat/src/utils/fetch.ts
- packages/chat/src/utils/image.ts
- packages/chat/tsconfig.build.json
- packages/modals/src/login-cta-modal.tsx
- packages/modals/src/modal/modal-context.tsx
- tsconfig.json
[triple-chat-frontend](https://github.com/titicacadev/triple-chat-frontend) 레포지토리에 있는 패키지를 TF 내부로 이동합니다. 
- 관련 이슈: https://github.com/titicacadev/triple-frontend/issues/2130
- 관련 스레드: https://titicaca.slack.com/archives/C02UED2AZAP/p1665449131850309
코드에 대한 변경점은 없고 린트, 스토리북 실행 시 에러 나는 부분만 수정했습니다. 
https://github.com/titicacadev/triple-frontend/pull/2231 리뷰 반영했습니다. 
다음 작업으로 위젯화를 해볼 예정입니다.
사용부는 검색 결과 아래 3개입니다. 
- [tna-booking-admin](https://github.com/titicacadev/tna-booking-admin)
- [triple-chat-web](https://github.com/titicacadev/triple-chat-web)
- [tna-partners-web](https://github.com/titicacadev/tna-partners-web)
as-is
```
"@titicaca/chat-bubble": "1.1.0",
"@titicaca/chat-types": "1.1.0",
```
to-be
```
"@titicaca/chat": "11.0.0",
```
스토리북: …
> [chat] triple-chat-frontend 패키지 이동

- package-lock.json
- packages/poi-detail/package.json
- packages/poi-detail/src/actions.tsx
- packages/poi-detail/tsconfig.build.json
- packages/poi-detail/tsconfig.json
동영상 첨부 기능을 더 많은 사용자에게 알리기 위해 POI 상세 페이지에 최초 진입 시, 툴팁을 노출합니다.
[[리뷰 동영상 첨부 유도하기 - POI 상세 툴팁 노출] 스레드](https://titicaca.slack.com/archives/C03DA2QG3KK/p1665729439633439)
- POI 페이지가 열리면 `localStorage`에 `REVIEW_TOLLTIP_EXPOSED` 값을 저장합니다. 
- 저장하기 전 `REVIEW_TOLLTIP_EXPOSED`값이 로컬스토리지에 저장되어있는 지 구분하여 툴팁을 띄웁니다.
- `web-storage` 패키지를 사용합니다.
> 리뷰 쓰기 영역에 툴팁 추가

- package-lock.json
- packages/core-elements/package.json
- packages/core-elements/src/elements/checkbox/checkbox-group-base.tsx
- packages/core-elements/src/elements/checkbox/checkbox-group-context.tsx
- packages/core-elements/src/elements/checkbox/checkbox-group.stories.tsx
- packages/core-elements/src/elements/checkbox/checkbox-group.tsx
- packages/core-elements/src/elements/checkbox/checkbox.stories.tsx
- packages/core-elements/src/elements/checkbox/checkbox.tsx
[core-elements] 접근성 지원되는 Checkbox 컴포넌트 추가
- 많이 사용되는 디자인인데 공용 컴포넌트가 없어서 추가합니다.
- Checkbox 컴포넌트는 `label` 태그로 감싸서 스크린 리더가 내용을 설명할 수 있도록 합니다.
- CheckboxGroup 컴포넌트는 옵셔널로 사용되며 Checkbox 컴포넌트들을 감쌀 수 있습니다. 선택된 체크박스들의 value 값들을 배열로 간단하게 가져올 수 있습니다.
크로마틱
> [core-elements] 접근성 지원되는 Checkbox 컴포넌트 추가

- packages/react-contexts/src/my-reviews-context/api-client.ts
- packages/react-contexts/src/my-reviews-context/my-reviews-provider.tsx
[TRIPLE-CONTENT-WEB-A6S
](https://sentry.io/organizations/titicaca-corp/issues/3648661673/?query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d)
[TRIPLE-HOTELS-WEB-7BT
](https://sentry.io/organizations/titicaca-corp/issues/3679989256/?query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d)
- 에러 원인을 파악하기 위해서 에러 메시지에 resourceId를 추가합니다.
- 불필요한 useCallback dep을 제거합니다.
> [react-contexts] checkIfReviewed 에러 로깅에 정보 추가

- packages/chat/src/chat/chat.tsx
- packages/core-elements/src/elements/flex-box/flex-box.tsx
- packages/core-elements/src/elements/portal/portal.tsx
renewal-ui 자잘한 버그들 수정하였습니다.
- Chat 컴포넌트에서 css prop name을 cssProp으로 변경합니다.
- FlexItem Prop에 HTMLAttributes type도 추가합니다.
- chat-web에 카나리 임시 적용 중 Portal 컴포넌트에서 document is not defined 이슈가 발견되어 수정하였습니다.
> [common] renewal-ui 버그 수정 

- packages/core-elements/src/elements/select/select.stories.tsx
- packages/core-elements/src/elements/select/select.tsx
[core-elements] Select 접근성 개선
- form-field를 사용해서 aria state, property를 추가합니다.
- frame (div) 대신 select를 스타일링 하도록 변경합니다.
- 아이콘을 png -> svg로 변경합니다.
- (breaking change) onChange 콜백의 두번째 파라미터 value를 제거합니다. 오리지널 ChangeEventHandler 타입을 사용할 수 있습니다.
ref: https://w3c.github.io/aria/#combobox
크로마틱
> [core-elements] Select 접근성 개선

- packages/core-elements/src/elements/form.stories.mdx
- packages/core-elements/src/elements/textarea/textarea.stories.tsx
- packages/core-elements/src/elements/textarea/textarea.tsx
[core-elements] Textarea 접근성 개선
- textarea에 aria state, property를 추가합니다.
ref: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/textbox_role
> [core-elements] Textarea 접근성 개선

- packages/core-elements/src/global-style.ts
[core-elements] 기본 line-height를 1에서 normal로 변경
원래 모습과 달라지는 부분이 많아서 변경합니다.
> [core-elements] 기본 line-height를 1에서 normal로 변경

- packages/core-elements/src/elements/tooltip/tooltip.tsx
[core-elements] Tooltip 컴포넌트에 role="tooltip" 추가
Tooltip 컴포넌트에 role="tooltip" 추가
ref: https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/
> [core-elements] Tooltip 컴포넌트에 role="tooltip" 추가

- packages/action-sheet/src/action-sheet-item.tsx
closes https://github.com/titicacadev/triple-frontend/issues/599
ActionSheetItem를 flex layout으로 변경
크로마틱
> [action-sheet] ActionSheetItem를 flex layout으로 변경

- packages/core-elements/src/elements/numeric-spinner/index.ts
- packages/core-elements/src/elements/numeric-spinner/numeric-spinner-base.tsx
- packages/core-elements/src/elements/numeric-spinner/numeric-spinner.stories.tsx
- packages/core-elements/src/elements/numeric-spinner/numeric-spinner.tsx
closes https://github.com/titicacadev/triple-frontend/issues/1228
- NumericSpinner에서 저 부분을 NumericSpinnerBase로 분리하고 export합니다.
- disabled Prop을 추가합니다.
- step Prop을 추가합니다.
- (Breaking Change) min Prop의 기본값을 1 -> 0으로 변경합니다. min 기본값이 value  기본값보다 큰게 이상해서 변경했습니다. https://github.com/titicacadev/triple-hotels-web/blob/a35ba32dc6a9a2865be19ef7530bd7849afd4366/src/children-age-input/index.tsx#L43 에서 기본값 지정이 필요합니다.
- (Breaking Change) borderless Prop을 제거합니다. 모든 곳에서 쓰이고 있어서 기본 border를 없앴습니다.
크로마틱
> [core-elements] export NumericSpinnerBase

- packages/footer/src/default-footer.tsx
> [Footer] 회사 소개 영역을 제거합니다.

- packages/chat/src/chat/chat.tsx
모바일 접속할 때 채팅 스크롤이 내려가지 않은 이슈를 발견해 수정합니다.
초기 스크롤을 최하단으로 이동하도록 해주는 코드 조건을 수정합니다.
> [chat] 초기 스크롤 다운 처리 조건 수정

- packages/modals/src/modal/modal-base.tsx
z-index를 큰 값으로 수정합니다.
- 다른 요소에 z-index가 들어있는 경우가 있어 z-index를 추가했습니다.
> [modals] z-index를 큰 값으로 수정

- packages/triple-document/src/elements/regions.tsx
- 관련 슬랙 : https://titicaca.slack.com/archives/CEEPB4TDY/p1670398095419859
- region element의 바로가기 버튼 위치를 조정합니다.
> [triple-document] regions element의 바로가기 버튼 위치를 조정합니다.

- package-lock.json
- packages/public-header/package.json
- packages/public-header/tsconfig.build.json
- packages/review/package.json
- packages/review/tsconfig.build.json
- packages/user-verification/package.json
- packages/user-verification/tsconfig.build.json
@titicaca/react-triple-client-interfaces를 peer dependency로 변경 2
https://github.com/titicacadev/triple-frontend/pull/2295 에서 빠뜨린 패키지가 있었습니다.
> @titicaca/react-triple-client-interfaces를 peer dependency로 변경 2

- packages/core-elements/src/global-style.ts
- table 간격이 넓게 적용되고 있어 global css를 수정합니다.
- table 에 border-spacing: 0 추가
- tr, td, th에 padding: 0 추가
> table 관련 global css 수정

- package-lock.json
- packages/intersection-observer/package.json
react-intersection-observer 버전 업데이트
- peer dependency react 18 추가된 버전으로 업데이트합니다.
> react-intersection-observer 버전 업데이트

- packages/triple-document/src/elements/itinerary.tsx
Triple document 에서 styled component 오류를 수정합니다. 
styled component undefined 오류가 발생하는 부분을 수정했습니다. 
버전이 올라가면서 에러가 된 것 같습니다
> [triple-document] styled component undefined 오류 수정

- packages/core-elements/src/mixins/box.ts
- packages/hub-form/src/hub-form.stories.tsx
- shadow none option을 추가했습니다.
- 타입에는 없지만.. 기존에도 쓰이고 있고, 코드 상으로는 none도 가능해서 맞추기 위해 추가해 주었습니다. 
https://617b7c4431c922004a42c7cc-gemcrgisxb.chromatic.com/?path=/story/hub-form-hubform--shadow
> [hub form] shadow none option 추가

- packages/core-elements/src/elements/numeric-spinner/numeric-spinner-base.tsx
- packages/core-elements/src/elements/numeric-spinner/numeric-spinner.stories.tsx
- packages/core-elements/src/elements/numeric-spinner/numeric-spinner.tsx
> [core-elements] numeric spinner 스타일 조정

- packages/modals/src/alert/alert.tsx
- packages/modals/src/modal/modal-description.tsx
- packages/modals/src/modal/modal-title.tsx
- 텍스트 가운데정렬, alert color 기본값 변경 하였습니다. 
개선된 modal이 기존과 다르게 적용된 스타일이 있어 수정합니다. 
- 화면 보면서 다른부분 그때그때 체크하다보니까 pr이 너무 쪼개지는 것 같은데 이 다음부터는 작은건 모아서 올려보겠습니다 🙇🏻
- as-is
- to-be
> [modals] 텍스트 가운데정렬, alert color 기본값 변경 

- packages/react-contexts/src/session-context/browser.tsx
웹 환경에서 로그아웃 할 때 401 응답이 오는 경우에도 로그아웃이 정상적으로 처리되도록 수정합니다.
관련 슬랙:
- https://titicaca.slack.com/archives/CBK006NR5/p1671595290695449
- https://titicaca.slack.com/archives/C02UED2AZAP/p1671596687807739
> [react-contexts] 웹 로그아웃 시 401 응답도 정상적으로 처리하도록 합니다.

- packages/modals/src/alert/alert.tsx
- packages/modals/src/confirm/confirm.tsx
- modal handler에서 onClose 실행 분기문을 이전 버전과 동일한 조건으로 변경합니다.
- [관련 스레드](https://titicaca.slack.com/archives/C02UED2AZAP/p1674032084062209?thread_ts=1673936777.970379&cid=C02UED2AZAP)
- ActionSheet에 이어 Alert,Confirm도 분기문을 같게 수정합니다.
> [Modals] modal handler onClose 실행 분기문 이전 버전과 동일하게 변경

- .github/workflows/cd.yaml
cd workflow 에러를 수정합니다. 
- https://github.com/titicacadev/triple-frontend/pull/2340 의 영향을 받은 것 같습니다. 
actions/checkout@v3을 해주지 않을 경우 에러가 나고 있어 추가했습니다. 
https://github.com/titicacadev/triple-frontend/actions/runs/3963217885/jobs/6790897670
> cd workflow 에러 수정 

- packages/view-utilities/src/routelist/routelist.ts
- 관련 미로페이지 : https://miro.com/app/board/uXjVPerOKGM=/
- 위의 동선 의도에 맞게 /redirect (triple-redirection-pages)를 이용할 때 앱 설치 유도 모달을 띄우지 않도록 해당 path를 추가합니다.
> [view-utilities] public route list에 `/redirect`를 추가합니다.

- packages/core-elements/src/elements/confirm-selector/confirm-selector-base.tsx
- packages/core-elements/src/elements/confirm-selector/confirm-selector.tsx
[core-elements] ConfirmSelector 디자인 수정
ConfirmSelector를 리팩토링 하면서 구조만 잡아놓고 임시 디자인이 그대로 배포되어버렸습니다. 
디자인을 원래대로 변경합니다.
> [core-elements] ConfirmSelector 디자인 수정

- packages/core-elements/src/elements/rating/rating.stories.tsx
- packages/core-elements/src/elements/rating/rating.tsx
- [core-elements] Rating 컴포넌트에 최대값,최소값 설정 추가합니다.
- close #2357 
- Rating 컴포넌트에 최대값,최소값 설정을 추가해 안정성을 높입니다.
- 스토리를 prop 타입 별로 추가합니다.
> [core-elements] Rating 컴포넌트에 최대값,최소값 설정 추가

- packages/action-sheet/src/action-sheet-overlay.tsx
- action-sheet에 pointer-events css를 추가합니다.
- [관련 스레드](https://titicaca.slack.com/archives/C02UED2AZAP/p1675318746904259)
- [pointer-events 관련 참고 블로그](https://webdir.tistory.com/506)
- 안드로이드 웹뷰에서만 이벤트가 활성화되게 구현되어있었나 봅니다..
- 11버전 관련 코드 https://github.com/titicacadev/triple-frontend/blob/v11.1.0/packages/action-sheet/src/components/action-sheet.tsx#L116-L124
확인 경로
- Dev > 여행 홈 > 라운지 > 여행기 작성 > 삭제
- Dev > My 여행기 > 삭제
> [action-sheet] pointer-events css 추가 

- packages/i18n/src/assets/ja/common-web.ts
- packages/i18n/src/assets/ko/common-web.ts
- packages/i18n/src/assets/zh/common-web.ts
- packages/modals/src/transition-modal.tsx
설치유도팝업의 문구를 수정합니다.
[관련 스레드](https://titicaca.slack.com/archives/CE1TS26GK/p1675390254408289?thread_ts=1672730534.784689&cid=CE1TS26GK)
※ 국제화 기본 언어가 한국어로 설정되어 있기 때문에 일본어, 중국어 텍스트가 없는 경우 한국어 텍스트를 사용하게 됩니다. 따라서 일단은 한국어 텍스트만 추가하는 방향으로 가겠습니다!
|As-is|To-be|
|-|-|
|<img width="339" alt="스크린샷 2023-02-03 12 08 24" src="https://user-images.githubusercontent.com/50892653/216503389-dd3af440-804a-48e7-a0a8-6631fc709b25.png">|<img width="332" alt="스크린샷 2023-02-03 12 05 17" src="https://user-images.githubusercontent.com/50892653/216503393-768b056e-26c6-4640-af24-0c9b88538302.png">|
> [modals] 설치유도팝업 문구를 수정합니다.

- packages/i18n/src/assets/ja/common-web.ts
- packages/i18n/src/assets/ko/common-web.ts
- packages/i18n/src/assets/zh/common-web.ts
- packages/modals/src/transition-modal.tsx
https://github.com/titicacadev/triple-frontend/pull/2379 PR에서 작업한 설치유도모달 텍스트 수정 결과물을 [GA, FA 로깅 수정 작업](https://github.com/titicacadev/triple-frontend/pull/2354) 이후에 배포하기 위해 설치유도모달 텍스트를 기존 버전으로 되돌립니다 🙇
> 설치유도모달 텍스트를 이전 버전으로 되돌림

- package-lock.json
- package.json
- packages/fetcher/package.json
- #2361 와 동일한 PR입니다.(패키지 버전이 꼬여서 새로만들었습니다.)
> chore(deps): update dependency next to v13.1.6 

- package-lock.json
- package.json
https://titicaca.slack.com/archives/C02UED2AZAP/p1675737058980299
@titicaca/next-i18next 13.8.5를 추가합니다.
tsc 빌드 속도를 개선합니다.
> @titicaca/next-i18next 추가

- packages/modals/src/transition-modal.tsx
- 설치유도팝업 TransitionType에 loungeHome을 추가합니다. ([관련 스레드](https://titicaca.slack.com/archives/C047AUFRRJ7/p1675832910897079))
> [Modal] 설치유도팝업 TransitionType에 loungeHome을 추가합니다.

- packages/view-utilities/src/routelist/routelist.ts
- 관련 문서 - https://titicaca.atlassian.net/wiki/spaces/dev/pages/3293413428/PLCC
- #2355 에서 `/redirect`를 포함시켰지만 기획의도가 변경됨에 따라 `/benefit`으로 수정합니다.
- 예시 링크 `/inlink?path=/benefit/nolcard...`
> public route list에 `/redirect`를 제거하고 `/benefit`을 추가합니다.

- packages/public-header/src/extra-actions-container.tsx
- 헤더 컨테이너에 flex와 align-item property를 추가합니다. ([관련 스레드](https://titicaca.slack.com/archives/C047AUFRRJ7/p1675923745698359?thread_ts=1670214843.023309&cid=C047AUFRRJ7))
> PublicHeader의 일부 css 속성을 수정합니다

- packages/core-elements/src/elements/gender-selector/gender-selector-item.tsx
- packages/core-elements/src/elements/gender-selector/gender-selector.tsx
- packages/core-elements/src/elements/radio/radio-group.tsx
radio-group & gender-selector 가 disabled 속성을 받을 수 있도록 변경합니다.
> [core-elements] gender-selector 에 disabled 속성을 추가합니다.

- package-lock.json
- packages/core-elements/src/elements/drawer/drawer.tsx
- packages/drawer-button/src/index.tsx
- packages/modals/src/modal/modal-base.tsx
- packages/popup/package.json
- packages/popup/src/index.tsx
오버레이 되는 컴포넌트에 Portal 사용하고 z-index 값 변경
[core-elements] 
- Drawer의 layeringProps을 제거하고 z-index를 9999로 변경합니다.
- Drawer를 Portal로 렌더합니다.
[drawer-button]
- DrawerButton의 layeringProps를 제거합니다.
[modals]
- Modal의 z-index를 9999로 변경합니다.
[popup]
- Popup의 layeringProps을 제거하고 z-index를 9999로 변경합니다.
- Popup을 Portal로 렌더합니다
https://www.chromatic.com/build?appId=617b7c4431c922004a42c7cc&number=2931
> 오버레이 되는 컴포넌트에 Portal 사용하고 z-index 값 변경

- packages/i18n/src/assets/ja/common-web.ts
- packages/i18n/src/assets/ko/common-web.ts
- packages/i18n/src/assets/zh/common-web.ts
- packages/modals/src/transition-modal.tsx
설치유도팝업의 문구를 수정합니다. ( https://github.com/titicacadev/triple-frontend/pull/2379 PR을 복원합니다)
|As-is|To-be|
|-|-|
|<img width="339" alt="스크린샷 2023-02-03 12 08 24" src="https://user-images.githubusercontent.com/50892653/216503389-dd3af440-804a-48e7-a0a8-6631fc709b25.png">|<img width="332" alt="스크린샷 2023-02-03 12 05 17" src="https://user-images.githubusercontent.com/50892653/216503393-768b056e-26c6-4640-af24-0c9b88538302.png">|
> 설치유도팝업 문구를 수정합니다.

- lerna.json
- package-lock.json
- package.json
lerna 버전 업데이트
lerna 버전 업데이트
packages -> useWorkspaces로 변경  https://lerna.js.org/docs/api-reference/configuration#useworkspaces--packages
> lerna 버전 업데이트

- packages/core-elements/src/global-style.ts
https://titicaca.slack.com/archives/C01CHRQBP1U/p1676959141321259
height: auto는 초기값이고 우선순위 문제로 width, height attribute가 계산한 aspect ratio를 유지하지 못하게 하므로 제거합니다,
> fix(core-elements): img, video global style height: auto 제거

- packages/directions-finder/src/ask-to-the-local.tsx
- drawer 랜더조건을 추가합니다. 
- [관련 스레드](https://titicaca.slack.com/archives/C02UED2AZAP/p1677023673784389)
- 팝업이 오픈되기 전에 drawer이 먼저 떠있는 현상을 수정합니다. 
- 다른 컴포넌트에서도 drawer가 portal을 쓰는 컴포넌트 하위에 있으면 랜더조건을 추가해야 하지 않을지 확인이 필요해 보입니다. 
- 관련 pr: https://github.com/titicacadev/triple-frontend/pull/2404
> [directions-finder] drawer 랜더조건 추가

- packages/app-installation-cta/src/elements.tsx
- packages/app-installation-cta/src/floating-button-cta.tsx
[관련 기획 문서](https://titicaca.atlassian.net/wiki/spaces/SPC/pages/3222044694#3%EC%B0%A8-%EB%B2%84%ED%8A%BC-%EC%B6%94%EA%B0%80)
[피그마](https://www.figma.com/file/KRUG0gxPAFdgRPKe4m7AMH/%E1%84%8B%E1%85%B0%E1%86%B8-%ED%94%8C%EB%A1%9C%ED%8C%85-%E1%84%87%E1%85%A2%E1%84%82%E1%85%A5?node-id=615%3A3275&t=BvPfeUNICyONpGgy-0)
플로팅 버튼 3차 UI 변경안을 반영합니다.
|**As-is**|**To-be**|
|-|-|
|<img width="757" alt="스크린샷 2023-02-21 13 23 11" src="https://user-images.githubusercontent.com/50892653/220248759-d826d49b-0ba8-4ee7-8211-5da729aa6cd7.png">|<img width="802" alt="스크린샷 2023-02-21 13 34 43" src="https://user-images.githubusercontent.com/50892653/220248766-62f998fe-f33b-422a-adda-41892a2205aa.png">|
> 플로팅 버튼 디자인을 수정합니다.

- packages/meta-tags/src/facebook-open-graph-meta.tsx
- 웹 공통으로 사용되는 OG-tag 이미지 URL을 변경합니다.([피그마](https://www.figma.com/file/lWjthw9dRRXbbRvfVDDQBI/%5B%EB%B8%8C%EB%9E%9C%EB%94%A9%5D-%EB%A9%94%EC%8B%9C%EC%A7%80-%ED%86%B5%ED%95%A9(%EC%9B%B9)?node-id=1%3A3667&t=WgzTGiT6zJzzRNBl-4))
- [og-tag-app_download@4x.png](https://assets.triple.guide/images/og-tag-app_download@4x.png)
> [meta-tags] og-tag img URL을 변경합니다.

- packages/replies/src/list/reply.tsx
[JIRA](https://titicaca.atlassian.net/jira/software/projects/TFC/boards/108?selectedIssue=TFC-29)
[관련 쓰레드](https://titicaca.slack.com/archives/C6DNCMXUL/p1677806512068159)
댓글 컴포넌트의 따봉 아이콘이 짤리던 현상을 수정합니다.
> 댓글 따봉 아이콘이 짤리던 현상을 수정합니다.

- packages/action-sheet/src/action-sheet-item.tsx
ActionSheetItem에 notice 아이콘을 추가합니다.
> action-sheet-item에 notice 아이콘 추가

- .github/workflows/ci.yaml
ci: lint job에서 eslint-config-triple 설치하는 스텝 제거
필요 없는 스텝이라서 지웁니다.
> ci: lint job에서 eslint-config-triple 설치하는 스텝 제거

- package-lock.json
- package.json
storybook 관련 모듈 버전 업데이트
storybook 관련 모듈 버전을 업데이트 하고 overrides를 없앱니다.
> storybook 관련 모듈 버전 업데이트

- package-lock.json
renovate pr을 승인했는데 의존성이 업뎃 안된채로 머지되어 수정합니다.
> 의존성 에러 수정 

- package-lock.json
- packages/i18n/package.json
- packages/router/package.json
> chore: 불필요한 의존성 제거

- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/pinned-message.tsx
- packages/review/src/components/types.tsx
- packages/review/src/services/generated/query.ts
파트너 댓글이 있는 경우, 리뷰 목록 화면에서 파트너 댓글을 표시하도록 합니다.
> 리뷰 목록에 pinned message를 노출합니다.

- packages/popup/src/popup.test.tsx
[popup] 외부 클릭시 닫는 테스트 제거
popup은 화면 전체 영역을 차지하므로 외부를 클릭할 수 없습니다.
> [popup] 외부 클릭시 닫는 테스트 제거

- packages/action-sheet/src/action-sheet.test.tsx
- packages/modals/src/modal/modal.test.tsx
https://titicaca.atlassian.net/browse/TFC-72
확실한 원인은 모르겠는데 잘 되는지 시도해봅니다.
> 외부 클릭하면 닫는 테스트가 랜덤하게 실패하는 문제 수정

- .github/workflows/add-label.yaml
릴리즈 브랜치(`release/...`)에 대해선 라벨 자동화를 실행하지 않도록 합니다.
> 릴리즈 브랜치에는 라벨 자동화를 실행하지 않도록 합니다.

- .github/workflows/update-changelog.yaml
- scripts/changelog.js
기존에 쉘 스크립트로 작성된 내용을 자바스크립트로 옮기고, ChatGPT로 하여금 원하는 대답을 안정적으로 내뱉을 수 있도록 프롬프트 수정, 데이터 전처리,  [temperature](https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature)값 수정 등의 내용을 추가합니다.
> CHANGELOG 자동화 로직을 개선합니다.

- .gitignore
- .vscode/settings.json
workspace setting에 eslint 컨픽 추가
vscode-eslint 익스텐션이 모노레포에서 패키지마다 다른 설정을 사용할 수 있도록 vscode workspace setting을 추가합니다.
- https://code.visualstudio.com/docs/getstarted/settings#_workspace-settings
- https://github.com/Microsoft/vscode-eslint#settings-options:~:text=%5B%7B%20%22mode%22%3A%20%22auto%22%20%7D%5D%20(%40since%202.0.0)%3A%20instructs%20ESLint%20to%20infer%20a%20working%20directory%20based%20on%20the%20location%20of%20package.json%2C%20.eslintignore%20and%20.eslintrc*%20files.%20This%20might%20work%20in%20many%20cases%20but%20can%20lead%20to%20unexpected%20results%20as%20well.
> workspace setting에 eslint 컨픽 추가

- packages/image-carousel/src/video-content.tsx
- packages/review/src/components/review-element/media/video.tsx
Sentry에 리포팅된 NotAllowedError
- [reviews-web](https://titicaca-corp.sentry.io/issues/3935752775/?query=NotAllowedError&referrer=issue-stream&statsPeriod=1h&stream_index=0)
- [content-web](https://titicaca-corp.sentry.io/issues/3925948018/?query=NotAllowedError&referrer=issue-stream&statsPeriod=7d&stream_index=0)
- [hotels-web](https://titicaca-corp.sentry.io/issues/4048930230/?query=NotAllowedError&referrer=issue-stream&statsPeriod=7d&stream_index=3)
해당 에러가 발생했을 때 재생/중단 버튼이 나타날 수 있도록 합니다. `reviews-web`은 `Review` 패키지를 사용하고 있고, `content-web`은 `Review` 패키지와 `ImageCarousel` 패키지, `hotels-web`은 `ImageCarousel` 패키지를 사용하고 있습니다.
[관련 슬랙 스레드](https://titicaca.slack.com/archives/CEEPB4TDY/p1685583277053509)
> 비디오 자동 재생 시에 간헐적으로 발생하는 NotAllowedError를 핸들링합니다.

- package-lock.json
- packages/ad-banners/package.json
- packages/ad-banners/src/horizontal-list-view.tsx
- packages/carousel/package.json
- packages/carousel/src/carousel-item.tsx
- packages/carousel/src/carousel.tsx
- packages/image-carousel/package.json
- packages/image-carousel/src/carousel.tsx
- packages/image-carousel/src/image-carousel.tsx
- packages/image-carousel/src/video-content.tsx
- packages/poi-detail/src/image-carousel/carousel.tsx
@egjs/react-flicker 4 업데이트
- css import를 추가합니다.
- `isPlaying()`이 없어져서 제거합니다.
- page label을 업데이트하기 위해 사용하던 핸들러를 onMoveEnd 대신 onChanged로 변경합니다.
> @egjs/react-flicker 4 업데이트

- packages/review/src/components/reviews-shorten.tsx
- packages/review/src/components/write-button.tsx
- packages/review/src/mocks/reviews.ts
- packages/review/src/reviews-shorten.stories.tsx
- packages/review/src/reviews.stories.tsx
- packages/review/src/services/use-reviews.ts
[review] 버그 수정
- 리뷰 좋아요, 좋아요 취소, 삭제 mutation이 성공하면 query data를 업데이트 합니다.
- 리뷰 작성 아이콘 버튼의 위치를 수정합니다.
> [review] mutation, 디자인 버그 수정

- packages/review/src/components/review-element/index.tsx
https://github.com/titicacadev/triple-frontend/pull/2731 의 v13 버전입니다.
> [TFC-97] 호텔 리뷰 개선 - 더보기 UX 개선 (v13 용)

- package-lock.json
- packages/ad-banners/package.json
- packages/ad-banners/src/horizontal-list-view.tsx
- packages/carousel/package.json
- packages/carousel/src/carousel-item.tsx
- packages/carousel/src/carousel.tsx
- packages/image-carousel/package.json
- packages/image-carousel/src/carousel.tsx
- packages/image-carousel/src/image-carousel.tsx
- packages/poi-detail/src/image-carousel/carousel.tsx
This reverts commit b35f911.
컴포넌트 사용하는 곳에서 CSS import가 어려워서 revert 합니다.
> Revert egjs flicking 업데이트

- packages/modals/src/transition-modal.tsx
TransitionModal에 community TransitionType을 추가합니다.
> TransitionModal에 community TransitionType 추가

- renovate.json
renovate swc group 추가
- @swc/core와 @swc/plugin-styled-components가 그룹되지 않는 문제를 고쳐봅니다.
> renovate swc group 추가

- packages/view-utilities/package.json
- package.json의 main 필드를 복구합니다.
https://interpark.slack.com/archives/C05EUG8UYP6/p1689149261278129?thread_ts=1689141846.526589&cid=C05EUG8UYP6
> view-utilities의 package.json main 필드를 복구합니다

- packages/react-contexts/src/middleware.ts
https://titicaca.slack.com/archives/C7XGZTMFX/p1689234116510009?thread_ts=1687848162.724689&cid=C7XGZTMFX
원래 기획된 6.6.0가 아니라 6.5.5 버전으로 배포될 예정이라 변경합니다.
> [react-contexts] ios cookie fixation 기준 버전 변경

- .github/workflows/add-label.yaml
Draft PR을 오픈할 때 라벨 자동 등록 GHA 워크플로우가 트리거되도록 수정합니다.
> Draft PR을 오픈할 때 라벨 자동 등록 GHA workflow가 실행되도록 수정합니다.

- packages/react-contexts/package.json
react-contexts의 middleware export 경로를 복구합니다. (..😅)
> react-contexts의 middleware export 경로를 복구합니다.

- packages/chat/src/utils/image.ts
- 지라: https://titicaca.atlassian.net/browse/TNA-5621
- chat image url 생성 시 cloudinaryBucket을 우선적으로 사용하도록 변경합니다.
- cloudinaryBucket과 Chat component에 넘긴 cloudinaryName이 달라서 엑박이 발생해(dev) 메시지 데이터 기반으로 생성하도록 변경합니다.
> [chat] chat image url 생성 시 cloudinaryBucket을 우선적으로 사용하도록 변경

- packages/modals/src/modal/modal.stories.tsx
- packages/modals/src/modal/modal.tsx
웹 일정판 PC view 에서 사용하는 모달이 viewport 에 따라 반응형 처리가 필요합니다.
이를 위해 panel 너비값을 고정(285px) 이 아닌 내부 컨테이너의 너비에 맞게 조절할 수 있는 옵션을 추가합니다.
> (modal) modal flexible 옵션을 추가합니다.

- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- package.json
workflow 컨픽 정리
- HUSKY=0 환경변수 사용
- wait-for-ci 업데이트
- read only npm token을 workflow 전역 환경변수로 설정
- 중복 checkout 제거
> workflow 컨픽 정리

- .storybook/i18n.js
- .storybook/main.js
- .storybook/preview.js
chore: remove webpack options
pnpm 마이그레이션 브랜치에 포함되어 있지만 pnpm과 관련이 크게 없는 변경을 분리합니다.
- storybook build 스피드 개선
- zh -> zh-TW
> storybook build 스피드 개선

- packages/slider/src/range-slider.stories.tsx
- packages/slider/src/single-slider.stories.tsx
- packages/slider/src/slider-base.tsx
- Slider 패키지에 비활성화 기능을 추가합니다.
- [Slack](https://interpark.slack.com/archives/C05FJFC4HGS/p1690417858169729)
- [Figma](https://www.figma.com/file/4Hh60VybNKdREmC1fhhV3S/%E1%84%87%E1%85%B5%E1%84%8C%E1%85%B3?type=design&node-id=4899-111371&mode=design&t=ytWQhFvhnHSZZk7b-0)
- `<SliderBase />`에 `disabled` prop을 추가하였습니다.
- `diabled`가 `true` 일 경우 Slider handler를 제거하고 Rail의 투명도를 변경합니다.
> [slider] SliderBase disabled 상태 추가

- .github/workflows/tag-with-comment.yaml
- .github/workflows/update-changelog.yaml
https://interpark.slack.com/archives/C05EUG8UYP6/p1693287960496669?thread_ts=1692845892.671169&cid=C05EUG8UYP6
pnpm setup 추가
> pnpm setup 추가

- renovate.json
renovate self 업데이트, firebase 업데이트 disable
https://github.com/titicacadev/triple-frontend/pull/2869 이런 pr이 생성되지 않도록 합니다.
firebase 업데이트를 끕니다.
> renovate self 업데이트, firebase 업데이트 disable

- .github/workflows/update-changelog.yaml
- scripts/changelog.js
> update-changelog에 node native fetch 사용

- .github/workflows/update-changelog.yaml
> update changelog에서 prettier cli에 --no-config 옵션 추가

- .github/workflows/cd.yaml
어떤 브랜치에서 체크하는지 확인하지 않고, 배포합니다.
메인 브랜치 배포시, 배포가 안되는 이슈를 수정합니다.
> 메인 브랜치 배포 시, 배포가 안되는 이슈를 수정합니다.

- packages/chat/src/types/index.ts
- packages/chat/src/utils/constants.ts
RoomInterface에 roomType을 추가합니다.
> [Chat] RoomInterface에 roomType을 추가합니다.

- packages/web-storage/src/boundary.tsx
web storage error boundary 컴포넌트 타입을 수정합니다.
> web storage error boundary 컴포넌트 타입 수정

- packages/chat/src/bubbles/rich.tsx
- packages/chat/src/bubbles/text.ts
- packages/chat/src/chat-bubble/blinded.tsx
- packages/chat/src/chat-bubble/bubble-payload.tsx
- packages/chat/src/chat-bubble/chat-bubble-ui.tsx
- packages/chat/src/chat-bubble/chat-bubble.tsx
- packages/chat/src/chat/chat.tsx
- packages/chat/src/types/ui.ts
Text Bubble에 들어가는 링크의 디자인을 수정합니다. (색상 및 밑줄)
- color가 아닌 style(밑줄)이 추가되었기 때문에 BubbleColor props 변수명을 BubbleStyle로 수정합니다.
> [Chat] 채팅 bubble의 link 스타일을 수정합니다.

- packages/chat/src/chat-bubble/chat-bubble.tsx
타인 메시지가 본인의 메시지처럼 보이는 현상을 해결하기 위해 others -> me 변경합니다.
> [Chat] received, sent 구분 기준 변경

- packages/action-sheet/src/action-sheet-item.tsx
- tna 문의하기 액션시트에 아이콘 타입이 추가되어 없는 아이콘을 추가합니다. 
- 관련 지라: https://inpk.atlassian.net/browse/TPB-2045
> [action-sheet] action sheet item에 아이콘 추가

- packages/chat/src/chat/chat-scroll-container.tsx
- packages/chat/src/chat/chat.tsx
- packages/chat/src/chat/constants.ts
- packages/chat/src/chat/index.ts
- packages/chat/src/chat/scroll-context.tsx
- packages/chat/src/chat/use-chat-message.ts
[Chat refactor] 스크롤을 위한 context와 container를 작성합니다.
- 관련 PR: https://github.com/titicacadev/triple-chat-web/pull/274
> [Chat refactor] 스크롤을 위한 context와 container를 작성합니다.

- packages/view-utilities/src/routelist/routelist.ts
로그인 없이 이동할 수 있는 주소 목록에 웹일정판 url path를 추가합니다.
> [view-utilities] 로그인 없이 이동할 수 있는 페이지 주소 목록에 웹일정판 path 추가

- packages/triple-web/src/components/login-cta-modal.tsx
- packages/triple-web/src/components/transition-modal.tsx
- packages/triple-web/src/constants/index.ts
- packages/triple-web/src/constants/modal.ts
- packages/triple-web/src/hooks/modal/use-login-cta-modal.ts
- packages/triple-web/src/hooks/modal/use-transition-modal.ts
- packages/triple-web/src/index.ts
hash router를 사용해서 modal을 제어
- modal hash constants를 분리
- hash router를 사용해서 modal을 제어
- useTransition.show가 transitionType 파라미터를 받도록 수정
> [v14] hash router를 사용해서 modal을 제어

- packages/tds-widget/src/poi-detail/image-carousel.stories.tsx
- packages/tds-widget/src/poi-detail/image-carousel/index.tsx
#3012 에서 imagesProvider의 위치와 명칭이 바뀌었습니다. 
이를 반영합니다.
- `ImagesProvider` -> `ImageCarouselProvider`
- import path 변경
> [v14] images-context 마이그레이션

- packages/resource-list-element/src/extended-resource-list-element.tsx
- ExtendedResourceListElement badge 패딩 및 사이즈를 수정합니다.
> ExtendedResourceListElement badge 디자인 수정

- packages/react-contexts/src/event-tracking-context/event-tracking-context.tsx
틱톡 픽셀의 누락된 track 메소드를 추가합니다... (😫)
> [react-contexts] 틱톡 픽셀의 누락된 track 메소드를 추가합니다.

- packages/standard-action-handler/src/converse.tsx
- packages/tds-ui/package.json
- pnpm-lock.yaml
`standard-action-handler` 패키지 마이그레이션
- `@titicaca/tds-ui` 패키지 설치
- `Modal component import path` 변경
> [v14] standard-action-handler 마이그레이션

- packages/tds-ui/src/components/popup/popup.stories.tsx
- packages/tds-ui/src/components/popup/popup.test.tsx
- packages/tds-ui/src/components/popup/popup.tsx
> [v14 ] Popup export 문법을 수정합니다.

- packages/tds-ui/src/components/slider/handle.tsx
- packages/tds-ui/src/components/slider/range-slider.tsx
- packages/tds-ui/src/components/slider/single-slider.tsx
- packages/tds-ui/src/components/slider/slider-base.tsx
- packages/tds-ui/src/components/slider/track.tsx
- pnpm-lock.yaml
tds-ui 타입 에러 수정
- slider 타입 에러 수정
- update lockfile (input-mask-input 타입 에러 수정)
> [v14] tds-ui 타입 에러 수정

- packages/meta-tags/src/types/schema.ts
> [meta-tags] 리뷰 스니펫에 inLanguage 항목을 추가합니다.

- packages/directions-finder/src/direction-buttons.tsx
- packages/directions-finder/src/directions-finder.stories.tsx
- packages/i18n/src/assets/en/common-web.ts
- packages/i18n/src/assets/ja/common-web.ts
- packages/i18n/src/assets/ko/common-web.ts
- packages/i18n/src/assets/zh-TW/common-web.ts
- [directions-finder] grab 호출 버튼을 추가합니다. ([관련 위키](https://inpk.atlassian.net/wiki/spaces/SPC/pages/462784030/Grab))
> [directions-finder] grab 호출 버튼을 추가합니다.

- packages/tds-widget/package.json
- packages/tds-widget/src/poi-list-elements/get-type-names.ts
- packages/triple-document/package.json
- packages/triple-document/src/elements/coupon/index.tsx
- packages/triple-document/src/elements/shared/document-carousel.tsx
- packages/triple-web/src/event-tracking/types.ts
- pnpm-lock.yaml
> [v14] 빌드 에러 수정

- packages/tds-widget/.eslintignore
- packages/tds-widget/.prettierignore
- packages/tds-widget/src/.stylelintignore
- packages/tds-widget/src/nearby-pois/poi-entry.tsx
- packages/tds-widget/src/scrap-button/scrap-button-mask.test.tsx
> [v14] 린트 수정

- packages/meta-tags/src/types/schema.ts
reviewRating에 bestRating, worstRating을 추가합니다.
> [meta-tags] reviewRating에 bestRating, worstRating을 추가합니다.

- packages/chat/package.json
- pnpm-lock.yaml
[관련 스레드](https://interpark.slack.com/archives/C05EUG8UYP6/p1702542333059239)
`chat`에서는 `react-triple-client-interfaces`를 사용하고 있습니다. 
`react-triple-client-interfaces`의 경우, context provider를 제공합니다. `chat`을 사용하는 레포에서 `react-triple-client-interfaces`를 사용하는 다른 패키지(ex. router)를 함께 사용할 때 해당 레포에서 `react-triple-client-interfaces`를 명시적으로 `package.json`의 `dependencies`에 추가하지 않으면 각 패키지 별로 context가 생성되어 오류가 발생할 수 있습니다.
chat 패키지 사용부에서 dependencies에 `react-triple-client-interfaces`를 추가하여 사용하는 것을 권장하기 위해 `dependencies`에서 `peerDependencies`와 `devDependencies`로 변경합니다.
> [Chat] react-triple-client-interfaces의 Dependencies 수정

- packages/tds-widget/package.json
- packages/tds-widget/src/review/components/infinite-list/services.ts
- packages/tds-widget/src/review/components/shorten-list/services.ts
- packages/tds-widget/src/review/review-element.stories.tsx
- packages/tds-widget/src/review/reviews-shorten.stories.tsx
- packages/tds-widget/src/review/reviews.stories.tsx
- packages/tds-widget/src/review/services/use-reviews.ts
- pnpm-lock.yaml
react-query 5 업그레이드
react-query 5 업그레이드
- react-query -> @tanstack/react-query
- 변경된 인터페이스를 적용합니다.
> [v14] react-query 5 업그레이드

- packages/tds-widget/src/public-header/public-header-deeplink.tsx
- packages/triple-web/src/event-tracking/use-track-event-with-metadata.ts
- packages/triple-web/src/event-tracking/utils/track-event.ts
- trackEvent에 tiktokPixel 항목을 추가합니다.
- 기존 pixel은 metaPixel로 이름을 변경합니다. (window.fbq는 동일하군요!)
- window 타입 선언을 임시로 작성하고 주석을 추가했습니다.
> [v14] trackEvent에 틱톡 픽셀 항목을 추가합니다.

- packages/chat/src/messages.tsx
메세지에 unreadCount를 계산하기 위한 calculateUnreadCount prop을 추가합니다.
> [chat refactor] 메세지에 unreadCount를 계산하기 위한 prop을 추가합니다.

- packages/poi-detail/src/detail-header/business-hours-note.tsx
DetailHeader의 영업준비중, 휴무일 섹션의 아이콘을 정렬합니다.
|as-is|to-be|
|-----|------|
|<img width="320" alt="스크린샷 2024-02-01 오후 2 21 30" src="https://github.com/titicacadev/triple-frontend/assets/37494848/3a12f9c6-7890-4f43-b494-168160d8f4d8">|<img width="296" alt="스크린샷 2024-02-01 오후 2 21 17" src="https://github.com/titicacadev/triple-frontend/assets/37494848/814106b4-4c98-4cf5-9f0b-5f9dfe47db29">|
> [poi-detail] DetailHeader의 아이콘을 정렬합니다.

- packages/chat/src/bubble-container/bubble-container.tsx
- packages/chat/src/bubble-container/bubble-info.tsx
- packages/chat/src/icons/reply-meesage-icon.tsx
- packages/chat/src/messages/index.tsx
bubbleContainer의 info 영역에 메세지 답장하기 아이콘을 추가합니다.
> [chat] 메세지에 답장하기 아이콘을 추가합니다.

- packages/chat/src/bubble-container/bubble-container.tsx
- packages/chat/src/messages/index.tsx
geochat의 메세지 기능을 추가하기 위한 IntersectionObserver와 ref를 추가합니다.
> [chat] 메세지에 IntersectionObserver와 ref를 추가합니다.

- packages/chat/src/messages/index.tsx
> [chat] 답장하기 아이콘의 렌더링 조건을 수정합니다.

- packages/react-hooks/src/use-local-storage.ts
- packages/react-hooks/src/use-session-storage.ts
- packages/triple-web/src/event-tracking/use-track-screen.ts
react-hooks
- useLocalStorage, useSessionStorage의 return type을 initialValue 유무에 따라 overloading
triple-web
- useTrackScreen은 context가 없어도 사용 가능하도록 수정
> [v14] 타입 개선과 버그 수정

- packages/chat/src/bubble-container/bubble-container.tsx
- packages/chat/src/messages/index.tsx
- messages의 openMenu와 BubbleUI의 openMenu의 타입이 달라 & 연산자로 묶이는 오류를 수정합니다.
- 기타 자잘한 디자인 수정도 추가합니다😂
> [chat] openMenu의 타입 오류를 수정합니다.

- packages/modals/src/transition-modal.tsx
TransitionModal의 타입을 추가합니다. (공유하기, 일정추가)
> TransitionModal에 타입을 추가합니다.

- packages/review/src/components/full-list-button.tsx
- packages/review/src/services/use-client-actions.tsx
리뷰 더보기 로그인 모달의 returnUrl을 리뷰 목록 페이지로 수정합니다.
- jira 이슈: https://inpk.atlassian.net/browse/WATF-78
> [reviews] 리뷰 더보기의 로그인 returnUrl을 리뷰 목록 페이지로 수정합니다.

- packages/poi-detail/src/image-carousel/carousel.tsx
- packages/poi-detail/src/image-carousel/cta-overlay.tsx
- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/media/index.tsx
웹 이미지 확대뷰 지원을 위해 이미지 캐러셀의 cta 조건을 수정합니다.
- 웹에서 사진을 클릭하면 앱 설치 모달이 아닌 로그인 팝업이 뜨도록 수정합니다.
- 웹에서도 로그인 시 슬라이드를 통해 전체 이미지를 확인할 수 있도록 합니다.
> [poi-detail, review] 이미지 캐러셀의 cta 조건을 수정합니다.

- packages/image-viewer/package.json
- packages/image-viewer/src/detail-viewer/index.tsx
- packages/image-viewer/src/detail-viewer/video.tsx
- packages/image-viewer/src/image-viewer.stories.tsx
- pnpm-lock.yaml
동영상 확대뷰를 작성합니다.
https://inpk.atlassian.net/browse/WATF-69
- 비디오 관련 코드는 image-carousel의 [VideoContent](https://github.com/titicacadev/triple-frontend/blob/main/packages/image-carousel/src/video-content.tsx)를 참고해서 작성했습니다.
> [image-viewer] 동영상 확대뷰를 작성합니다.

- packages/image-viewer/package.json
- packages/image-viewer/src/detail-viewer/index.tsx
- packages/image-viewer/src/detail-viewer/video.tsx
- packages/image-viewer/src/image-viewer.stories.tsx
- packages/image-viewer/src/image-viewer.tsx
- packages/review/package.json
- packages/review/src/components/review-element/media/index.tsx
- pnpm-lock.yaml
리뷰 컴포넌트에 이미지 뷰어를 적용합니다.
https://inpk.atlassian.net/browse/WATF-85
- 이미지 뷰어에 있는 ImagesContext를 제거하고 props로 넘겨주도록 수정합니다.
- 리뷰 컴포넌트에 이미지 뷰어를 적용합니다.
- 비디오 뷰어의 intersection observer를 제거하고 visible 여부로 재생을 중단하도록 수정했습니다. (브랜치 분리 실패ㅋㅋ큐ㅠㅠ)
> [review, image-viewer] 이미지 뷰어에서 ImagesContext를 제거하고 리뷰 컴포넌트에 이미지 뷰어를 적용합니다.

- packages/image-viewer/src/detail-viewer/image.tsx
> [image-viewer] 더블 클릭으로 인한 이미지 확대를 disable합니다.

- packages/poi-detail/src/recommended-articles.stories.tsx
- packages/poi-detail/src/recommended-articles/recommended-articles.tsx
`이지역꿀정보`의 타이틀을 좌측 정렬로 수정합니다. width가 767 이하인 경우 캐러셀 하단에 생기는 padding을 제거합니다. [관련 스레드](https://interpark.slack.com/archives/C06FLC344Q0/p1711687108949999)
mock API를 사용해 어떤 환경에서든 스토리북이 정상적으로 보여질 수 있도록 합니다.
|AS-IS|TO-BE|
|--|--|
|![스크린샷 2024-04-01 오후 3 02 01](https://github.com/titicacadev/triple-frontend/assets/43779313/953ee149-e26b-41b5-b919-57185b0f4d19)|![스크린샷 2024-04-01 오후 3 02 25](https://github.com/titicacadev/triple-frontend/assets/43779313/29163acf-9fc6-43de-9481-170e1b4dd9d8)|
> [poi-detail] 이지역꿀정보 영역 디자인을 수정합니다.

- packages/image-viewer/src/detail-viewer/image.tsx
- packages/image-viewer/src/detail-viewer/index.tsx
- packages/image-viewer/src/detail-viewer/video.tsx
- packages/image-viewer/src/image-viewer.tsx
- packages/poi-detail/src/image-carousel/carousel.tsx
- packages/poi-detail/src/image-carousel/cta-overlay.tsx
- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/media/index.tsx
이미지 확대뷰 fa 이벤트를 추가합니다.
https://inpk.atlassian.net/browse/WATF-87
- 브랜치 분리 실패로 ios에서 비디오 썸네일이 나오지 않는 문제도 포함되었습니다😂
> [image-viewer, poi-detail, review] 이미지 확대뷰 fa 이벤트를 추가합니다.

- packages/image-viewer/src/image-viewer.tsx
- packages/review/src/components/review-element/media/index.tsx
이미지 확대뷰의 사진이 네브바 위로 올라가는 현상을 수정합니다.
> [reviews] 이미지 확대뷰 QA

- packages/meta-tags/src/apple-smart-banner-meta.tsx
- packages/meta-tags/src/article-script.tsx
- packages/meta-tags/src/breadcrumb-list-script.tsx
- packages/meta-tags/src/common-meta.tsx
- packages/meta-tags/src/essential-content-meta.tsx
- packages/meta-tags/src/facebook-app-link-meta.tsx
- packages/meta-tags/src/facebook-open-graph-meta.tsx
- packages/meta-tags/src/local-business-script.tsx
- packages/meta-tags/src/product-script.tsx
- packages/meta-tags/src/review-script.tsx
- packages/meta-tags/src/theme-color-meta.tsx
https://github.com/titicacadev/triple-frontend/pull/2826 에서 제거된 코드 관련 설명을 제거합니다
> [meta-tags] 불필요 주석 제거

- packages/poi-detail/src/recommended-articles/recommended-articles.tsx
`이지역꿀정보` 영역의 FA 이벤트 로깅을 추가합니다.
[지라 티켓](https://inpk.atlassian.net/browse/WATF-86)
> [poi-detail] 이지역꿀정보의 fa를 추가합니다.

- package.json
- packages/image-viewer/README.md
- packages/image-viewer/package.json
- packages/image-viewer/src/detail-viewer/detail-viewer.stories.tsx
- packages/image-viewer/src/detail-viewer/image.tsx
- packages/image-viewer/src/detail-viewer/index.tsx
- packages/image-viewer/src/detail-viewer/video.tsx
- packages/image-viewer/src/image-viewer.stories.tsx
- packages/image-viewer/src/image-viewer.tsx
- packages/image-viewer/src/index.ts
- packages/image-viewer/src/styled.d.ts
- packages/image-viewer/tsconfig.build.json
- packages/image-viewer/tsconfig.json
- packages/poi-detail/src/image-carousel/carousel.tsx
- packages/poi-detail/src/image-carousel/cta-overlay.tsx
- packages/review/package.json
- packages/review/src/components/review-element/index.tsx
- packages/review/src/components/review-element/media/index.tsx
- pnpm-lock.yaml
웹에서도 이미지를 확대해서 볼 수 있는 이미지 뷰어 패키지를 생성합니다. 
PC에서는 슬라이드/좌우 버튼으로 이전/다음 이미지로 이동할 수 있고, 모바일에서는 슬라이드로 이동할 수 있습니다. 
모바일에서는 제스처 확대가 가능합니다. 
현재는 확대뷰만 제공되며 추후 격자뷰가 추가될 수 있습니다.
이미지 캐러셀, 리뷰에서 이미지를 클릭 시 확대뷰를 볼 수 있습니다.
[지라 티켓](https://inpk.atlassian.net/browse/WATF-14)
포함 PR
#3166 
#3170
#3171 
#3172 
#3173 
#3175 
#3176 
#3179 
https://github.com/titicacadev/triple-frontend/assets/43779313/920a9c5c-4a3f-4bd1-b755-6006b16384a9
https://github.com/titicacadev/triple-frontend/assets/43779313/d05cea08-1613-44d8-a786-99477e8fb068
> [image-viewer] 확대뷰/격자뷰를 위한 이미지 뷰어 패키지를 생성합니다.

- packages/modals/src/transition-modal.tsx
POI 기본 정보를 클릭했을 때 열리는 앱설치유도 모달을 구분하기 위해 type을 추가합니다.
- 앱설치유도 모달에 POI 기본정보 type을 추가합니다.
> [modals] 앱설치유도 모달에 POI 기본정보 type을 추가합니다.

- packages/public-header/src/public-header.tsx
> [public-header] 헤더 로고에 onClick props를 추가합니다.

- packages/type-definitions/src/translated-property.ts
`TranslatedProperty` 타입을 최신화합니다. 추후 `primary` 값이 모두 업데이트될 예정이지만, 이 값이 `ko, en, ja, zh, local`을 기반으로 하기 때문에 각 값들 또한 존재합니다. 최신 버전에 추가된 `ja`, `zh` 속성을 추가합니다. 
[관련 스레드](https://interpark.slack.com/archives/C05ES3E2VL2/p1715576739842059)
> TranslatedProperty 타입을 최신화합니다.

- packages/triple-document/src/elements/index.ts
- packages/triple-document/src/elements/sticky-tabs.tsx
- packages/triple-document/src/triple-document.stories.tsx
5월 프로모션 대응으로  triple-document 패키지에 신규 Tab element추가
관련 쓰레드: [interpark.slack.com/archives/C06SHL8FC5V/p1715217465749669](https://interpark.slack.com/archives/C06SHL8FC5V/p1715217465749669)
https://github.com/titicacadev/triple-frontend/assets/1519159/5af6c3a6-b520-4758-8a1f-7db284c92b24
> [triple-document] StickyTabs element 추가

- packages/view-utilities/src/routelist/routelist.ts
> [view-utilities] 맞춤일정 페이지를 routelist에 추가합니다.

- packages/footer/src/company-info.tsx
`footer` 내 인터파크트리플 주소를 변경합니다.
6/5 이전 배포 예정입니다.
- 관련 문서 : https://inpk.atlassian.net/wiki/spaces/SPC/pages/675217411/2024.06.05
> [footer] 인터파크 사업장 주소 변경

- CHANGELOG.md
- packages/tds-widget/src/review/components/full-list-button.tsx
- packages/tds-widget/src/review/services/use-client-actions.tsx
> v13.26.1 변경사항을 main에 머지합니다.

- packages/action-sheet/src/action-sheet-overlay.tsx
- packages/action-sheet/src/action-sheet.tsx
액션 시트에서 `lockScroll`의 여부를 prop으로 제공합니다. `lockScroll`이 `false`인 경우에는 딤드가 사라지고 액션 시트 뒤의 엘리먼트가 동작합니다. 
- `lockScroll` prop 추가
> [action-sheet] 액션 시트에서 lockScroll을 해제할 수 있도록 옵션 제공

- packages/react-contexts/src/session-context/user.ts
[react-contexts] user의 마일리지 뱃지 이미지 타입을 수정합니다.
- api 상으로는 image_url 스네이크 케이스로 내려옵니다. 
- 타입을 스네이크 케이스로 바꾸는 게 좋을지, 아니면 setUser 과정에서 카멜케이스로 바꾸는게 좋을지 의견 부탁드립니다!
> [react-contexts] user의 마일리지 뱃지 이미지 타입을 수정합니다.

- packages/action-sheet/src/action-sheet.tsx
액션 시트 뒤의 컨텐츠들에서 이벤트가 발생할 수 있도록 `pointerSelect` css를 복구합니다.
> [action-sheet] pointer select revert

- CHANGELOG.md
- packages/tds-ui/src/components/action-sheet/action-sheet-overlay.tsx
- packages/tds-ui/src/components/action-sheet/action-sheet.tsx
- packages/triple-web/src/session/types.tsx
main 브랜치에 13.26.2, 13.26.3 변경 사항을 반영합니다.
> v13 변경사항 리베이스

- packages/footer/src/triple-korea-link.tsx
[footer] 푸터 KINT 진입점에 FA 로깅을 추가합니다.
> [footer] 푸터 KINT 진입점에 FA 로깅을 추가합니다.

- README.md
SEO 작업의 일환으로 리드미에 트리플, 트리플 코리아 백링크를 추가합니다
> 리드미에 관련 서비스 링크 추가

- packages/footer/src/company-info.tsx
사옥 이전에 따라 푸터 주소를 변경합니다.
- 관련 문서 : https://inpk.atlassian.net/wiki/spaces/SPC/pages/895845132/2024.10.10
- 관련 쓰레드 : https://interpark.slack.com/archives/C05EUG8UYP6/p1728347645653909
> [KLZT-622] 푸터 주소 변경

- packages/tds-widget/src/flicking-carousel/flicking-carousel.tsx
- packages/tds-widget/src/poi-detail/recommended-articles/recommended-articles.tsx
- POI > 추천가이드에서 `FlickingCarousel`을 사용하도록 합니다(`FlickingCarousel` 내부에서 `Carousel` or `FlickingCarousel` 사용여부가 분기됨).
- 스크롤 숨김 설정이 작동하도록 수정합니다.
> [v14] 캐러셀 관련 이슈 수정

- packages/tds-widget/src/poi-detail/use-fetch-images.tsx
node querystring 대신 qs 사용
node querystring 대신 qs 사용
> node querystring 대신 qs 사용

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
Release v14.0.2
- node querystring 대신 qs 사용 [#3423](https://github.com/titicacadev/triple-frontend/pull/3423)
> Release v14.0.2

- packages/tds-widget/src/user-verification/index.ts
user-verification service export 추가
[tds-widget] 
user-verification service export 추가
> user-verification service export 추가

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
Release v14.0.3
- 13.31.0 - 13.34.0 변경사항을 14에 반영 [#3460](https://github.com/titicacadev/triple-frontend/pull/3460)
- 13.31.0 - 13.34.0 변경사항을 14에 반영 [#3460](https://github.com/titicacadev/triple-frontend/pull/3460)
- user-verification service export 추가 [#3442](https://github.com/titicacadev/triple-frontend/pull/3442)
- 13.31.0 - 13.34.0 변경사항을 14에 반영 [#3460](https://github.com/titicacadev/triple-frontend/pull/3460)
- useClientAppCallback의 fn, appInstallCtaModalOptions 파라미터 순서 변경 [#3440](https://github.com/titicacadev/triple-frontend/pull/3440)
- 13.31.0 - 13.34.0 변경사항을 14에 반영 [#3460](https://github.com/titicacadev/triple-frontend/pull/3460)
> Release v14.0.3

- packages/tds-ui/src/components/segment/segment.tsx
Card radius prop 이름 변경
https://interpark.slack.com/archives/C05EUG8UYP6/p1730710012708069
borderRadius -> radius로 수정합니다
> Card radius prop 이름 변경

- packages/react-triple-client-interfaces/src/triple-client-metadata-context.tsx
- packages/react-triple-client-interfaces/src/triple-client-user-agent.ts
- packages/react-triple-client-interfaces/src/types.ts
- 맥용 앱을 구분하기 위해 client meta data에 isMacApp 플래그를 추가합니다.
> [MAC용 트리플 앱 개발 지원] client meta data에 isMacApp 플래그 추가

- CHANGELOG.md
- packages/tds-widget/src/poi-detail/images-provider.tsx
- packages/tds-widget/src/poi-detail/use-fetch-images.tsx
- packages/triple-web-nextjs-pages/src/providers/client-app.ts
- packages/triple-web-nextjs/src/providers/client-app.ts
- packages/triple-web-utils/src/regex.ts
- packages/triple-web/src/client-app/types.ts
13.35.0 - 13.36.0 변경사항을 14에 반영
> 13.35.0 - 13.36.0 변경사항을 14에 반영

- packages/router/src/common/router-guarded-link.tsx
router 패키지의 LocalLink, ExternalLink 컴포넌트가 불필요한 인라인 스타일을 가지지 않도록 수정합니다.
- Link 컴포넌트에서 불필요한 inline style 제거
> Link 컴포넌트에서 불필요한 inline style 제거

- packages/router/src/navigate/use-navigate.ts
- packages/view-utilities/src/routelist/routelist.ts
[view-utilities] routelist에 라운지홈을 추가합니다.
[router] useNavigate에서 showAppInstallCtaModal을 호출할 때 deeplink로 이동할 수 있도록 수정합니다.
> [view-utilities, router] routelist에 라운지홈을 추가합니다. useNavigate에서 deeplink 이동 로직을 추가합니다.

- packages/triple-web/src/modal/components/login-cta-modal.tsx
https://nol-universe.slack.com/archives/C05EUG8UYP6/p1732856084450209
[triple-web]
- LoginCtaModal 기본 return url에서 hash 제거
> LoginCtaModal 기본 return url에서 hash 제거

- packages/tds-widget/src/scrap/use-scrap.ts
[tds-widget] beforeScrapedChange시 파람에 eventParam을 넘기도록 수정합니다.
- 이벤트 로깅을 위해 scrape 시 target의 eventParams도 파람으로 넘기도록 수정합니다.
> [tds-widget] beforeScrapedChange시 파람에 eventParam을 넘기도록 수정합니다.

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [tds-widget] beforeScrapedChange시 파람에 eventParam을 넘기도록 수정합니다. [#3493](https://github.com/titicacadev/triple-frontend/pull/3493)
- [triple-web] firebaseAnalytics 인스턴스를 가져오지 못하는 이슈를 해결합니다. [#3492](https://github.com/titicacadev/triple-frontend/pull/3492)
- [triple-web] 모달을 띄울 때 trackScreen이 호출되는 문제를 해결합니다. [#3496](https://github.com/titicacadev/triple-frontend/pull/3496)
- [triple-web] 로그인 모달 버튼 함수 수정 [#3497](https://github.com/titicacadev/triple-frontend/pull/3497)
> 🚀 release v14.0.6

- packages/chat/package.json
- packages/chat/src/bubble-container/bubble-container.tsx
- packages/chat/src/bubble/altered.tsx
- packages/chat/src/chat/chat-scroll-container.tsx
- packages/chat/src/chat/scroll-context.tsx
- packages/chat/src/messages/index.tsx
- pnpm-lock.yaml
- intersectionObaserver를 react-intersection-observer 패키지로 교체합니다.
- 유저 프로필 클릭 핸들러를 추가합니다.
- 기타 자잘한 스타일 수정을 추가했습니다.
> [chat] intersection observer 교체 외 스타일 수정

- packages/footer/src/award-footer.tsx
- packages/footer/src/company-info.tsx
- packages/footer/src/default-footer.tsx
[footer] 합병으로 인한 푸터의 회사명, 대표명을 변경합니다. ([관련 스레드](https://nol-universe.slack.com/archives/C05GCN0AYSZ/p1734572677692729))
> [footer] 푸터의 회사명, 대표명을 변경합니다.

- packages/review/src/components/review-placeholder-with-rating.tsx
- 리뷰 플레이스홀더 마진 값을 수정합니다. ([관련스레드](https://nol-universe.slack.com/archives/C06SJ6275L1/p1734591717578319?thread_ts=1733878953.296629&cid=C06SJ6275L1))
- PlaceholderContainer 마진 탑 수정
AS-IS
TO-BE
> [Reivew] 리뷰 플레이스홀더 마진 값을 수정합니다.

- CHANGELOG.md
- packages/tds-widget/src/footer/award-footer.tsx
- packages/tds-widget/src/footer/company-info.tsx
- packages/tds-widget/src/footer/default-footer.tsx
- packages/tds-widget/src/media/media.tsx
- packages/tds-widget/src/review/components/review-placeholder-with-rating.tsx
- packages/type-definitions/src/image.ts
v13.37.0, v13.38.0 변경사항을 적용합니다.
- https://github.com/titicacadev/triple-frontend/pull/3506
- https://github.com/titicacadev/triple-frontend/pull/3511
> v13.37.0, v13.38.0 변경사항을 적용합니다.

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [meta-tags] 앱라우터용 메타태그 및 QaPageScript, DiscussionForumPostingScript를 추가합니다. [#3500](https://github.com/titicacadev/triple-frontend/pull/3500)
- [middleware] 세션 쿠키 리프레시 로직을 수정합니다.  [#3498](https://github.com/titicacadev/triple-frontend/pull/3498)
- [triple-web] web track event는 클라이언트 웹뷰가 아닐 때만 로깅하도록 수정합니다.  [#3507](https://github.com/titicacadev/triple-frontend/pull/3507)
- v13.37.0, v13.38.0 변경사항을 적용합니다. [#3512](https://github.com/titicacadev/triple-frontend/pull/3512)
- v13.37.0, v13.38.0 변경사항을 적용합니다. [#3512](https://github.com/titicacadev/triple-frontend/pull/3512)
> 🚀 Release v14.0.7

- packages/footer/src/award-footer.tsx
- packages/footer/src/default-footer.tsx
> [footer] 푸터의 맞춤법을 수정합니다.

- CHANGELOG.md
- packages/tds-widget/src/footer/award-footer.tsx
- packages/tds-widget/src/footer/default-footer.tsx
v13.38.1 변경사항을 적용합니다.
- https://github.com/titicacadev/triple-frontend/pull/3516
> v13.38.1 변경사항을 적용합니다.

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
v13.38.1 변경사항을 적용합니다. [#3521](https://github.com/titicacadev/triple-frontend/pull/3521)
> 🚀 Release v14.0.8

- packages/tds-ui/src/components/index.ts
- packages/tds-widget/src/index.ts
- packages/triple-web-nextjs-pages/src/triple-web.tsx
- packages/triple-web-nextjs/src/triple-web.tsx
- packages/triple-web/src/modal/use-app-install-cta-modal.ts
- packages/triple-web/src/modal/use-login-cta-modal.ts
- tds-ui, tds-widget, modal hooks에 `'use client'` 추가
- triple-web-nextjs TripleWeb에 불필요한 async 제거
- TripleWeb에 displayName 추가
> App router에서 use client 문제 수정

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [triple-web] 웹뷰에서는 nativeTrackScreen만 실행하도록 수정합니다.  [#3536](https://github.com/titicacadev/triple-frontend/pull/3536)
> 🚀 Release v14.0.10

- packages/footer/src/company-info.tsx
회사 문의메일 정보 변경에 따라 푸터 내 문의메일을 변경합니다.
- [관련 쓰레드](https://nol-universe.slack.com/archives/C05ERUV2603/p1736927375819889?thread_ts=1736841784.072699&cid=C05ERUV2603)
> [footer] 푸터 내 문의메일 정보 변경

- packages/triple-web/src/modal/use-app-install-cta-modal.ts
- packages/triple-web/src/modal/use-login-cta-modal.ts
[triple-web] 앱설치유도 모달 및 로그인 모달의 `showOptions`를 수정합니다.
- useModal 외에 `AppInstallCtaModalProvider`, `LoginCtaModalProvider`에서 InitialProps로 넣는 `showOptions`들도 반영할 수 있도록 수정합니다.
> [triple-web] 앱설치유도 모달 및 로그인 모달의 showOptions를 수정합니다.

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- v13.40.0 변경사항을 적용합니다. [#3545](https://github.com/titicacadev/triple-frontend/pull/3545)
- [triple-web] 앱설치유도 모달 및 로그인 모달의 showOptions를 수정합니다. [#3540](https://github.com/titicacadev/triple-frontend/pull/3540)
- v13.40.1 변경사항을 적용합니다. [#3547](https://github.com/titicacadev/triple-frontend/pull/3547)
> 🚀 Release v14.0.11

- packages/chat/src/utils/a-tag-navigator.ts
aTagNavigator가 외부 브라우저에서 열리도록 수정합니다.
> [chat] aTagNavigator가 외부 브라우저에서 열리도록 수정합니다.

- packages/chat/src/input-area/index.tsx
- [TPB-2794]
- 트리플 채팅에서 accept 처리가 되어 있지 않아 영상이 보내지는 이슈를 수정합니다.
- 지라에 첨부했습니다.
[TPB-2794]: https://yanoljagroup.atlassian.net/browse/TPB-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (chat)fix: file input에 사진만 업로드 가능하도록 accept 추가

- packages/react-contexts/src/middlewares/set-web-device-id.ts
setWebDeviceId 미들웨어에 applySetCookie를 적용합니다.
아래 PR을 참고했습니다.
- https://github.com/titicacadev/triple-frontend/pull/3592
> [react-contexts] setWebDeviceId 미들웨어에 applySetCookie를 적용합니다.

- packages/view-utilities/src/routelist/routelist.ts
[KLZT-885] routelist에 static-pages, community, game 경로를 추가합니다.
- 아티클에서 개인정보 이용방침 링크 클릭 시 앱 모달이 뜨는 것을 방지합니다.
- community와 game은 겸사겸사 추가했습니다😄
[KLZT-885]: https://yanoljagroup.atlassian.net/browse/KLZT-885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KLZT-885] routelist에 static-pages, community, game을 추가합니다.

- packages/react-contexts/src/middlewares/index.ts
[react-contexts] 미들웨어에 chain 및 기타 미들웨어의 export를 추가합니다.
- 미들웨어를 커스텀해서 사용할 수 있도록 합니다. ([관련 스레드](https://nol-universe.slack.com/archives/C05EUG8UYP6/p1742783715893399?thread_ts=1742782882.395029&cid=C05EUG8UYP6))
> [react-contexts] 미들웨어에 chain 및 기타 미들웨어의 export를 추가합니다.

- packages/react-contexts/src/session-context/provider/index.tsx
session context 누락된 param을 추가합니다.
> [react-contexts] session context 누락된 param을 추가합니다. 

- packages/tds-widget/src/chat/expired/expired.tsx
> fix: onChatRestart 기본값 제거

- packages/tds-widget/src/chat/types/room.ts
- 초대 및 채팅방 만료 정책 타입을 추가합니다.
- https://nol-chat-api.proxy.dev.triple.zone/docs/swagger-ui/index.html#/invitation-external-controller/getInvitation
- https://nol-chat-api.proxy.dev.triple.zone/docs/swagger-ui/index.html#/room-external-controller/getRoom
> [DMTALK-88] 초대 및 채팅방 만료 정책 타입 추가

- packages/tds-widget/src/chat/bubble-container/bubble-container.tsx
- packages/tds-widget/src/chat/bubble-container/elements.tsx
- packages/tds-widget/src/chat/bubble/bubble-ui.tsx
- packages/tds-widget/src/chat/bubble/bubble.tsx
- packages/tds-widget/src/chat/bubble/full-text-message-view.tsx
- packages/tds-widget/src/chat/bubble/text.tsx
- packages/tds-widget/src/chat/bubble/type.ts
- packages/tds-widget/src/chat/messages/index.tsx
- Chat 스타일 / 컴포넌트 확장 가능하도록 수정합니다. 
1. `bubbleInfoStyle`에 `failureHandler`를 추가합니다.
2. 버블과 버블 사이, 버블과 부가정보 사이의 gap을 커스텀 할 수 있는 `spacing` 프롭을 추가합니다.
3. 버블의 radius, arrowRadius를 커스텀할 수 있는 `borderRadius`,  `arrowRadius` 를 추가합니다.
4. 버블에 프로필 사진을 노출할지 여부를 결정하는 `showProfilePhoto`를 추가합니다. @choisohyun 
5. 전체보기 정책, 전체보기 페이지를 커스텀할 수 있는 `CustomFullTextViewController`를 추가합니다. 전체보기를 노출하는 조건, 팝업 스타일 등 커스텀이 필요한 내용이 많아 관련 플로우와 UI를 사용처에 맡기게 되었는데 혹시 좋은 방법이 있을지,, 의견 부탁드립니다! 🙇‍♀️ ([적용 예시](https://github.com/titicacadev/triple-chat-web/pull/459/files#diff-c8ba05e71c91e0bce2b487347940eac8bc9b827c8a79c9da27c57f37ef6714e2))
> [DMTALK-86] Chat 스타일 / 컴포넌트 확장 가능하도록 수정

- .github/workflows/add-label.yaml
- .github/workflows/cd.yaml
- .github/workflows/ci.yaml
- .github/workflows/pr-closed.yaml
- .github/workflows/tag-with-comment.yaml
- .github/workflows/update-changelog.yaml
- 깃헙 액션 러너를 `vars.NOL_RUNNER`로 수정합니다.  ([러너 문의 스레드](https://nol-universe.slack.com/archives/C05FT7UHU7N/p1742345620984849?thread_ts=1741333193.518839&cid=C05FT7UHU7N))
- 더이상 사용하지 않는 슬랙 notify 스텝을 제거합니다.
> 깃헙 액션 러너를 수정하고 슬랙 notify 스텝을 제거합니다.

- packages/tds-widget/src/chat/preview/elements.tsx
- packages/tds-widget/src/chat/reservation-info/index.ts
- ReservationInfo > Label을 export 합니다.
- 일부 일부 Preview element에 css가 override되도록 수정합니다.
-
> [DMTALK-67] ReservationLabel export 및 일부 Preview element css override 되도록 수정

- packages/tds-widget/src/chat/chat/chat-room-messages/chat-message-context.tsx
> [DMTALK] 조건문 내 오타 수정

- packages/ab-experiments/src/triple-ab-experiment-context/context.tsx
- packages/ab-experiments/src/triple-ab-experiment-context/service.ts
- packages/fetcher/package.json
- packages/fetcher/src/factories.ts
- packages/fetcher/src/index.ts
- packages/fetcher/src/session-refresh.ts
- packages/tds-widget/src/ad-banners/api.ts
- packages/tds-widget/src/date-picker/service.ts
- packages/tds-widget/src/date-picker/use-public-holidays.ts
- packages/tds-widget/src/nearby-pois/service.ts
- packages/tds-widget/src/poi-detail/recommended-articles/api-client.ts
- packages/tds-widget/src/poi-detail/use-fetch-images.tsx
- packages/tds-widget/src/replies/hook.tsx
- packages/tds-widget/src/replies/list/reply.tsx
- packages/tds-widget/src/replies/replies-api-client.ts
- packages/tds-widget/src/review/components/shorten-list/services.ts
- packages/tds-widget/src/review/data/graphql/client.ts
- packages/tds-widget/src/review/services/use-reviews.ts
- packages/tds-widget/src/user-verification/confirmation-services.ts
- packages/triple-document/src/elements/tna/index.tsx
- packages/triple-header/src/service.ts
- packages/triple-web-nextjs-pages/src/ssr-utils/auth-guard.ts
- pnpm-lock.yaml
https://github.com/titicacadev/triple-frontend/pull/3595 내용을 TF 14에 적용합니다.
> [KLZT-882] 클라이언트 세션 갱신 로직을 추가합니다. 

- packages/tds-widget/src/chat/types/room.ts
- `ProductMetaData, BookingMetaData`를 [스웨거](https://nol-chat-api.proxy.dev.triple.zone/docs/swagger-ui/index.html?urls.primaryName=1.external#/room-external-controller/getRoom) 타입에 맞춰 수정합니다.
- 참고: https://github.com/titicacadev/tna-partners-web/pull/2256
> [DMTALK] `ProductMetaData, BookingMetaData` type 스웨거와 싱크

- packages/tds-widget/src/chat/expired/index.ts
- packages/tds-widget/src/chat/input-area/index.tsx
- packages/tds-widget/src/chat/input-area/nol-input-area-ui/index.tsx
> [DMTALK] refactor: export 네이밍 변경

- packages/react-contexts/src/session-context/provider/hooks.ts
[react-contexts] 일반 로그아웃시 reload 추가
- 누락된 코드를 추가합니다.
> [react-contexts] 일반 로그아웃시 reload 추가

- packages/fetcher/src/factories.ts
[fetcher] authFetcherize에서 refresh의 apiUriBase를 fetcher와 통일합니다.
> [fetcher] authFetcherize에서 refresh의 apiUriBase를 fetcher와 통일합니다.

- packages/footer/src/award-footer.tsx
footer의 disclaimer maxWidth를 삭제합니다.
> [footer] footer의 disclaimer maxWidth 삭제

- packages/footer/src/button-area/button.tsx
- packages/footer/src/button-area/index.tsx
[footer] 푸터 버튼에 key props를 추가합니다.
> [footer] 푸터 버튼에 key props를 추가합니다.

- packages/public-header/src/side-menu/profile.tsx
[public-header] NOL 멤버스 문구를 NOL 회원으로 변경합니다.
> [public-header] NOL 멤버스 문구를 NOL 회원으로 변경합니다.

- packages/fetcher/src/factories.ts
- packages/triple-web/package.json
- packages/triple-web/src/session/context.tsx
- pnpm-lock.yaml
- https://github.com/titicacadev/triple-frontend/pull/3655
- https://github.com/titicacadev/triple-frontend/pull/3654
> v13 변경사항을 적용합니다

- packages/tds-widget/src/chat/bubble/nol/full-text-view/elements.tsx
- packages/tds-widget/src/chat/bubble/nol/styles.ts
- 놀 버블에 잘못된 간격을 수정합니다. 🙇
- dev에는 적용시켰습니다!
> [DMTALK] 잘못된 간격 수정

- packages/tds-widget/src/scrap/services.ts
- packages/tds-widget/src/scrap/use-scrap.ts
누락된 `authGuardedFetchers`를 적용합니다. 
- scrape에 `authGuardedFetchers` 적용
> [tds-widget] scrap에 authGuard 추가

- packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts
- 누락된 디펜던시와 text sanitize된 payload 첨부 누락을 추가합니다.
> [DMTALK-158] 누락된 디펜던시 및 message sanitize 추가

- packages/tds-widget/src/chat/expired/elements.tsx
- packages/tds-widget/src/chat/reservation-info/elements.tsx
- packages/tds-widget/src/chat/reservation-info/reservation-info.stories.tsx
- expired, reservation-info 디자인 수정사항 반영합니다.
- https://travel.dev.inpk.io/chat/rooms/67ee59f22be1560013b0528c (tourweb01 계정)
> [DMTALK-156] 간격 수정 및 문구 변경으로 인한 max-width 수정

- packages/tds-widget/src/chat/reservation-info/reservation-info.tsx
https://github.com/titicacadev/triple-frontend/pull/3668 에서 클릭이벤트 실행조건 오류를 수정합니다. 🙇
expandable일 때만 setExpanded 실행됩니다.
> [DMTALK] 상품/예약정보 접기펼치기 영역 - 클릭이벤트 조건 수정

- packages/triple-web-nextjs/src/initializers/session.ts
- https://github.com/titicacadev/triple-frontend/pull/3618/files
위 PR의 변경사항을 `triple-web-nextjs` 패키지에도 적용합니다.
> [triple-web-nextjs] 웹/앱 구분 없이 세션 갱신을 시도합니다. 

- .github/workflows/tag-with-comment.yaml
- tag-with-comment 실행오류를 수정합니다. 
- https://github.com/titicacadev/triple-frontend/actions/runs/14486460830/job/40632908282#step:6:20
- gha-tools의 [fetch-github-pr](https://github.com/titicacadev/gha-tools/blob/main/lib/fetch-github-pr.js#L4)에서 `SLACK_GITHUB_REPOSITORY` 값을 사용하고 있는데 제거되어 복구합니다. 
- tag-with-comment가 pr의 코멘트 이벤트로 실행되기 때문에 main 브랜치 기준으로 실행되어 테스트는 못해보았습니다.. 🙏
> SLACK_GITHUB_REPOSITORY 누락 추가

- packages/tds-widget/src/chat/input-area/input-area.stories.tsx
- packages/tds-widget/src/chat/input-area/nol-input-area-ui/index.tsx
- packages/tds-widget/src/chat/messages/messages.stories.tsx
- packages/tds-widget/src/chat/nol-theme-provider/constants.ts
- packages/tds-widget/src/chat/reservation-info/elements.tsx
- packages/tds-widget/src/chat/reservation-info/reservation-info.stories.tsx
- packages/tds-widget/src/chat/reservation-info/reservation-info.tsx
- 디자인 QA 사항을 반영합니다.
- nol input에 nol theme을 적용합니다.
- storybook 테스트용 NOL_COLOR를 추가합니다.
> [DMTALK-176] 디자인 QA

- packages/tds-widget/src/chat/bubble/full-text-message-view.tsx
- packages/tds-widget/src/chat/bubble/text.tsx
- 전체보기 뷰 시 지오챗 스타일 오류를 수정합니다. 🧎‍♂️ 
|as-is|to-be|
|--|--|
|![IMG_3799 2](https://github.com/user-attachments/assets/6ee54fa7-43aa-4613-9d66-bf91d83d52d8)|<img  alt="스크린샷 2025-04-17 오전 9 31 31" src="https://github.com/user-attachments/assets/fbf62310-0bdb-409a-bc92-34ab7ce828d1" />|
|as-is|to-be|
|--|--|
|![IMG_3798 2](https://github.com/user-attachments/assets/ebec4760-978e-4335-8075-873ee5e5f46c)|<img alt="스크린샷 2025-04-17 오전 9 30 56" src="https://github.com/user-attachments/assets/afa04a5c-8c92-457b-a878-6094f5ebbe9b" />|
> [DMTALK-177] 전체보기 뷰 지오챗 스타일 오류 수정

- packages/tds-widget/src/chat/reservation-info/elements.tsx
- https://github.com/titicacadev/triple-frontend/pull/3675 수정에서 누락된 높이를 추가합니다.
- 렌더 영역의 패딩은 1.5 -> 5.5로 증가했지만 expanded 여부 확인을 위한 min-height은 수정되지 않아 텍스트 하단이 잘려보이는 오류를 수정합니다.
> reservation info min-height 수정

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- (Chat) [DMTALK-60] 챗룸 컴포넌트 추가 [#3608](https://github.com/titicacadev/triple-frontend/pull/3608)
- [DMTALK-183] 링크 두번 열리는 오류 수정 [#3681](https://github.com/titicacadev/triple-frontend/pull/3681)
- (Chat) 채팅 버블 부가 정보 커스텀 스타일 프롭스 추가 [#3574](https://github.com/titicacadev/triple-frontend/pull/3574)
- (Chat) 누락된 타입 export 및 props 추가 [#3585](https://github.com/titicacadev/triple-frontend/pull/3585)
- tds-widget/chat에서 triple-web 디펜던시를 제거 [#3586](https://github.com/titicacadev/triple-frontend/pull/3586)
- (chat) 커스텀이 가능한 채팅 리스트 공통 컴포넌트를 만든다. [#3588](https://github.com/titicacadev/triple-frontend/pull/3588)
- (Chat) [DMTALK-31] 채팅 공통타입 정리 [#3589](https://github.com/titicacadev/triple-frontend/pull/3589)
- (Chat) [DMTALK-32] 채팅 메시지 플로우 공통화 …
> 🚀 release v14.0.13

- packages/tds-widget/src/chat/input-area/index.tsx
- packages/tds-widget/src/chat/input-area/nol-input-area-ui/index.tsx
- packages/tds-widget/src/chat/input-area/nol-input-area-ui/types.ts
- packages/tds-widget/src/chat/reservation-info/elements.tsx
- packages/tds-widget/src/chat/types/room.ts
- chats > nol input의 커스텀 액션 버튼을 추가합니다. 
- disabled 상태 및 커스텀 스타일(`inputContainerColor`)을 추가합니다. 
- chats > reservation-info 스타일 오류를 수정합니다.
- chats > Metadata 타입 오류를 수정합니다.
> [DMTALK-165] chat 컴포넌트 커스텀 필드 추가, 스타일 및 타입 수정

- packages/tds-widget/src/chat/types/base.ts
- ChatChannelEvents 타입을 확장할 수 있도록 객체기반으로 이넘화 합니다.
> [DMTALK-310] ChatChannelEvents 타입 정의

- packages/tds-ui/src/components/popup/popup.tsx
[tds-ui] popup에 id props를 추가합니다.
FloatingPortal에 id를 부여하면 해당 portal div를 재사용할 수 있게 됩니다. portal의 순서 보장을 위해 id를 활용하려고 합니다.
([관련 문서](https://floating-ui.com/docs/FloatingPortal#id))
> [tds-ui] popup에 id props를 추가합니다.

- packages/poi-detail/src/detail-header-v2/index.tsx
- packages/user-verification/src/verification-request.stories.tsx
https://yanoljagroup.atlassian.net/browse/INTTNA-2259
내부 리뷰는 없고 공급사 리뷰만 있을 경우 상세 헤더에 리뷰보기 버튼을 노출하기 위한 처리
> [INTTNA-2259] 상세 헤더 TNA 공급사 리뷰로 사용하기 위해 리뷰 개수만 확인하여 리뷰보기 노출

- packages/tds-widget/src/chat/bubble-container/elements.tsx
- packages/tds-widget/src/chat/reservation-info/elements.tsx
- 프로필 이미지 object-fit을 cover로 정의합니다.
> [DMTALK-396] 프로필 이미지 object-fit 변경

- packages/tds-widget/src/date-picker/day-picker.tsx
- packages/tds-widget/src/date-picker/range-picker-v2/range-picker.tsx
- packages/tds-widget/src/date-picker/range-picker.tsx
- packages/tds-widget/src/date-picker/use-public-holidays.ts
[tds-widget] nol api를 받아올 수 있도록 RangePicker의 publicHolidays props를 복구합니다.
- 기타로 initialMonth도 외부에서 받아올 수 있도록 추가했습니다.
> [tds-widget] RangePicker에서 publicHoliday를 props로 받아올 수 있도록 수정합니다.

- packages/tds-widget/src/chat/messages/index.tsx
- parent message 클릭 시 해당 메시지로 스크롤되지 않는 오류를 수정합니다. 
- parent message를 `message-{id}` 로 검색하고 있으므로 첫 버블은 id에서 index 제거
https://github.com/titicacadev/triple-frontend/blob/9f281965e4a491eda5ae6e209a1faa7d142e8225/packages/tds-widget/src/chat/chat/scroll-context.tsx#L95
> [DMTALK-374] parent message로 스크롤 되지 않는 오류 수정

- packages/tds-ui/src/components/carousel/carousel-item.tsx
[기존 carousel-item이 `className`을 받던 것을 복](https://github.com/titicacadev/triple-frontend/blob/ba1c3f18373b6e74fb27844366963a9295b06a38/packages/carousel/src/carousel-item.tsx#L46)구하며 `prop`으로 확장성을 추가합니다.
> [tds-ui] carousel-item 추가 prop 받을 수 있도록 수정

- packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts
- https://github.com/titicacadev/triple-frontend/pull/3728 머지 시 리베이스가 누락된 부분을 적용합니다. 🙏
> fix: rebase 누락 적용

- packages/tds-ui/src/components/checkbox/checkbox-base.tsx
- packages/tds-ui/src/components/checkbox/checkbox.stories.tsx
- packages/tds-ui/src/components/checkbox/checkbox.tsx
체크박스 사이즈 설정 prop을 추가하고 불필요한 여백을 제거합니다. 
- `checkboxSize` prop 추가
- `display: block`으로 변경
- 정방형 체크박스 이미지로 변경
AS-IS
TO-BE
> [tds-ui] 체크박스 사이즈 설정 prop을 추가합니다.

- packages/tds-widget/src/map/focus-tracker.tsx
[tds-widget] focus tracker에 autoZoomThreshold props 추가
autoZoomThreshold를 외부에서 조정할 수 있도록 props로 추가합니다.
> [tds-widget] focus tracker에 autoZoomThreshold props 추가

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [tds-widget] focus tracker에 disabled props를 추가합니다. [#3739](https://github.com/titicacadev/triple-frontend/pull/3739)
> 🚀 Release v14.1.4

- packages/tds-widget/src/chat/types/room.ts
InvitationInterface에 validInvitation 필드 추가합니다.
> [TPB-3385] InvitationInterface 에  validInvitation 필드 추가

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [TPB-3385] InvitationInterface 에  validInvitation 필드 추가 [#3741](https://github.com/titicacadev/triple-frontend/pull/3741)
- [DMTALK-533] usePendingIntersections 추가 [#3742](https://github.com/titicacadev/triple-frontend/pull/3742)
- [DMTALK-505] 타입 업데이트 [#3743](https://github.com/titicacadev/triple-frontend/pull/3743)
[TPB-3385]: https://yanoljagroup.atlassian.net/browse/TPB-3385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DMTALK-533]: https://yanoljagroup.atlassian.net/browse/DMTALK-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DMTALK-505]: https://yanoljagroup.atlassian.net/browse/DMTALK-505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🚀 Release v14.1.5

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- [DMTALK-555] dismissKeyboardOnSend 옵션 추가 [#3747](https://github.com/titicacadev/triple-frontend/pull/3747)
[DMTALK-555]: https://yanoljagroup.atlassian.net/browse/DMTALK-555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> 🚀 Release v14.1.6

- CHANGELOG.md
- lerna.json
- packages/ab-experiments/package.json
- packages/constants/package.json
- packages/fetcher/package.json
- packages/i18n/package.json
- packages/intersection-observer/package.json
- packages/meta-tags/package.json
- packages/middlewares/package.json
- packages/react-hooks/package.json
- packages/router/package.json
- packages/scroll-to-element/package.json
- packages/standard-action-handler/package.json
- packages/tds-theme/package.json
- packages/tds-ui/package.json
- packages/tds-widget/package.json
- packages/triple-document/package.json
- packages/triple-email-document/package.json
- packages/triple-fallback-action/package.json
- packages/triple-header/package.json
- packages/triple-web-nextjs-pages/package.json
- packages/triple-web-nextjs/package.json
- packages/triple-web-test-utils/package.json
- packages/triple-web-utils/package.json
- packages/triple-web/package.json
- packages/type-definitions/package.json
- packages/view-utilities/package.json
- v13.48.1 변경사항을 적용합니다. [#3758](https://github.com/titicacadev/triple-frontend/pull/3758)
> 🚀 Release v14.1.8
