packages/app-installation-cta/src/banner-cta.tsx, packages/app-installation-cta/src/image-banner.tsx
- 배너 CTA 오버레이 클릭시, 해당 배너가 닫히도록 합니다.
- 하위 컴포넌트에 이벤트 전파가 되지 않도록 `stopPropagation` 처리를 해주는 코드를 추가합니다.
- 관련 지라 : https://titicaca.atlassian.net/browse/HI-2013
- 배너 CTA의 오버레이(백그라운드) 클릭시, 해당 배너가 닫히도록 유도합니다.
- 해당 이벤트의 버블링으로 인해 내부 컴포넌트 클릭시, 해당 배너가 닫히는것을 방지합니다.
=> 배너 CTA 오버레이 클릭시, 해당 배너가 닫히도록 합니다

packages/react-contexts/src/user-agent-context/utils.ts
react-triple-client-interfaces 패키지가 담당할 트리플 클라이언트 정보 관리 역할을 user-agent-context에서 deprecate합니다.
Related: #1832 
user-agent-context가 사용하는 `UserAgentValue` 타입에서 `isPublic`과 `app`에 deprecation notice를 추가합니다.
=> [react-contexts] user-agent-context의 isPublic과 app 속성에 deprecation notice를 추가합니다.

packages/react-triple-client-interfaces/README.md, packages/react-triple-client-interfaces/src/index.ts, packages/react-triple-client-interfaces/src/use-triple-client-feature-flag.spec.tsx, packages/react-triple-client-interfaces/src/use-triple-client-feature-flag.ts
#1728 에서 구현하던 Feature flag 훅을 재구현합니다.
- `useTripleClientFeatureFlag` 훅과 테스트를 작성합니다.
=> [react-triple-client-interfaces] useTripleClientFeatureFlag 훅을 추가합니다.

MIGRATION.md
`@titicaca/react-triple-client-interfaces`는 `@titicaca/user-verification` 패키지에서만 이용하고 있지만, `triple-document`등 간접 의존성을 가진 패키지들이 있으므로 미리 가이드를 하는 편이 안전하다고 보았습니다. 마이그레이션의 혼란을 줄이기 위해 `TripleClientMetadataProvider`를 마운트하는 내용을 추가합니다.
=> v6 마이그레이션 가이드에 react-triple-client-interfaces에 대응하는 내용을 추가합니다.

packages/map/src/map-view.tsx, packages/map/src/overlay/markers/poi-dot-marker.tsx, packages/map/src/overlay/markers/primary-marker/circle-marker/circle-marker-base.tsx, packages/map/src/overlay/markers/primary-marker/circle-marker/index.tsx, packages/map/src/overlay/markers/primary-marker/dot-marker.tsx
- 각 플젝에서 사용되는 `CircleMarkerType`, `CIRCLE_MARKER`를 export하여 사용가능하게 수정합니다.
-  `PoiDotMarker`에 props을 추가합니다 (dotSize, active/inActive Content, withDot)
- `coordinates`의 length가 0일때 bounds skip
=> [map] `PoiDotMarker`의 props, type 및 `CircleMarker`의 type 등을 export 합니다.

packages/triple-email-document/src/components/index.ts, packages/triple-email-document/src/elements/heading.tsx, packages/triple-email-document/src/elements/images.tsx, packages/triple-email-document/src/elements/link.tsx, packages/triple-email-document/src/elements/note.tsx, packages/triple-email-document/src/index.ts
Type
- export PreviewDocument Type
- export Images Types
Color
- var(--color-gray) => rgba(58, 58, 58, 1)
- email-admin은 @titicaca/core-elements의 GlobalStyle이 적용되어 있지 않으므로 rgba로 color를 표현합니다.
=> [triple email document] Migration에 필요한 Type을 내보내고, Color 표현을 수정합니다.

.eslintrc.js, packages/view-utilities/src/generate-deep-link/make-deep-link-generator.test.ts, packages/view-utilities/src/generate-deep-link/make-deep-link-generator.ts
[triple-email-api](https://github.com/titicacadev/triple-email-api)의 로직에서 OneLink 생성이 필요한데, 이전에 발송했던 OneLink params 중 `makeDeepLinkGenerator`가 지원하지 않는 속성이 있었습니다.
첫 이메일 캠페인에 썼던 OneLink params: https://titicaca.slack.com/archives/C01PCRU2XQR/p1635840393047300?thread_ts=1635300966.009600&cid=C01PCRU2XQR
JIRA 티켓: https://titicaca.atlassian.net/jira/software/projects/ENGDIVA/boards/57?selectedIssue=ENGDIVA-730
- `af_reengagement_window`를 지원합니다.
- `af_web_dp`를 `webUrl`로 Override 가능하게 합니다.
- 이전 테스트 케이스를 개선하고, 새로 추가한 params들에 대한 케이스를 추가합니다.
=> [view-utilities] makeDeepLinkGenerator가 지원하는 옵션을 확장합니다.

package-lock.json, packages/core-elements/package.json, packages/core-elements/src/constants.ts, packages/core-elements/src/elements/navbar.tsx, packages/core-elements/src/elements/spinner/rolling-spinner.tsx, packages/core-elements/src/elements/spinner/spinner.tsx, packages/core-elements/tsconfig.build.json, packages/core-elements/tsconfig.json, packages/triple-fallback-action/README.md, packages/triple-fallback-action/package.json, packages/triple-fallback-action/src/index.test.tsx, packages/triple-fallback-action/src/index.tsx, packages/triple-fallback-action/tsconfig.build.json, packages/triple-fallback-action/tsconfig.json, tsconfig.test.json
[애셋 로드에 실패했을 때 페이지를 벗어날 수 있는 기능](https://github.com/titicacadev/triple-content-web/pull/498)을 공통 모듈로 추출합니다.
클릭 대상의 클래스 이름, 스크립트를 추가하는 컴포넌트, 핸들러를 제거하는 훅과 컴포넌트를 제공합니다.
- `@titicaca/triple-fallback-action` 패키지 추가
- `@tititcaca/core-elements`에 `@titicaca/triple-fallback-action`을 의존성으로 추가
=> Triple Fallback Action 패키지 추가

packages/replies/src/auto-resizing-textarea.tsx, packages/replies/src/list/reply.tsx, packages/replies/src/register.test.tsx, packages/replies/src/register.tsx, packages/replies/src/reply.test.tsx
비로그인 상태일 때 처리하는 로직이 없어서, 사용자가 등록을 눌러도 아무 반응이 없는 오류가 있습니다.
비로그인 상태일 때에는 로그인 유도 모달을 노출하도록 합니다.
로그인 유도 모달이 들어가는 기능
- 좋아요 반응
- 댓글 달기
- 답글 달기
[매거진에 댓글달기 테스트 시트 9번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
=> [replies] 비로그인 상태일 때, 로그인 유도 모달 노출

packages/standard-action-handler/README.md, packages/standard-action-handler/src/index.ts, packages/standard-action-handler/src/new-window.test.ts, packages/standard-action-handler/src/new-window.ts, packages/standard-action-handler/src/types.ts
새창열기 기능을 추가합니다.
TL;DR
인앱에서는 `inlink`를 사용해 새 창을 여는 것이 가능하지만, 웹 브라우저에서는 불가능한 현상이 있었습니다. `inlink`로 표현한 링크를 모두 새 창에서 여는 것으로 변경하기에는 기존에 사용하고 있는 `inlink` 링크들이 웹 브라우저에서 같은 창에서 페이지를 여는 기능을 사용하는 경우가 있었습니다. 따라서 새 창 열기를 `standard-action-handler`에 새로운 기능으로 추가합니다. 
- `/web-action/new-window?href="이동할 URL"`
=> [standard-action-handler] 새창열기 기능 추가

packages/replies/src/replies.tsx, packages/replies/src/reply-tree-manipulators.test.tsx, packages/replies/src/reply-tree-manipulators.ts
불필요한 코드를 제거합니다.
- onClickCapture props를 제거합니다.
- deleteReply manipulators return 값을 수정합니다.
- 답글이 작성된 댓글을 지울 때에는  editReply를 실행하도록 분기를 나눴습니다. [관련 코드](https://github.com/titicacadev/triple-frontend/blob/main/packages/replies/src/list/index.tsx#L47-L52)
- 불필요한 테스트 코드를 제거합니다.
=> [replies] 불필요한 코드를 제거합니다.

package-lock.json, packages/user-verification/package.json, packages/user-verification/src/confirmation-services.test.ts, packages/user-verification/src/confirmation-services.ts, packages/user-verification/src/index.ts, packages/user-verification/src/types.ts, packages/user-verification/src/use-user-verification.test.ts, packages/user-verification/src/use-user-verification.ts, packages/user-verification/tsconfig.build.json, packages/user-verification/tsconfig.json
triple-cash-web 작업 중 발견했습니다. `personal-id-verification` 타입의 인증이 https://github.com/titicacadev/triple-user/pull/223 에서 추가한 API를 이용해야 하는데, 임시로 숙박대전용 API를 이용하던 상태였습니다.
Verification 상태 체크를 API Path만 달리 해서 수행하던 상태였는데, 응답 Body가 일정해서 가능한 상태였습니다. 그러나 이번에 작업하는 API는 응답 형식이 달라서 그 형식을 유지할 수 없었고, `verificationType`별로 명확한 상태 체크 API 호출 서비스를 별도로 구현합니다.
=> [user-verification] 인증여부 확인 API 경로를 변경합니다.

packages/resource-list-element/src/extended-resource-list-element.tsx
Closes #1519 
https://titicaca.slack.com/archives/C01CHRQBP1U/p1645594225549139
genie-web과 hotels-web에서도 `ExtendedResourceListElement`를 사용하는데 깨지는 부분을 발견했습니다
이 부분은 해당 PR의 수정사항이 반영되어 깨지는 부분이기에 제가 직접 두개 플젝에서 수정작업을 거치도록하겠습니다!
(content-web은 해당사항 없습니다!)
=> [resource-list-element] `ExtendedResourceListElement`의 가변 높이를 보장하도록 수정합니다.

packages/replies/src/list/reply.tsx
현재 2가지의 오류가 있습니다.
- 웹에서 프로필 사진, 닉네임, 멘션된 닉네임을 클릭했을 때, 액션이 없습니다.
- 앱에서 멘션된 닉네임 클릭 시, 아이코가 노출되는 오류가 있습니다.
원인
- 현재 유저 프로필 페이지가 웹에서 구현이 안된 상황(제가 알기론..)에서  inlink url를 사용하다보니 아이코가 노출되고 있는 것 같습니다. 
해결 방법
`onClick` 함수 생성 및 `navigate`를 이용하는 방식으로 수정해보았습니다.
- 웹에서는 `useAppCallback`을 이용해서 트리플 로그인 설치 유도 모달을 렌더링합니다.
- 앱에서는 `navigate`를 이용해서 해당 딥링크로 이동합니다.
[매거진에 댓글달기 테스트 시트 1번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
=> [replies] 프로필 및 멘션을 클릭했을 때, 액션을 추가합니다.

packages/standard-action-handler/src/image-download.ts, packages/standard-action-handler/src/index.ts
이미지 다운로드 web action을 추가합니다.
images API를 호출하여 입력된 imageId에 해당하는 이미지를 다운로드 받습니다.
[참여형 프로모션](https://titicaca.slack.com/archives/C1246L2MD/p1640919513357300?thread_ts=1636509689.091300&cid=C1246L2MD) 아티클에서 이미지를 다운로드하는 기능을 요구하여 개발하였습니다.
`<a>`tag의 [`download`](https://developer.mozilla.org/ko/docs/Web/HTML/Element/a#attr-download) 특성을 활용하기 위해 DOM에 추가되지 않은 anchor element를 생성해 활용합니다.
anchor element 활용 과정에서 [`동일 출처 정책`](https://developer.mozilla.org/ko/docs/Web/Security/Same-origin_policy) 준수를 위해 images API 작업을 요청하였습니다.
----------
lucian
https://developer.mozilla.org/ko/docs/Web/HTML/Element/a
웨이드께서 말씀하신대로 동일 출처 정책 때문에 a tag를 사용하는데 문제가 있었습니다.
api 만드는 것도 좋은 방법이지만 위의 문서의 내용 처럼 blob, data 스킴형태로 사용하면 작동시키는 방법을 고안한 결과 해당 PR의 수정내용처럼 작업해봤습니다.
Blob으로 객체를 생성하고 createObjectURL 함수를 통해서 다운로드 가능한 URL을 생성한 뒤 a …
=> [standard-action-handler] 이미지 다운로드 기능 추가 

packages/replies/src/auto-resizing-textarea.tsx, packages/replies/src/register.tsx
3가지 이슈를 수정합니다.
- 버튼의 디자인이 깨지는 오류를 해결합니다.
- 댓글&답글 작성 후, 입력창의 높이가 변경되지 않는 오류를 해결합니다.
- 입력창의 넓이를 flex 속성을 이용해서 확장합니다.
[매거진에 댓글 달기 테스트 시트 5번](https://docs.google.com/spreadsheets/d/1kzWfbAFQookK-sqi4OnpiAUHx0jKgQyR5X99y2DWPgU/edit#gid=195797161)
- 등록 버튼의 최소 넓이를 지정합니다.
- useEffect를 이용해서 입력된 값이 없을 때, Textarea의 높이를 초기화합니다.
- flex-grow 속성을 사용해서, 확장합니다.
=> [replies] 입력창의 오류를 해결합니다. 

.eslintignore, packages/intersection-observer/src/index.tsx, packages/intersection-observer/src/intersection-observer.d.ts, packages/intersection-observer/src/lazy-loaded-intersection-observer.tsx
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 intersection-observer 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
=> [intersection-observer] ESLint 검사를 활성화하고 오류를 수정합니다. 

package-lock.json, packages/standard-action-handler/package.json, packages/standard-action-handler/src/hook.test.tsx, packages/standard-action-handler/src/hook.ts, packages/standard-action-handler/src/types.ts, packages/standard-action-handler/tsconfig.build.json, packages/standard-action-handler/tsconfig.json, packages/triple-document/src/types.ts
`standard-action-handler` Hook을 생성합니다. 
현재 `stadard-action-handler`를 쓰는 곳에서 `useNavigate`, `useExternalRouter`를 파라미터로 직접 넘겨주고 있기 때문에 이를 편하게 하기 위해 Hook을 만들었습니다.
`initialize` 함수의 결과를 반환합니다.
=> [standard-action-handler] standardActionHandler Hook 생성

.eslintignore, packages/scrap-button/src/scrap-button-mask.tsx, packages/scrap-button/src/scrap-button.tsx
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 scrap-button 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
=> [scrap-button] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, packages/react-hooks/src/use-error-handler.ts, packages/react-hooks/src/use-fetch.ts, packages/react-hooks/src/use-interval.ts
Related to #1755 
#1737  에서 비활성화했던 `react-hooks`의 ESLint, Stylelint 검사를 다시 활성화합니다. 그리고 ESLint 오류를 수정합니다.
.eslintingnore에서 `react-hooks` 제거 및 오류 수정
=> react-hooks Lint 검사 활성화 및 오류 해결

.eslintignore, packages/app-banner/src/index.tsx
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 app-banner 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 app-banner 를 제거합니다.
- Props 스키마에 변화가 있습니다. (Breaking change입니다.)
- onCTAClick -> onCtaClick
=> [app-banner] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, packages/static-page-contents/src/index.tsx
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 static-page-contents 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 static-page-contents 를 제거합니다.
- triple-code-convention 을 적용합니다.
=> [static-page-contents] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, MIGRATION.md, docs/stories/map/types.ts, docs/stories/scroll-spy/scroll-spy.stories.tsx, packages/map/src/focus-tracker.tsx, packages/nearby-pois/src/nearby-pois.tsx, packages/poi-list-elements/src/types.ts, packages/type-definitions/src/geojson.ts, packages/type-definitions/src/image.ts, packages/type-definitions/src/listing-poi.ts, packages/view-utilities/src/measure-distance.ts
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 type-definitions 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 listing-filter 를 제거합니다.
- explicit-member-accessibility 오류에 대응합니다.
- Props 스키마에 변화가 있습니다. (Breaking change입니다.)
- PointGeoJSON -> PointGeoJson
- ListingPOI -> ListingPoi
=> [type-definitions] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, packages/web-storage/src/boundary.tsx, packages/web-storage/src/error.ts, packages/web-storage/src/storage.ts, packages/web-storage/src/utils.ts
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 web-storage 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 listing-filter 를 제거합니다.
- explicit-member-accessibility 오류에 대응합니다.
=> [web-storage] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, .stylelintignore, package-lock.json, packages/author/package.json, packages/author/src/index.tsx, packages/author/tsconfig.build.json, packages/author/tsconfig.json
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 author 디렉토리의 ESLint, StyleLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 author 를 제거합니다.
- .stylelintignore에서 author 를 제거합니다. 
- image type을 정의합니다.
- @titicaca/type-definitions 패키지 추가
=> [author] ESLint, Stylelint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, docs/stories/public-header/public-header.stories.tsx, package-lock.json, packages/public-header/package.json, packages/public-header/src/public-header.spec.tsx, packages/public-header/src/public-header.tsx, packages/public-header/tsconfig.build.json, packages/public-header/tsconfig.json
`react-contexts` 대신 `triple-react-client-interfaces` 패키지를 이용해 `PublicHeader`의 렌더링 여부를 분기합니다.
- `PublicHeader` 내부에서 `useTripleClientMetadata` 훅의 리턴 값이 있을 경우 렌더링을 생략합니다.
- `.eslintignore` 목록에서 `public-header` 패키지를 제거합니다.
=> [public-header] react-triple-client-interfaces를 이용해 렌더링 여부를 분기합니다.

docs/stories/booking-completion/booking-completion.stories.tsx, docs/stories/reviews/reviews.stories.tsx, docs/stories/router/external-link.stories.tsx, docs/stories/router/local-link.stories.tsx, docs/stories/router/styled-local-link.stories.tsx, docs/stories/social-reviews/social-reviews.stories.tsx, docs/stories/triple-document/tna-slot.stories.tsx, docs/stories/triple-document/triple-document.stories.tsx, integration-test/src/router-modal.test.tsx, packages/replies/src/reply.test.tsx, packages/router/src/common/disabled-link-notifier.test.ts, packages/router/src/common/disabled-link-notifier.ts, packages/router/src/external/hook.test.ts, packages/router/src/external/href-handler.ts, packages/router/src/external/link.test.tsx, packages/router/src/external/link.tsx, packages/router/src/href-to-props/use-href-to-props.test.ts, packages/router/src/href-to-props/use-href-to-props.ts, packages/router/src/local/hook.test.ts, packages/router/src/local/href-handler.ts, packages/router/src/local/link.test.tsx, packages/router/src/navigate/index.test.ts, packages/router/src/navigate/index.ts
기존에 `useUserAgentContext`를 쓰던 로직을 `useTripleClientMetadata`를 사용하도록 변경합니다.
- `@titicaca/router` 패키지 내에서 `useUserAgentContext`의 `isPublic`으로 분기하던 로직들을 `useTripleClientMetadata`를 이용하도록 변경합니다.
- `router` 패키지 내 테스트 케이스의 Mock들을 변경합니다.
- Integration test를 수정합니다.
- `replies` 패키지 테스트 과정에서 `router`의 `useNavigate` 모킹이 누락된 부분을 발견하여 추가합니다.
=> [router] 앱 사용중 여부를 react-triple-client-interfaces 패키지의 정보로 구분합니다.

.eslintignore, MIGRATION.md, packages/app-installation-cta/src/app-installation-cta.tsx, packages/app-installation-cta/src/article-card-cta/article-card-cta.tsx, packages/app-installation-cta/src/banner-cta.tsx, packages/app-installation-cta/src/chatbot-cta.tsx, packages/app-installation-cta/src/constants.ts, packages/app-installation-cta/src/floating-button-cta.tsx, packages/app-installation-cta/src/image-banner.tsx, packages/app-installation-cta/src/interfaces.ts, packages/app-installation-cta/src/text-banner.tsx
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 app-installation-cta 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 static-page-contents 를 제거합니다.
- Component 명에 변화가 있습니다. (Breaking change입니다.)
- AppInstallationCTA -> AppInstallationCta
- ArticleCardCTA -> ArticleCardCta
- BannerCTA -> BannerCta
- ChatbotCTA -> ChatbotCta
- FloatingButtonCTA -> FloatingButtonCta
=> [app-installation-cta] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, packages/action-sheet/src/components/action-item.tsx, packages/action-sheet/src/components/action-sheet.tsx, packages/action-sheet/src/index.tsx
Related to #1755 
#1737 에서 비활성화했던 action-sheet 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
`src/components/action-sheet.tsx` `action-sheet/src/index.tsx`의 `error  Delete `;`  prettier/prettier` 해결
`src/components/action-item.tsx`의 `typescript-eslint/no-explicit-any`에 ignore를 적용해 임시 해결
usage에서의 `any` 타입 인자가 사용되는 경우가 있어 `no-explicit-any` rule을 ignore하고 별도 issue로 처리하려합니다. 
ex) [`tna-web-v2/src/product/navbar.tsx` line 234](https://github.com/titicacadev/tna-web-v2/blob/main/src/product/navbar.tsx#L234): `ui-flow`의 `use-app-callback`에 존재하는 [`any` 타입 returnValue](https://github.com/titicacadev/triple-frontend/blob/main/packages/ui-flow/src/use-app-callback.ts#L18)이 전달됩니다.
더 나은, 바로 해결할 방법이 있다면 조언 부탁드립니다!
=> [action-sheet] ESLint 검사를 활성화하고 오류를 수정합니다.

.eslintignore, packages/ab-experiments/src/google-optimize-context/context.tsx, packages/ab-experiments/src/triple-ab-experiment-context/context.tsx, packages/ab-experiments/src/triple-ab-experiment-context/service.ts
https://github.com/titicacadev/triple-frontend/pull/1737 에서 비활성화했던 ab-experiments 디렉토리의 ESLint 검사를 다시 활성화합니다. 그리고 발생한 오류를 수정합니다.
- .eslintignore에서 ab-experiments 를 제거합니다.
=> [ab-experiments] ESLint 검사를 활성화하고 오류를 수정합니다.

.github/workflows/cd.yaml, .github/workflows/ci.yaml, README.md, package-lock.json, package.json
Closes #1719
#1719 에 해당하는 이슈입니다.
https://github.com/lerna/lerna/issues/2891#issuecomment-954876165 
npm 7.20 - 8.4 버전까지 TF 버전 업 시 package-lock.json가 업데이트 되지 않는 이슈가 있었습니다.
8.5이상 버전부터는 [릴리즈 노트 내용](https://github.com/nodejs/node/pull/41925)과 같이 fix 되었습니다.
---
node 버전 업 ([노드 문서](https://nodejs.org/ko/download/releases/))
npm version 8.5.0 이상을 지원하는 노드 버전이 17.6부터여서 노드 버전도 올리게 됐습니다.
위의 내용에 따라 npm 버전을 8.5이상으로 강제하여 이슈를 해결하고자 합니다.
=> npm 버전 8.5이상으로 강제하고 node version을 17.7.0으로 변경합니다.

package-lock.json, packages/replies/src/reply.test.tsx, packages/ui-flow/package.json, packages/ui-flow/src/auth-guard/index.ts, packages/ui-flow/src/guarded-scraps-provider.tsx, packages/ui-flow/src/use-app-callback.test.ts, packages/ui-flow/src/use-app-callback.ts, packages/ui-flow/tsconfig.build.json, packages/ui-flow/tsconfig.json
`@titicaca/ui-flow` 패키지에서 `useUserAgentContext` 대신 `useTripleClientMetadata`를 이용합니다. 
- `ui-flow` 패키지의 의존성에 `react-triple-client-interfaces`를 추가합니다.
- `ui-flow` 내부 로직에서 `useTripleClientMetadata`를 호출합니다.
- 이로 인해 실패하는 reply 테스트 케이스를 위해 mocking을 개선합니다.
=> [ui-flow] react-triple-client-interfaces로 웹-앱 동작을 분기합니다.

MIGRATION.md
v7부터는 `@titicaca-react-triple-client-interfaces` 적용이 필수에 가깝게 되어서 한 번 더 명시해주었고, 네이밍 변경 항목 추가했습니다.
=> v7 Migration guide를 보완합니다.

packages/user-verification/src/confirmation-services.test.ts, packages/user-verification/src/confirmation-services.ts, packages/user-verification/src/types.ts, packages/user-verification/src/use-user-verification.test.ts, packages/user-verification/src/use-user-verification.ts
다양한 외부 프로모션이 요구하는 사용자 인증 형태에 대응하기 위해 유연한 `VerificationType`을 지원합니다.
- `VerificationType`을 `string` 타입으로 완화합니다. (`string`을 직접 사용하도록 유도하기 위해 Deprecate합니다.)
- `"external-promotion-*"` 패턴의 `verificationType`은 외부 프로모션용 검증 API, 인증유도 URL을 사용합니다.
- Refer https://github.com/titicacadev/triple-verifications-web/pull/102, https://github.com/titicacadev/triple-user/pull/236
=> [user-verification] External promotion에 대응 가능하도록 인터페이스를 확장합니다.

docs/stories/replies/replies.stories.tsx, packages/replies/README.md, packages/replies/src/list/index.tsx, packages/replies/src/replies.tsx
입력창을 화면 최하단에 고정하는 optional props를 추가합니다.
**props**
1 `isFormFixed`을 추가합니다.
- true일 때, 화면 최하단에 댓글/답글 입력창을 고정합니다.
- false일 때, 댓글/답글 리스트 아래에 댓글/답글 입력창을 위치시킵니다.  (default)
2 `padding`을 추가합니다.
- replies 패키지를 사용하는 프로젝트에서 댓글/답글 리스트의 padding을 설정할 수 있습니다. 
**docs**
- README.md를 수정합니다.
=> [replies] 입력창을 화면 최하단에 고정하는 props를 추가합니다.

packages/date-picker/src/day-picker.tsx
day-picker에서 fromMonth, toMonth에 의한 설정이 제대로 안되고 있었습니다. 
https://react-day-picker-v7.netlify.app/examples/months-restrict 를 보면 fromMonth, toMonth가 동작하려면 [month](https://react-day-picker-v7.netlify.app/api/DayPicker#month)를 같이 받아야지 동작이 되도록 처리되어있습니다.
=> [date-picker] day-picker의 fromMonth, toMonth가 동작되도록 수정

packages/react-contexts/src/my-reviews-context/my-reviews-provider.tsx
리뷰 삭제 후에 web-to-native-interface의 함수인 `notifyReviewDeleted `가 중복해서 불리고 있었습니다.
- 삭제 액션 시트에서 호출: [링크](https://github.com/titicacadev/triple-frontend/blob/5f9a72c002c6631441a523097d2af1b9e7530f2e/packages/review/src/my-review-action-sheet.tsx#L53)
- `MyReviewsProvider`에서 호출: [링크](https://github.com/titicacadev/triple-frontend/blob/5f9a72c002c6631441a523097d2af1b9e7530f2e/packages/react-contexts/src/my-reviews-context/my-reviews-provider.tsx#L94)
`MyReviewsProvider`에서 `notifyReviewDeleted` 호출을 제거합니다.
=> notifyReviewDeleted 중복 호출 제거

docs/stories/poi-detail/detail-header-v2.stories.tsx, docs/stories/poi-detail/detail-header.stories.tsx, packages/poi-detail/src/area-names.tsx, packages/poi-detail/src/area.tsx, packages/poi-detail/src/detail-header-v2/index.test.tsx, packages/poi-detail/src/detail-header-v2/index.tsx, packages/poi-detail/src/detail-header/index.test.tsx, packages/poi-detail/src/detail-header/index.tsx
detail-header컴포넌트의 areas props의 타이핑을 확장
- string타입을 추가하고, 타입에 따라 분기되도록 수정
=> [poi-detail] areas props의 타이핑을 string도 받을수 있도록 확장

package-lock.json, packages/react-triple-client-interfaces/package.json, packages/search/package.json
TF와 [triple-web-to-native-interfaces](https://github.com/titicacadev/triple-web-to-native-interfaces)를 동시에 쓰면 다른 버전이 설치되면서 native interface가 이상동작하는 상황이 생깁니다.
triple-web-to-native-interfaces를 TF로 옮겨오면 좋겠지만.. 작업이 크기때문에 일단 TF에서 peerDependencies로 변경해놓습니다.
=> web-to-native-interfaces 모듈을 peerDependencies로 설정

packages/social-reviews/src/external-links.tsx
1. ExternalLink 데이터에 `imageUrl`이 비어있을 경우 이미지를 노출하지 않습니다. (현재는 이미지가 빈 회색으로 노출되고 있습니다.)
[슬랙 링크](https://titicaca.slack.com/archives/CRHS5TUNM/p1653268299802699)
2. 텍스트 간격을 `8`에서 `6`으로 조정합니다. (추가 수정 요청 사항)
1. Image 컴포넌트 노출 부분을 `{imageUrl && (...)}` 조건부 노출로 변경
2. 텍스트 마진 6으로 조정
=> ExternalLink의 imageUrl이 있을 때만 Image 노출

packages/replies/src/replies.tsx
Viewport 하단 영역에 safeAreaInset이 필요한 경우, 이 mixin이 없다면 터치 이벤트를 방해할 수 있습니다.
`FixedBottom` 컨테이너에 `core-elements` 패키지의 `safeAreaInsetMixin`을 추가합니다.
=> [replies] FixedBottom 컨테이너에 safeAreaInsetMixin을 추가합니다.

packages/triple-document/src/elements/images.tsx
필요에 따라 Context가 아닌 Props를 통해 이벤트 핸들러를 주입 가능하도록 합니다. `images` 요소만 별도로 사용하고자 하는데, 이벤트 핸들링을 다루기 위해서는 `TripleDocument` 전체를 Mount해야 하는 불편이 있었습니다.
- `images` 요소 렌더링에 사용하는 `Images` 컴포넌트에 `onLinkClick`, `onImageClick` props를 추가합니다.
- 각 핸들러는 Optional type입니다.
- 핸들러가 props로 전달될 경우, Context가 아닌 props의 핸들러를 사용합니다.
https://titicaca.atlassian.net/browse/ENGDIVA-999
=> [triple-document] images 요소의 이벤트 핸들러를 Override할 수 있도록 합니다.

packages/replies/src/replies.tsx
페이지 진입시 노출하는 댓글 갯수를 변경할 수 있도록 props를 추가합니다.
자세한 내용은 [관련 스레드](https://titicaca.slack.com/archives/CRHS5TUNM/p1654228329233469)에서!
- initialSize를 정의한다면 정의한 숫자만큼 댓글이 노출됩니다.
아래는 댓글 16개가 달린 [공유 일정](https://triple-dev.titicaca-corp.com/trips/lounge/itineraries/6e891c08-c879-4f89-ac87-8ba35e4fa61b)이며, 초기 렌더링 시 3개를 노출합니다.
=> [replies] 노출하는 댓글 갯수를 변경할 수 있도록 props를 추가합니다.

packages/map/src/map-view.tsx
- 현재 Map에서 컴포넌트 내가 아닌 뷰포트 중앙에 뜨는 spinner를 사용하고 있습니다.
- 위와 같은 사용을 의도되지 않은 랜더링으로 보고 이를 제거합니다.
- [packages/map/src/map-view.tsx](https://github.com/titicacadev/triple-frontend/compare/fix/remove-map-spinner?expand=1#diff-e2c9d3c5488a9e35379a1f9d9670e85691e66f4376c228e6c6f6569e0e4d0d28): `Spinner`를 삭제합니다. `isLoaded` 분기는 필수적이므로 로딩 중에는 `null`을 리턴합니다.
- tf에서 적절한 spinner 소스를 발견하지 못했고, 기존 `Spinner`가 공간을 확보하는 placeholder기능을 하지 않음에도 문제가 없었으므로 로딩 중에는 `null`을 리턴하도록 했습니다. 로딩 중인 경우를 다루는 나은 방법에 대해 의견을 부탁드립니다🙇‍♂️
=> Map에서 의도치 않은 spinner를 삭제합니다.

packages/ad-banners/src/api.ts
`ad-banners` 패키지의 클릭 관련 이벤트 수집이 안되는 오류를 수정합니다.
- [관련 스레드](https://titicaca.slack.com/archives/C01CHRQBP1U/p1655445449851739)
[fetcher 안에서 직렬화](https://github.com/titicacadev/triple-frontend/blob/main/packages/fetcher/src/make-request-params.ts#L49)를 하고 `ad-banners` 안에서 또 한번 직렬화를 하다보니 그런 것으로 추정됩니다.
- [패키지 내 isomorphic-fetch를 제거하고 fetcher로 대체](https://github.com/titicacadev/triple-frontend/pull/2045)
- [정상요청](https://app.datadoghq.com/logs?event=AQAAAYFn5NqdkbNqGgAAAABBWUZuNVF2U0FBRFpha2hvT0F2NlE4T1c&from_ts=1655304460380&index=&live=false&query=trace_id%3A1446947008268632105&to_ts=1655306460533)
- [비정상요청](https://app.datadoghq.com/logs?event=AQAAAYFwYTjCp7UWuwAAAABBWUZ3WVZadUFBQUZLZ1RjM2s0MnlMQW0&from_ts=1655446828673&index=&live=false&query=trace_id%3A1342202844421033491&to_ts=165544882871 …
=> [ad-banners] 이벤트 수집이 안되는 오류를 해결합니다.

packages/constants/src/regex.ts
`KOREAN_REGEX` 정규식에서 "|" 문자를 제거합니다. 그동안 한글과 | 문자를 포함한 정규식이었습니다.
triple-frontend 안에서는 사용하는 곳이 없었습니다.
triple-air-web에서 영문 필드에 한글을 제거하는데 쓰고 있었습니다.
[hotel-master에 같은 정규식](https://github.com/titicacadev/hotel-master/blob/9b23ef8601a5b69d70513dbdaceac248f6de75a0/src/main/kotlin/com/triple/hotel/master/Constants.kt#L7)이 있는데 괜찮은 걸까요?
=> `KOREAN_REGEX`에서 "|"를 제거

docs/stories/map/mock.ts, packages/map/src/map-view.tsx, packages/map/src/utilities.ts
- 해당이슈 [PR](https://github.com/titicacadev/tna-partners-web/pull/477#issuecomment-1160096938)
- 기존에는 zoom이 undefined => 13으로 바뀌어 13으로 고정되어서 undefined으로 1차 수정 
=> zoom 값 자체가 undefined으로 들어가다 보니 처음 로드시 인식으로 못해서 구글맵 BG 색상이 회색으로 나오는 2차 오류 발견
=> poi가 1개인 경우 줌레벨은 17로 고정하고 2개부터는 bounds에 의존하여 보여지도록 수정
- `getGeometry`의 `zoom`을 제거합니다
현재 `getGeometry`의 `zoom`은 파트너센터에서만 사용하고 있고 또한 이 작업으로 인해 사용하지 않으므로 제거합니다.
=> [map] `Mapview` zoom이 제대로 잡히지 않는 오류를 수정합니다.

packages/core-elements/src/global-style.ts
input, textarea의 폰트 스타일을 동일하게 처리되도록 수정
- global-style에 input, textarea에 font-family를 추가
=> feat: input, textarea에 font 초기화

packages/public-header/src/public-header.spec.tsx, packages/public-header/src/public-header.tsx
public-header가 마이그레이션전에는 children을 받을수 있었는데, 마이그레이션되면서 제거가 되었군요.
[my-booking-web](https://github.com/titicacadev/my-bookings-web/blob/main/src/components/index.tsx#L125-L145)에서는 children으로 처리하고 있는 상황이라서, children을 추가하도록 합니다.
변경된 [PR](https://github.com/titicacadev/triple-frontend/pull/1586/files#diff-5941651ebbc5266a34b0dabef0236c210cf1b68260a75c9b534e2ae3189e9954)
=> [public-header] public-header props를 추가합니다.

packages/i18n/src/backend.ts, packages/i18n/src/index.ts
`@titicaca/i18n`에서 사용하던 backend 모듈을 외부에서 사용할 수 있도록 내보냅니다.
이름은 `I18nextTripleWebAssetsBackend`로 설정합니다.
`dev` 옵션을 통해 개발 환경 web assets에 접근할 수 있는 기능을 추가합니다.
- `I18nextTripleWebAssetsBackend` 클래스 내보내기
- `dev` 옵션 추가
=> i18next triple-web-assets backend를 추가합니다.

packages/modals/src/transition-modal.tsx
TransitionModal props에 action click optional props를 추가합니다.
- 데이블 이벤트가 트리플 앱 설치 유도 모달의 `트리플 가기`를 클릭했을 때 수집되도록 하기 위함
TransitionModal props에 onClick props를 추가합니다.
=> TransitionModal props에 action click optional props를 추가합니다.

.github/workflows/ci.yaml, .github/workflows/renovate-pr-fix.yaml
- 2번 실행되던 ci 액션을 1번으로 바꾸기 위해 renovate PR에서 실행되지 않도록 하고 renovate-pr-fix 액션에서만 실행되도록 변경합니다.
- workflow_call의 inputs을 이용하여 renovate-pr-fix에서 `If working tree dirty, shutdown job`이 실행되지 않도록 합니다.
=> `renovate` PR에서 CI를 한 번만 동작하도록 변경합니다.

docs/stories/__mocks__/triple-document.sample.json, packages/triple-document/src/elements/images.tsx, packages/triple-document/src/elements/shared/display-containers.tsx
- 어드민페이지에서 가로배열에 사용되는 `DocumentCarousel`의 `margin props`가 누락되는 이슈를 해결합니다.
- `DocumentCarousel`에 `margin`값을 적용하는 새로운 `Component`를 생성했습니다.
=> 아티클 어드민에 사용되는 이미지 가로배열(default) margin props 누락 수정

packages/i18n/src/i18next.ts, packages/map/src/focus-tracker.tsx, packages/map/src/map-view.tsx, packages/react-contexts/src/history-context/history-context.tsx, packages/react-contexts/src/hooks.tsx, packages/review/src/components/review-container.tsx
지속적으로 뜨는 린트 워닝 뜨지 않도록 수정했습니다 
close https://github.com/titicacadev/triple-frontend/issues/2203
- import Router 부분 import router from 'next/client'로 변경해 보려고 했는데 참조하는 'react-dom/client'가 react 18부터 지원되서 disable 주석만 추가했습니다 
- i18n은 i18next로 수정하면 고쳐지긴 하는데 사용부에서 문제가 생길까봐 여기도 주석만 추가했습니다
=> Lint warning 수정

docs/stories/core-elements/tabs.stories.tsx, packages/core-elements/src/elements/tabs/index.tsx, packages/core-elements/src/elements/tabs/rounded-tab.tsx
- Tabs 패키지에 rounded 모양을 추가합니다.
- `RoundedTab` 컴포넌트 추가
- `TabType`에 `rounded` 타입 추가
- `StoryBook`에 `roundedTab` 샘플 데이터 추가
- [hotels](https://triple-staging.titicaca-corp.com/hotels/curation/product-listing-deal/855ea355-cde8-4357-a3c1-7d793446934d?checkIn=2022-11-13&checkOut=2022-11-14&numberOfAdults=2&categoryGroupFilter%5B0%5D=5f913a0edc0e8200016da34e&_triple_no_navbar=true)
- [air](https://triple-staging.titicaca-corp.com/air/curation/air-theme-highlighting-deal/a2897afd-318a-40b0-b06b-6552e7902fd3?_triple_no_navbar)
- [tna](https://triple-staging.titicaca-corp.com/tna/curation/product-listing-deal/4ae9f7b8-2af9-41ba-8c63-ec6ec86c75e4)
- [스레드](https://titicaca.slack.com/archives/C0J3TT1H8/p1657701375633549?thread_ts=1655102310.388119&cid=C0J3TT1H8)
- [Hotels …
=> [core-element] tabs에 rounded-tab 추가

.github/workflows/renovate-pr-fix.yaml
Renovate bot이 아니고 사람이 푸시하는 경우엔, 이 GHA에서 수정하려는 Broken dependency가 없을 수 있습니다. 그 상황에서 `git commit`의 exit status는 0이 아니게 되고, 그로 인해 GHA 실행이 실패하고, PR의 Branch Protection 룰이 Check Failure 상태에 놓이게 됩니다.
위 문제 우회를 위해 `git commit`의 오류를 무시하도록 합니다.
`git commit` 및 `push` 커맨드 이후 `|| true`를 추가합니다.
=> nothing-to-commit 에러를 무시합니다.

packages/triple-document/src/elements/images.tsx
센트리의 [#952 Error: Element type is invalid](https://github.com/titicacadev/triple-content-web/issues/952) 이슈를 해결합니다.
triple-doucment의 image에서 display가 존재하지 않거나 `IMAGE_CONTAINER_MAP`에 존재하지 않을 때 디폴트 컨테이너를 설정합니다.
=> [triple-document] 디폴트 이미지 컨테이너 설정

integration-test/src/router-modal.test.tsx, packages/react-contexts/src/session-context/app.tsx, packages/react-contexts/src/session-context/provider.tsx
일부 인앱브라우저에서만 필요한 세션 고정 기능이 전체 인앱브라우저 환경에서 실행되고 있습니다. 지금까지는 큰 문제가 없었지만, 쿠키가 유실될 수 있는 상황을 발견했습니다: https://developer.android.com/about/versions/12/behavior-changes-12?hl=ko#samesite
`InAppSessionContextProvider`의 props에 `preventSessionFixation`이라는 prop을 추가합니다. 이 prop의 값이 `true`이면 쿠키 변경을 하지 않습니다.
=> [react-contexts] 세션 고정을 방지할 수 있도록 합니다.

packages/core-elements/src/elements/video/play-pause-button.tsx, packages/image-carousel/src/video-content.tsx, packages/review/src/components/review-element/media/video.tsx
비디오 자동재생 문제 해결
[TRIPLE-CONTENT-WEB-A4B
](https://sentry.io/organizations/titicaca-corp/issues/3627285063/?query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d)
[TRIPLE-CONTENT-WEB-A76
](https://sentry.io/organizations/titicaca-corp/issues/3649174441/?query=is%3Aunresolved+assigned%3Ame&referrer=issue-stream&statsPeriod=14d)
https://titicaca.slack.com/files/URE6H1L01/F042U71PNA3/3.mp4
- 모바일 기기 배터리 절전모드에서는 비디오 자동재생이 불가능하고 에러를 던집니다. 이 에러를 센트리에 리포트 되지 않도록 에러를 무시합니다.
- iOS에서 `object-fit: cover` 스타일의 비디오를 처음 재생할 때 레이아웃이 깨지는 현상이 있습니다. 비디오를 처음에 숨기고 있다가 첫 timeUpdate 이벤트가 발생했을 때 비디오를 보여주어서 우회합니다. 
- 비디오와 poster를 분리해서 비디오에 opacity transition을 줄 수 있게 만듭니다.
before
https://user-images.githubusercontent.com/11497500/199685770-4964565d-c1a2-4b4f-b480-aad54ee5bb13.MP4
after …
=> 비디오 자동재생 문제 해결

packages/core-elements/src/elements/label.tsx, packages/core-elements/src/global-style.ts
블랙프라이데이 대응합니다.
rgba 코드는 #222222이고, 컬러명은 black으로 진행합니다.
관련 쓰레드 : [https://titicaca.slack.com/archives/C0263JTN4DS/p1668494074232759?thread_ts=1666666650.565229&cid=C0263JTN4DS](https://titicaca.slack.com/archives/C0263JTN4DS/p1668494074232759?thread_ts=1666666650.565229&cid=C0263JTN4DS)
=> [common] 블랙프라이데이 대응 black 컬러 추가

packages/action-sheet/src/action-sheet-base.tsx, packages/action-sheet/src/action-sheet-body.tsx, packages/action-sheet/src/action-sheet-context.tsx, packages/action-sheet/src/action-sheet-item.tsx, packages/action-sheet/src/action-sheet-overlay.tsx, packages/action-sheet/src/action-sheet.stories.tsx, packages/action-sheet/src/action-sheet.tsx, packages/action-sheet/src/index.ts, packages/app-installation-cta/src/elements.tsx, packages/core-elements/src/elements/textarea/textarea.tsx
action-sheet 패키지의 스타일 적용 관련하여 수정하였습니다.
- 액션시트 사용하는 화면에 z-index가 걸려 있는 엘리먼트가 있어서 큰 값으로 z-index를 추가하였습니다.
- 스타일을 확장하여 사용하기 위해 customOverlay prop을 추가했습니다.
- 기존 확장은 적용이 되지 않아서 변경해봤는데 검토 부탁드립니다🙇🏻
- 적용부분: https://github.com/titicacadev/tna-partners-web/pull/839/commits/1f74a6c09fdb83b72697f07075715f02b8e443c1
https://617b7c4431c922004a42c7cc-vuayktiaao.chromatic.com/?path=/story/action-sheet-action-sheet--with-extend-style
=> [action-sheet] 스타일 관련 수정

packages/core-elements/src/elements/flex-box/flex-box.tsx, packages/core-elements/src/elements/select/select.tsx, packages/form/src/checkbox/index.tsx
prop 타입과 attr 타입을 분리해 구분지어 사용 가능하도록 합니다. 
- https://github.com/titicacadev/triple-frontend/pull/2264#discussion_r1024870573
-  flexbox item 타입을 분리합니다
- select 타입을 분리하고 HTMLAttributes 타입을 추가합니다
- checkbox 타입 오류를 수정합니다
=> [core-elements] Props 타입과 HTMLAttributes 타입 분리 

docs/stories/app-installation-cta/banner-cta.stories.tsx, packages/app-installation-cta/src/app-installation-cta.tsx, packages/app-installation-cta/src/banner-cta.tsx, packages/app-installation-cta/src/elements.tsx, packages/app-installation-cta/src/image-banner.tsx
호텔, TNA에서 사용할 배너 형식의 CTA에서 Dimmed 처리된 영역(= overlay)를 제거합니다.
[관련 스레드](https://titicaca.slack.com/archives/C0J3TT1H8/p1668496511081169?thread_ts=1667888668.839489&cid=C0J3TT1H8)
- Dimmed 영역 제거
- 스토리북 이미지가 안나오는 이슈 수정
- 인벤토리 어드민 (dev)에서 해당 인벤토리가 제거되서 수정했습니다.
=> [app-installation-cta] 배너 CTA의 Dimmed 영역을 제거합니다.

packages/action-sheet/src/index.ts, packages/form/src/action-sheet-selector/action-sheet.tsx, packages/location-properties/src/location-properties.tsx, packages/poi-detail/src/copy-action-sheet-item.tsx, packages/poi-detail/src/copy-action-sheet.tsx, packages/replies/src/list/reply.tsx, packages/review/src/components/my-review-action-sheet.tsx, packages/review/src/components/others-review-action-sheet.tsx
[action-sheet] export default 제거
- (Breaking Change) 일관된 import 구문 사용과 린트 warning을 제거를 위해서 ActionSheet 컴포넌트의 default export을 제거합니다.
=> [action-sheet] export default 제거

packages/core-elements/src/elements/checkbox/checkbox-group.tsx, packages/core-elements/src/elements/form-field/form-field-context.tsx, packages/core-elements/src/elements/form-field/form-field-label.tsx, packages/core-elements/src/elements/form-field/form-field.tsx, packages/core-elements/src/elements/form-field/use-form-field-state.ts, packages/core-elements/src/elements/radio/radio-group.tsx, packages/core-elements/src/elements/select/select.tsx, packages/core-elements/src/elements/textarea/textarea.tsx
[core-elements] FormField에 isFocused 상태와 핸들러 추가
- input에 focus 되었을 때 Label의 컬러를 변경해야 하는데 css만으로는 Label에서 focus 상태를 알 수 있는 방법이 없어서 FormField가 isFocused 상태를 관리할 수 있게 합니다.
- FormField 사용하는 컴포넌트를 업데이트 합니다.
- Label에 display: inline-block을 추가해서 margin-bottom이 제대로 보이도록 합니다.
=> [core-elements] FormField에 isFocused 상태와 핸들러 추가

packages/core-elements/src/elements/button/basic-button.tsx, packages/core-elements/src/elements/button/button-base.test.tsx, packages/core-elements/src/elements/button/button-base.tsx, packages/core-elements/src/elements/button/button.tsx, packages/core-elements/src/elements/button/icon-button.tsx, packages/core-elements/src/elements/button/index.ts, packages/core-elements/src/elements/button/normal-button.tsx, packages/core-elements/src/elements/checkbox/checkbox-base.tsx, packages/core-elements/src/elements/checkbox/checkbox.tsx, packages/core-elements/src/elements/confirm-selector/confirm-selector.tsx, packages/core-elements/src/elements/gender-selector/gender-selector.tsx, packages/core-elements/src/elements/radio/radio-base.tsx, packages/core-elements/src/elements/radio/radio.tsx, packages/core-elements/src/elements/select/select.tsx
[core-elements] Button과 Input 관련 컴포넌트 props 타입 개선
- Button, ButtonBase의 Props와 OwnProps 분리
- ButtonBase의 type attribute가 변경되지 않던 문제 수정
- Checkbox, Radio 컴포넌트에 InputHTMLAttributes 타입 추가
- GenderSelector, ConfirmSelector Props 타입도 extend
- Input 관련 컴포넌트에 forwardRef 추가
=> [core-elements] Button과 Input 관련 컴포넌트 props 타입 개선

packages/poi-detail/src/actions.tsx, packages/web-storage/README.md, packages/web-storage/src/error.ts, packages/web-storage/src/storage.ts, packages/web-storage/src/types.ts
[TRIPLE-CONTENT-WEB-A7F](https://sentry.io/organizations/titicaca-corp/issues/3650396944/?query=is%3Aunresolved+assigned%3Amia%40triple-corp.com&referrer=issue-stream&statsPeriod=14d), [TRIPLE-CONTENT-WEB-A7K](https://sentry.io/organizations/titicaca-corp/issues/3651947573/?query=is%3Aunresolved+assigned%3Amia%40triple-corp.com&referrer=issue-stream&statsPeriod=14d) 오류를 해결하기 위해 `web-storage`의 인자를 추가합니다.
`web-storage` 패키지를 사용하는 각 레포지토리가 window의 web storage를 접근하면서 발생하는 오류를 각자 처리할 수 있는 옵션을 제공하기 위해 `onError` 인자를 추가합니다. 
- `onError` 인자를 추가
- `webStorage`의 `error type(unavailable, notBrowser, quotaExceeded)`에 해당하는 오류들을 처리하기 위한 함수를 받을 수 있습니다. 
- README 업데이트
- `onError` 인자에 대한 설명
- `onError` 인자 사용 시 `WebStorageErrorBoundary`에 미치는 영향
- poi-detail에 web-storage 에러 처리 추가
- poi-detail에서는 [#2240 ]을 위해 …
=> [web-storage, poi-deatail] web-storage 오류 처리 함수 추가

package-lock.json, packages/core-elements/package.json, packages/core-elements/src/elements/tabs/pointing-tab-list.tsx, packages/core-elements/src/elements/tabs/pointing-tab.tsx, packages/core-elements/src/elements/tabs/rounded-tab-list.tsx, packages/core-elements/src/elements/tabs/tab-panel.tsx, packages/core-elements/src/elements/tabs/tabs-context.tsx, packages/core-elements/src/elements/tabs/tabs.tsx
Tabs 컴포넌트를 generic type 으로 변경합니다. 
기존에 Tabs 컴포넌트를 enum 등을 사용해 generic 을 활용하고 있는 부분이 있었습니다. 
호환성을 높이기 위해 generic으로 변경했습니다. 
context에도 generic을 적용해야 해서 `lodash.once`를 사용하였습니다. 
카나리 적용해 제네릭 적용된 모습입니다.
=> [core-elements] Tabs 컴포넌트를 generic type 으로 변경

packages/core-elements/src/elements/hr/hr.ts, packages/core-elements/src/elements/segment/segment.tsx, packages/core-elements/src/elements/tabs/tab.tsx, packages/core-elements/src/elements/textarea/textarea.tsx, packages/directions-finder/src/ask-to-the-local.tsx, packages/hub-form/src/hub-form.stories.tsx, packages/hub-form/src/hub-form.tsx, packages/poi-detail/src/actions.tsx, packages/poi-list-elements/src/poi-card-element/poi-card-element.tsx, packages/replies/src/list/index.tsx, packages/replies/src/list/not-exist-replies.tsx, packages/replies/src/register.tsx, packages/standard-action-handler/src/image-download.ts, packages/standard-action-handler/src/services/share.ts, packages/triple-document/src/elements/itinerary.tsx, packages/triple-document/src/elements/note.tsx
타입 수정, 일부 core-elements 컴포넌트에 css prop 추가
- export TextareaProps
- (standard-action-handler) IE 호환 제거
- (standard-action-handler) navigator.share -> 'share' in navigator
- (core-elements) hr, segment 컴포넌트에도 margin, padding prop을 제거하고 css Prop을 사용하도록 변경
- (core-elements) Tabs.Tab 컴포넌트에도 Value 제네릭 추가
=> 타입 수정 및 일부 core-elements 컴포넌트에 css prop 추가

packages/app-installation-cta/src/elements.tsx, packages/app-installation-cta/src/floating-button-cta.stories.tsx, packages/replies/src/replies.tsx, packages/review/src/components/review-placeholder-with-rating.tsx
styled.attrs로 스타일되었던 props를 css로 변경
- styled.attrs로 스타일되었던 props를 css로 변경
- app-installation-cta / floating-button-cta가 모바일 사이즈에서만 보이기 때문에 chromatic.viewports 값을 설정합니다.
=> styled.attrs로 스타일되었던 props를 css로 변경

package-lock.json, packages/directions-finder/package.json, packages/directions-finder/tsconfig.build.json, packages/location-properties/package.json, packages/location-properties/tsconfig.build.json, packages/poi-detail/package.json, packages/poi-detail/tsconfig.build.json, packages/replies/package.json, packages/replies/tsconfig.build.json, packages/router/package.json, packages/router/tsconfig.build.json, packages/ui-flow/package.json, packages/ui-flow/tsconfig.build.json
@titicaca/react-triple-client-interfaces를 peer dependency로 변경
@titicaca/react-triple-client-interfaces에서 global provider를 사용하기 때문에 @titicaca/react-contexts 처럼 peer dependency 로 설치해야 context를 정상적으로 사용할 수 있습니다.
=> @titicaca/react-triple-client-interfaces를 peer dependency로 변경

packages/core-elements/src/elements/tabs/pointing-tab-list.tsx, packages/core-elements/src/elements/tabs/pointing-tab.tsx, packages/core-elements/src/elements/tabs/rounded-tab-list.tsx
Tabs에서 발생하는 non-boolean attributes warning 수정
Tabs에서 styled 컴포넌트에 전달하는 props를 transient prop으로 변경해서 warning을 해결합니다.
=> [core-elements] Tabs에서 발생하는 non-boolean attributes warning 수정

packages/core-elements/src/elements/tabs/basic-tab.tsx, packages/core-elements/src/elements/tabs/pointing-tab-context.tsx, packages/core-elements/src/elements/tabs/pointing-tab.tsx, packages/core-elements/src/elements/tabs/rounded-tab-list.tsx, packages/core-elements/src/elements/tabs/rounded-tab.tsx, packages/core-elements/src/elements/tabs/tab-base.tsx, packages/core-elements/src/elements/tabs/tab-list.tsx, packages/core-elements/src/elements/tabs/tab-panel.tsx, packages/core-elements/src/elements/tabs/tab.tsx, packages/core-elements/src/elements/tabs/tabs-context.tsx, packages/core-elements/src/elements/tabs/tabs.tsx
- tabs 컴포넌트에 generic이 빠졌던 부분 추가 및 타입 제한을 추가했습니다.
- https://github.com/titicacadev/triple-frontend/blob/59f73e6647e56bae04d8254782c23a49ae703d9d/packages/core-elements/src/elements/tabs/pointing-tab-context.tsx#L6
- Record의 key 타입이 `string | number | symbol`로 제한되어 있어서 extends로 추가했습니다. 
- 카나리 적용해보니 잘되긴 하는데 타입이 점점 거대해지네요...
=> [core-elements] tabs 컴포넌트 generic type 보완

packages/chat/src/chat/chat.tsx
- 처음 대화하는 채팅일 경우 room이 존재하지 않아 메시지 조회를 하게 되면 undefined로 호출해 500 에러가 발생하는 것을 수정합니다.
- [관련 스레드](https://titicaca.slack.com/archives/CEEPB4TDY/p1673252610679029)
- https://github.com/titicacadev/triple-chat-web/pull/127
- triple-chat-web의 서버사이드 부분과 chat 컴포넌트 부분에 api 가 중복 호출되고 있어 해당 부분 수정했습니다. 
- server side에서 api 호출을 빼는 방법도 있는데 우선 분기처리로 추가했습니다.
=> fix: 초기 메시지가 prop으로 있을 경우 api 호출하지 않도록 수정

packages/action-sheet/src/action-sheet-item.tsx
TF 12버전을 적용한 후로, 라운지 상세 페이지에서 삭제하기가 정상적으로 동작하지 않는 이슈가 있습니다.
원인으로봤을 때에는, replace와 back이 동시에 이뤄지다보니 모달이 제대로 노출이 안되는 것으로 추정됩니다.
이전에 정의했던 조건이 위의 이슈를 막기 위한 것으로 보입니다.
[관련 스레드](https://titicaca.slack.com/archives/C02UED2AZAP/p1673859332257259?thread_ts=1673859074.038389&cid=C02UED2AZAP)
액션시트아이템에 정의한 클릭이벤트의 조건을 롤백합니다.
=> 액션시트 아이템의 클릭 이벤트 조건을 수정합니다.

packages/core-elements/src/elements/accordion/accordion.stories.tsx, packages/core-elements/src/elements/button/button.stories.tsx, packages/core-elements/src/elements/checkbox/checkbox-group.stories.tsx, packages/core-elements/src/elements/checkbox/checkbox.stories.tsx, packages/core-elements/src/elements/container/container.stories.tsx, packages/core-elements/src/elements/drawer/drawer.stories.tsx, packages/core-elements/src/elements/flex-box/flex-box.stories.tsx, packages/core-elements/src/elements/label/label.stories.tsx, packages/core-elements/src/elements/long-clickable/long-clickable.stories.tsx, packages/core-elements/src/elements/navbar/navbar.stories.tsx, packages/core-elements/src/elements/radio/radio-group.stories.tsx, packages/core-elements/src/elements/radio/radio.stories.tsx, packages/core-elements/src/elements/rating/rating.stories.tsx, packages/core-elements/src/elements/section/section.stories.tsx, packages/core-elements/src/elements/spinner/spinner.stories.tsx, packages/core-elements/src/elements/stack/stack.stories.tsx, packages/core-elements/src/elements/sticky-header/sticky-header.stories.tsx, packages/core-elements/src/elements/table/table.stories.tsx, packages/core-elements/src/elements/tooltip/tooltip.stories.tsx
[core-elements] story title을 소문자로 변경
core-elements 패키지의 story title이 `Core-Elements`인 것과 `core-elements` 인 것이 섞여있어서 chromatic에서 섹션이 두개로 구분되고 있습니다.
소문자로 통일해서 하나로 합쳐지게 합니다.
=> [core-elements] story title을 소문자로 변경

packages/poi-detail/src/actions.stories.tsx
[poi-detail] Actions 스토리가 빌드마다 변경되는 현상 수정
툴팁이 한번만 노출되도록 제어하기 위해서 내부에서 local storage를 사용하는데 빌드마다 스토리 3개 중 한개만 노출되고 툴팁이 노출되는 스토리가 일정하지 않습니다. decorator에서 local storage를 강제로 false로 설정해서 항상 툴팁이 노출되도록 합니다.
=> [poi-detail] Actions 스토리가 빌드마다 변경되는 현상 수정

packages/directions-finder/src/ask-to-the-local.tsx, packages/poi-detail/src/recommended-articles/recommended-articles.tsx
관련 스레드: https://titicaca.slack.com/archives/CEEPB4TDY/p1673512116458689?thread_ts=1672202321.110669&cid=CEEPB4TDY
TF [RecommendedArticles](https://github.com/titicacadev/triple-frontend/blob/main/packages/poi-detail/src/recommended-articles/recommended-articles.tsx#L118) 의 경우와 같이, [Section](https://github.com/titicacadev/triple-frontend/blob/main/packages/core-elements/src/elements/section/section.tsx) 컴포넌트에 css prop으로 마진값을 주는 경우 [Section 컴포넌트에서 사용하는 Container 에 적용된 centered 속성](https://github.com/titicacadev/triple-frontend/blob/main/packages/core-elements/src/elements/section/section.tsx#L21)이 덮어씌워지는 버그를 수정합니다 (mixin prop이 먼저 적용되고 css prop이 이후에 적용되어 mixin prop의 스타일이 덮어씌워지는게 이유인듯 합니다).
=> css prop과 centered prop이 충돌하는 문제 수정

packages/action-sheet/src/action-sheet-body.tsx, packages/action-sheet/src/action-sheet-overlay.tsx
https://titicaca.slack.com/archives/C02UED2AZAP/p1674608190699989
ActionSheet가 열고 닫힐 때 사용되는 usePreventScroll이 일부 브라우저에서(macOS 크롬 등) 비정상적인 layout shift를 유발합니다.
ActionSheet의 css를 변경해서 열고 닫힐 때도 가운데 정렬을 유지할 수 있도록 수정합니다.
https://user-images.githubusercontent.com/11497500/214770600-ff88ff18-b521-4602-b317-c079e607595d.mov
=> [action-sheet] 액션시트 열고 닫히는 transition이 일부 브라우저에서 layout shift 되지 않도록 수정

packages/action-sheet/src/action-sheet-base.tsx, packages/modals/src/modal/modal-base.tsx
- @react/aria에서 리랜더를 유발하는 usePreventScroll를 제거합니다.
- [관련 컨플루언스 문서](https://titicaca.atlassian.net/wiki/spaces/dev/pages/3287122066/triple-frontend+12+UI)
- ios 모바일에서만 발생하기 때문에 preventScrollMobileSafari에서 스크롤을 막으면서 document에 event를 넣고 있어서 리랜더가 발생해 버리는 게 아닐까 싶네요 [코드 링크](https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/overlays/src/usePreventScroll.ts#L106)
- useOverlay는 리랜더는 유발하지 않고 onClose를 가지고 실행하는 부분이 있어서 여기서 여행기 삭제 오류로 이어지는 것 같습니다. 
- 이전버전 확인해보면 scroll 막는것은 기존에 있던 기능은 아닌 것 같아서 우선은 제거하고 이슈 등록 후 다시 살펴보겠습니다. 
trips-web 적용버전
- https://triple-dev.titicaca-corp.com/trips/lounge/itineraries/d626a7ae-04cf-4368-93a1-bb772d2a3fdd?_triple_no_navbar&_safe_area_bottom
- https://triple-dev.titicaca-corp.com/trips/intro
=> [action-sheet, modals] @react/aria에서 리랜더를 유발하는 usePreventScroll 제거

packages/poi-detail/src/actions.tsx
POI 상세페이지 `Actions`컴포넌트 하단에서 사용되는 `<HR1>`에 넘기는 margin css prop값을 수정하여 `<HR1>`컴포넌트에 기본값으로 적용된 `margin: 50px 30px`에 의해 `<HR1>`의 너비가 줄어드는 현상을 해결합니다.
|As-is|To-be|
|-|-|
|<img width="333" alt="스크린샷 2023-02-01 오전 11 56 33" src="https://user-images.githubusercontent.com/50892653/215936086-61bace96-4857-4c48-a31a-9211745886ec.png">|<img width="334" alt="스크린샷 2023-02-01 오전 11 59 01" src="https://user-images.githubusercontent.com/50892653/215936116-4629adc6-e702-4312-bdd5-6d58687b3e68.png">|
=> [poi-detail] POI 상세페이지에서 사용되는 Actions 컴포넌트 하단 HR1 너비를 수정합니다.

packages/review/src/components/review-element/index.tsx, packages/review/src/components/types.tsx, packages/review/src/services/generated/query.ts
리뷰 개수를 표시할 때 아래 사진의 파트너 댓글과 같은 `pinned message`(연회색 백그라운드)도 포함하여 표시하도록 수정합니다.
=> [review] 댓글 개수를 표시할 때 pinned message도 포함하여 표시합니다.

packages/action-sheet/src/action-sheet-base.tsx, packages/action-sheet/src/action-sheet-body.tsx, packages/modals/src/modal/modal-base.tsx
underlayProps, overlayProps, FocusScope 위치 변경
- useOverlay의 underlayProps, overlayProps의 위치를 서로 바꿉니다. underlay가 뒷 배경, overlay가 그 위에 떠 있는 요소를 의미합니다. (https://react-spectrum.adobe.com/react-aria/useModalOverlay.html)
- FocusScope를 base 쪽으로 옮깁니다. body를 시각적인 ui만 담당하게 하고 base가 포커스같은 기능을 담당하도록 합니다.
=> underlayProps, overlayProps,  FocusScope 위치 변경

.eslintrc.js, packages/view-utilities/src/url.spec.ts, packages/view-utilities/src/url.ts
- parsedQuery 값 중 특정 key값을 추출하는 함수를 생성합니다. ([관련 스레드](https://titicaca.slack.com/archives/C8QE1TG95/p1673421773309249?thread_ts=1673325610.004569&cid=C8QE1TG95))
```typescript
// AS-IS
const parsedQuery = {
_web_expand: 'true',
triple_link_param_item_id: '123-1234',
skipInitialCache: 'true',
triple_link_param_content_type: 'air',
_triple_no_navbar: '',
triple_link_param_button_name: 'japan-low-price-air-ticket',
}
// TO-BE
const result = {
triple_link_param_item_id: '123-1234',
triple_link_param_content_type: 'air',
triple_link_param_button_name: 'japan-low-price-air-ticket',
}
```
=> [view-utilities] parsedQuery의 특정 key 값을 추출하는 함수를 생성합니다.

packages/i18n/src/assets/ja/common-web.ts, packages/i18n/src/assets/ko/common-web.ts, packages/i18n/src/assets/zh/common-web.ts, packages/listing-filter/src/index.tsx, packages/review/src/components/review-container.tsx, packages/review/src/components/sorting-options.tsx
- content-web의 ui renewal 디자인 개선사항을 수정합니다. ([피그마](https://www.figma.com/file/qlovwieZox6DTlEP8CqeVY/20230201_%EA%B0%9C%EB%B0%9C-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8-%EC%95%84%ED%8B%B0%ED%81%B4-%EA%B2%80%EC%88%98?node-id=0%3A1&t=VAFHdmLO9R4oDXry-0))
- `ListingFilterEntry`가 active 일 때 텍스트를 볼드 처리합니다.
- 리뷰의 '추천순', '최신순' `SortingOptions`의 텍스트를 볼드 처리합니다.
- 리뷰의 shorten 버전에서 리뷰의 개수가 0일 때 타이틀이 노출되지 않아 레이아웃이 깨지는 현상을 수정합니다.
|as-is|to-be|
|----|----|
|<img width="400" alt="_______________________________2023-02-03______________3 51 09" src="https://user-images.githubusercontent.com/37494848/216537587-4973ffc1-70fb-4074-a30d-f8b2be995b14.png">|<img width="400" alt="_______________________________2023-02-03______________3 52 38" src="https://user-images.githubusercontent.com/37494848/216537599-b33ac464- …
=> [review, listing-filter] ui-renewal 디자인 개선사항을 수정합니다.

packages/chat/src/chat-bubble/bubble-payload.tsx, packages/core-elements/src/elements/checkbox/checkbox-group.stories.tsx, packages/react-contexts/src/images-context/images-context.stories.tsx
더 적절한 의존성 사용
- [chat] 같은 패키지에서 import path는 relative path를 사용합니다.
- [core-elements] useState를 @storybook/addons 대신 react에서 import 합니다.
- [react-contexts] core-elements 의존성이 없어서 Button 컴포넌트를 뺍니다.
=> 더 적절한 의존성 사용

packages/triple-header/src/triple-header.tsx
아티클 상세에서 트리플 헤더를 추가했을 때, 레이아웃 쉬프트가 발생합니다. 
- 트리플 헤더를 렌더링할 때 다수의 이미지를 호출하며 영역 비율 계산하기 때문에 본문 영역에 비해 오래 걸립니다.
트리플 헤더가 들어갈 공간을 미리 확보해서, 레이아웃 쉬프트가 발생하는 시간을 줄입니다.
CLS 성능 테스트
- 네트워크 속도 등 다양한 요인으로 인해 매번 측정되는 시간이 다릅니다.
1. 0.857s -> 0.166s (`80.63%` 감소)
2. 0.857s -> 0.284s (`66.86%` 감소)
3. 0.858s -> 0.519s (`39.43%` 감소)
-> **평균: `62.30%` 감소**
=> [triple-header] layout shift 를 개선합니다.

packages/review/src/components/review-container.tsx, packages/review/src/services/generated/query.ts, packages/review/src/services/use-reviews.ts
[관련 스레드](https://titicaca.slack.com/archives/C01CHRQBP1U/p1676253558034269)
`최근 여행` 리뷰의 개수가 5개 이상임에도 불구하고, `리뷰 더보기` 버튼이 무조건 `1개 리뷰 더보기` 로 표시되는 버그를 수정합니다.
최근 여행 리뷰의 경우, `getLatestReviews` graphql 쿼리를 통해 가져오는 데이터(`reviewsData`) 배열의 길이를 이용하여 리뷰 개수를 표시하고 있었습니다. 이때, `getLatestReviews` 쿼리에 인자로 넘기는 `size`의 값이 5로 설정되어 있어 5 - 4(한 페이지에 보여주는 리뷰 개수 디폴트값) = 1이 되어 최근 여행의 경우 항상 `1개의 리뷰 더보기` 로 표시되는 버그가 있었습니다.
따라서 (기존에도 잘 동작하던) 최근 여행이 아닌 리뷰와 마찬가지로, 최근 여행 리뷰 개수를 표시할 때 [getReviewsCount](https://triple-dev.titicaca-corp.com/api/graphql?query=%7B%0A++getReviewsCount%28resourceType%3A+%22poi%22%2C+resourceId%3A+%2207c94508-bcad-48fb-9b0e-b17bea8a547f%22%2C+recentTrip%3A+true%29%0A%7D%0A) 쿼리를 통해 리뷰 개수를 표시하도록 수정합니다.
=> [review] 최근여행 리뷰 개수 표시 오류를 수정합니다.

packages/core-elements/src/elements/image/optimized-img.tsx, packages/intersection-observer/src/lazy-loaded-intersection-observer.tsx, packages/scroll-spy/src/index.test.tsx, packages/scroll-spy/src/index.tsx
[관련 스레드](https://titicaca.slack.com/archives/CEEPB4TDY/p1676354386689769)
([React Hydration Error](https://nextjs.org/docs/messages/react-hydration-error)의 원인이기도 한) lazy load IntersectionObserver를 deprecate 처리하고 `StaticIntersectionObserver`를 대신 사용합니다.
=> Lazy load IntersectionObserver를 deprecate 합니다.

packages/ui-flow/src/auth-guard/index.test.ts, packages/ui-flow/src/auth-guard/index.ts
- `authGuard`의 `refreshInAppSession` 실행조건을 수정합니다.
- `refreshInAppSession`은 앱에서 이미 로그인되어있지만 토큰값이 깨진 경우에만 실행되어야 합니다. 
- 따라서 `x-soto-session` 값의 유무를 판별해 주는 `getSessionAvailabilityFromRequest`가 `true`일 경우만 landing web(refreshInAppSession)으로 이동할 수 있도록 합니다.
- 앱에 해당하는 테스트코드를 변경합니다. 
- auth-web에서 app일 경우 접근을 막는 방어코드를 작성했습니다. https://github.com/titicacadev/triple-auth-web/pull/236
=> [ui-flow] authGuard의 refreshInAppSession 실행조건을 수정합니다.

packages/meta-tags/README.md, packages/meta-tags/src/theme-color-meta.tsx
- ThemeColorMeta의 기본 props color를 `#1FC1B6`으로 변경합니다.(사유: [common-meta](https://github.com/titicacadev/triple-frontend/blob/main/packages/meta-tags/src/common-meta.tsx#L16)의 기본값과 색상을 통일하기 위함)
- README의 내용을 일부 수정합니다.(기본값 변경)
=> [meta-tags] ThemeColorMeta의 기본 props color와 README를 일부 수정합니다.

packages/triple-header/src/frame/effects/common.ts, packages/triple-header/src/frame/effects/flying.tsx
날아오기 효과의 속도를 조절합니다.
[관련 스레드](https://titicaca.slack.com/archives/C0J3TT1H8/p1675652416306319?thread_ts=1665985693.829549&cid=C0J3TT1H8)
- 3000ms -> 300ms
=> [triple-header] 트리플헤더 날아오기 효과의 속도를 변경합니다.

packages/ab-experiments/src/triple-ab-experiment-context/context.tsx
[A/B 테스팅 그룹 요청 API에 비로그인 && 웹 요청을 허용합니다 PR](https://github.com/titicacadev/triple-user/pull/343)에서 비로그인 사용자에 대한 A/B 테스팅을 지원하는 기능이 추가되었으므로, `TripleABExperimentProvider`에서 CSR 시점에 A/B테스트 메타데이터를 가져올 때 세션 체크를 하지 않도록 수정합니다.
=> [ab-experiments] CSR 방식으로 A/B테스트 메타데이터를 가져올 때 세션 유무는 체크하지 않도록 합니다.

package-lock.json, package.json, packages/ad-banners/src/content-details-banner.tsx, packages/ad-banners/src/list-top-banners.tsx, packages/core-elements/src/elements/tabs/tab-base.tsx, packages/core-elements/src/elements/tabs/tab-panel.tsx, packages/modals/src/login-cta-modal.tsx, packages/react-contexts/src/event-tracking-context/with-event-tracking-provider.tsx, packages/replies/src/reply.test.tsx, packages/router/src/href-to-props/use-href-to-props.ts, packages/scrap-button/src/scrap-button-mask.tsx, packages/scrap-button/src/scrap-button.tsx, packages/web-storage/src/storage.ts, packages/web-storage/src/utils.ts
- Typescript 최신버전을 적용하고 그에 따른 타입에러를 수정합니다.
- Issue: close #2337
=> Typescript 최신버전 적용 및 타입에러 수정

packages/footer/src/award-footer.tsx, packages/footer/src/default-footer.tsx
styled-component 로 커스텀 리액트 컴포넌트 스타일링을 가능하도록 하기 위한 className 속성 추가
참고 : https://styled-components.com/docs/basics#styling-any-component
```javascript
/** @example */
<Footer css={{ paddingBottom: '200px' }} />
```
+ default-footer 에서 `className` 전달하도록 변경
=> Default Footer 에서 css 속성 사용 가능하도록 수정

packages/core-elements/src/elements/input/input.tsx, packages/core-elements/src/elements/select/select.tsx, packages/core-elements/src/elements/textarea/textarea.tsx
https://titicaca.atlassian.net/browse/TFC-12
Input, Textarea, Select의 border-radius를 기존 2px에서 4px로 변경
=> Input, Select, Textarea border-radius 변경

packages/core-elements/src/elements/select/select.tsx, packages/pricing/src/fixed-pricing.tsx
TF12에서 발생한 스타일 에러를 수정합니다.
1. Select 컴포넌트를 `div` -> `select` 태그로 수정하면서, ios 환경에서 기본 background-color(회색)가 적용되기에 배경색을 통일합니다.
2. fixed-pricing에서 top, left, right padding이 적용되지 않는 문제를 해결합니다.
=> Select, fixed-pricing 스타일 버그 픽스

packages/view-utilities/src/routelist/routelist.ts
`PUBLIC_ROUTELIST_REGEXES`에 여행기 상세 주소를 추가하여 여행기 웹뷰 이동 시 로그인 모달을 띄우지 않게 합니다.
=> PUBLIC_ROUTELIST_REGEXES에 여행기 상세 주소 추가

package-lock.json, packages/action-sheet/package.json, packages/action-sheet/src/action-sheet-body.tsx, packages/action-sheet/src/action-sheet-context.tsx, packages/action-sheet/src/action-sheet-overlay.tsx, packages/action-sheet/src/action-sheet.tsx, packages/core-elements/package.json, packages/core-elements/src/elements/drawer/drawer.tsx, packages/drawer-button/src/index.tsx, packages/popup/package.json, packages/popup/src/index.tsx
react-transition-group -> headlessui Transition 으로 변경
react-transition-group이 최초 Mount 될 때 애니메이션을 트리거하지 못하고 있습니다.
headlessui의 Transition 컴포넌트로 변경해서 애니메이션이 항상 트리거 되도록 변경합니다.
=> react-transition-group -> headlessui Transition 으로 변경

packages/triple-media/src/index.tsx
- 이미지 여백 제거를 위해 display: block 속성을 추가합니다.
- [관련 스레드](https://titicaca.slack.com/archives/CEEPB4TDY/p1678248648487349)
- TripleDocument에서 이미지 사이에 생기는 여백을 제거하기 위해 `TripleMedia`의 `Image.Img` 컴포넌트에 `display: block` 속성을 추가했습니다.
- chromatic: https://617b7c4431c922004a42c7cc-vkwqfrrnhh.chromatic.com/?path=/story/triple-document-tripledocument--sample
=> [triple-media] 이미지 여백 제거를 위해 display: block 속성 추가

packages/modals/src/modal/modal.tsx
https://titicaca.atlassian.net/browse/TFC-50
Modal 내부에서 position: fixed인 요소를 그릴 수 있도록 Container의 borderRadius를 사용하지 않고 css에 직접 border-radius를 사용해서 `webkit-mask-image` 속성을 제거합니다.
=> [modals] Panel에 webkit-mask-image 속성 제거

packages/react-triple-client-interfaces/README.md, packages/react-triple-client-interfaces/src/triple-client-metadata-context.tsx
static page의 경우 서버사이드의 User-Agent 값을 가져오지 못하므로 TripleClientMetadataContext에 shouldUpdateUserAgentOnMount 플래그를 추가합니다.
스테틱 페이지의 경우 useEffect를 통해 클라이언트에서 window.nagivation의 userAgent 값을 읽어옵니다.
- 사용방법 : 스테틱 페이지의 `getStaticProps`의 리턴 객체에 `shouldUpdateUserAgentOnMount `를 true로 설정하고, _app.tsx 파일에서 TripleClientMetadataContext의 props로 appContext.pageProps.shouldUpdateUserAgentOnMount를 추가하면 됩니다.
```tsx
// pages/example.tsx
interface PageProps {
isStaticPage: boolean
}
export default function ExampleComponent(props: PageProps) {
return <div>example</div>
}
export async function getStaticProps() {
return {
isStaticPage: true,
}
}
// _app.tsx
function MyApp({
Component,
pageProps,
tripleClientMetadataProviderProps,
}: AppProps & CustomAppProps) {
return (
<TripleClientMetadataProvider …
```
=> TripleClientMetadataContext에 `shouldUpdateUserAgentOnMount` props를 추가합니다

packages/core-elements/src/elements/input/input.stories.tsx, packages/core-elements/src/elements/list/list.stories.tsx, packages/core-elements/src/elements/list/list.test.tsx, packages/core-elements/src/elements/list/list.tsx
List 컴포넌트에 `marker` 를 노출할 수 있는 props 을 추가합니다.
기본 `disc marker` 대신 스타일 커스텀이 용이한 pseudo-element 로 추가했습니다.
해당 List 를 이용해서 `Input` 에 다중 도움말 문구를 노출하는 케이스를 추가합니다.
[JIRA](https://titicaca.atlassian.net/browse/TFC-13)
+ `List` 컴포넌트에 `marker` 속성 추가
+ `List` 유닛 테스트 추가
+ `Input` 컴포넌트 스토리 파일에 `multiline-help` 케이스 추가
적용 예시
=> List 에 marker prop 을 추가합니다.

.github/workflows/pr-closed.yaml
ci: delete-tag-and-release 버전 수정
PR Closed job이 실패하고 있습니다. https://github.com/titicacadev/triple-frontend/actions/runs/4506894128/jobs/7934157788
이 job에서 쓰고 있는 delete-tag-and-release 액션이 0.2.1 미만 버전을 모두 지워버려서 버전을 찾을 수 없는 문제입니다. 버전을 0.2.1로 수정합니다.
https://github.com/dev-drprasad/delete-tag-and-release/issues/20
=> ci: delete-tag-and-release 버전 수정

packages/react-triple-client-interfaces/package.json
[react-triple-client-interfaces] package.json에 url 추가
renovate가 react-triple-client-interfaces 패키지도 triple-frontend 모노레포에 포함된다고 인식할 수 있도록 package.json에 url 관련 필드를 추가합니다.
=> [react-triple-client-interfaces] package.json에 url 추가

.github/workflows/add-label.yaml, .github/workflows/update-changelog.yaml
GHA를 이용하여 기존에 마일스톤을 참고해서 수동으로 `CHANGELOG`를 작성하는 과정을 자동화합니다.
로컬에서 릴리즈 브랜치(`release/v1.2.3`)를 만들고 `npm run version`을 통해 새로운 버전으로 올린다음 `CHANGELOG`를 작성할 필요 없이, 릴리즈 PR을 오픈하면 GHA가 자동으로 릴리즈 PR이 등록된 마일스톤에 있는 _머지된_ PR들을 참고하여 `CHANGELOG`를 작성합니다.
릴리즈 PR을 오픈할 때 `release` 라벨과 마일스톤을 지정해주어야 GHA가 정상적으로 작동합니다. 마일스톤에 있는 PR 중에 라벨이 달려있지 않거나 머지되지 않은 PR은 `CHANGELOG` 작성 대상에서 제외됩니다.
변경된 파일들의 경로를 읽어 해당 PR이 어느 패키지를 변경했는지 파악하여 변경된 패키지 이름에 맞는 라벨을 부착하는 GHA를 추가합니다. 예를 들어, 어떤 PR이 `ab-experiments`와 `action-sheet`를 변경한 경우 해당 PR에 `ab-experiments`, `action-sheet` 라벨을 부착합니다. 패키지 변경 사항(`packages`로 시작하는 디렉토리)만 확인하며, `.storybook`, `package.json`과 같이 패키지 이외의 변경사항은 확인하지 않습니다.
https://github.com/titicacadev/triple-frontend/pull/2521 PR에서 작동 예시를 보실 수 있습니다!
`ab-experiments`, `core-elements` 패키지를 수정해서 그에 맞는 라벨이 자동으로 부착되었으며, 패키지 이외의 …
=> CHANGELOG 자동화를 구현합니다.

packages/modals/src/alert/alert.tsx, packages/modals/src/confirm/confirm.tsx
- Confirm.body에 css를 적용 할 수 있게 props를 추가합니다.
=> [ Modals ] Confirm body에 css prop을 추가합니다.

.github/workflows/add-label.yaml, .github/workflows/update-changelog.yaml
- renovate PR을 라벨 자동화 대상에서 제외합니다.
- 깃헙 API를 이용하여 PR 목록을 가져올 때 최대 100개를 가져오도록 합니다 (기존 30개)
=> CHANGELOG 자동화를 개선합니다.

package-lock.json, packages/app-installation-cta/package.json, packages/app-installation-cta/src/elements.tsx, packages/app-installation-cta/src/floating-button-cta.tsx, packages/app-installation-cta/tsconfig.json
[관련 스레드](https://titicaca.slack.com/archives/CE1TS26GK/p1681117980027519?thread_ts=1672730534.784689&cid=CE1TS26GK)
플로팅 A/B 테스팅 결과, 기존의 v1 버전(파란색) 플로팅 버튼을 사용하기로 하여 플로팅 버튼 디자인을 v1 버전으로 되돌립니다.
https://github.com/titicacadev/triple-frontend/pull/2262 요 PR을 참고했습니다.
=> 플로팅 버튼 디자인을 v1 버전으로 되돌립니다

package-lock.json, packages/triple-email-document/package.json, packages/triple-email-document/src/elements/links.tsx, packages/triple-email-document/src/links.stories.tsx, packages/triple-email-document/src/triple-email-document.tsx, packages/triple-email-document/tsconfig.json
해당 로직은 다음과 같은 사이드 이펙트가 있어서 롤백합니다.
- 뉴스레터에 삽입되는 아티클의 링크가 도시 메인(앱 딥링크)일 경우 랜딩이 안되는 이슈가 있습니다.
배경 지식
- 아티클 어드민에 삽입되는 링크는 WEB_URL_BASE이 아니라 APP_URL_BASE 기준입니다.
변환 로직은 newsletter-api 에서 관리합니다. (관련 [PR](https://github.com/titicacadev/triple-newsletter-api/pull/39))
https://github.com/titicacadev/triple-frontend/pull/2559 롤백
=> [triple-email-document] 링크 Element에 존재하는 URL 변환하는 로직을 제거합니다.

packages/review/src/components/review-element/pinned-message.tsx, packages/review/src/components/types.tsx, packages/review/src/services/generated/query.ts
pinnedMessage의 인터페이스가 변경에 대응합니다.
`replyBoard.pinnedMessage.content.text` 필드에 먼저 접근하여 `text` 필드가 있으면 `text` 필드값을 보여주고, 없으면 기존처럼 `markdownText` 값을 보여줍니다.
=> PinnedMessage의 text 필드를 추가합니다.

.github/workflows/update-changelog.yaml, scripts/changelog.js
기존 방식에선 GHA에 의해 자동으로 작성된 CHANGELOG가 커밋/푸쉬되면 CI가 정상적으로 돌았음에도 불구하고 아래 사진과 같이 깃헙에서 이를 인지하지 못하게되는 오류가 있었습니다.
(비교: 체크가 정상적으로 동작한경우)
이를 해결하기 위해, GHA에서 `actions/checkout@v3`를 실행할 때 `TRIPLE_BOT_GITHUB_TOKEN`을 이용하여 checkout하도록 수정했습니다. (-> https://stackoverflow.com/questions/52200096/github-pull-request-waiting-for-status-to-be-reported/69169858#69169858 참고)
그 외 변경사항으로, `COMMIT_USER_EMAIL`, `COMMIT_USER_NAME` env 변수값 등을 수정하고, 이모지를 제거하는 로직을 삭제하고 그 대신 라벨에 붙어있던 이모지들을 제거했습니다.
=> CHANGELOG 자동화 로직을 수정합니다.

packages/router/src/local/href-handler.ts, packages/router/src/local/link.tsx
- LocalLink에서 `target: current`인 경우 [shallow routing](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#shallow-routing) property를 추가합니다.
- [통합검색 - 인기 검색어](https://www.figma.com/file/Va0p9Eoaire2lKjQFqK3lG/20230215_%ED%86%B5%ED%95%A9%EA%B2%80%EC%83%89?type=design&node-id=836-79230&t=IvoZGnggjSPDV5cT-4)에서 [Text](https://github.com/titicacadev/triple-frontend/blob/main/packages/core-elements/src/elements/text/text.tsx)에 shallow routing이 필요한데, 이때 `onClick` 함수에 `router.push + shallow`를 선언하는 것보다 `LocalLink`를 이용하는 편이 구현하기 간단하고 사용 목적과 부합하여 추가하게 되었습니다.
=> [ Router ] LocalLink 컴포넌트에 shallow property를 추가합니다.

CHANGELOG.md, scripts/changelog.js
ChatGPT로 CHANGELOG를 작성할 때, PR 링크가 TF가 아니라 제 개인 레포의 링크로 작성되던 이슈를 수정합니다.
요걸 사전에 발견했었어야 하는데 죄송합니다 ㅠㅠ 🙇
=> CHANGELOG 작성 시 PR url이 잘못 달리던 버그를 수정합니다.

packages/footer/src/company-info.tsx
Footer 내 '로그인/로그아웃' 링크(`a`)가 href가 아닌 onClick으로 동작하고 있어 `hover` 시 포인터 커서 누락 및 탭으로 접근이 불가능 하여 `button` 태그로 렌더될 수 있도록 수정했습니다.
=> [Footer] 로그인 버튼 a -> button으로 수정

packages/meta-tags/src/article-script.tsx, packages/meta-tags/src/utils.ts
- [meta-tag] 태그 컴포넌트에 입력한 date props가 올바른 date 형식이 아닐 경우 undefined를 리턴하도록 validation을 추가합니다.
- toISOString 함수에서 date에 대한 validation을 추가하도록 수정합니다.
- FilterValidValue 함수의 인자가 제대로 디스트럭쳐링되지 않는 문제를 수정합니다.
- [뉴스레터 dev 배포](https://triple-dev.titicaca-corp.com/newsletter/articles/ae9ccb2b-bfd6-4b6c-a578-2ebf0f378eed)
=> [meta-tags] article script의 date 형식에 validation을 추가합니다.

packages/modals/src/modal/modal-actions.tsx, packages/modals/src/modal/modal.stories.tsx, packages/modals/src/modal/modal.tsx
https://titicaca.slack.com/archives/CA3QE80QL/p1682994720830179
- 기기 설정에서 폰트 사이즈가 크게 설정되어 Modal의 height가 기기 해상도보다 크게 늘어날 경우 Modal을 스크롤할 수 있도록 합니다. 
https://github.com/titicacadev/triple-frontend/assets/11497500/5dbc123b-7619-434b-a4f7-74dc055dfa86
=> [modals] Modal height가 스크린 높이보다 커도 스크롤 가능하도록 수정

packages/triple-document/src/elements/tna/product.tsx, packages/triple-document/src/mocks/slots.sample.json
- [관련 스레드](https://titicaca.slack.com/archives/C9WMUE9DX/p1684910046265049)
- 표시가보다 판매가가 큰 경우 할인율과 표시가가 미노출되도록 수정합니다.
- 할인율이 마이너스 퍼센트로 표시되는 현상을 수정하기 위해 `할인율과 표시가` 표시 조건을 수정합니다. 
- as-is
- to-be
=> [triple-document] 표시가보다 판매가가 큰 경우 할인율과 표시가가 미노출되도록 수정합니다.

packages/review/src/components/review-element/index.tsx, packages/review/src/components/reviews-list.tsx, packages/ui-flow/src/use-app-callback.ts
리뷰 더보기 UX 개선했습니다. 
- [지라](https://titicaca.atlassian.net/browse/TFC-97)
- [리뷰개선 기획 위키](https://titicaca.atlassian.net/wiki/spaces/BUS/pages/3164471344) 
- 관련 레포지토리
- tna-web-v2 https://github.com/titicacadev/tna-web-v2/pull/1310
- triple-content-web https://github.com/titicacadev/triple-content-web/pull/1152
- triple-hotels-web https://github.com/titicacadev/triple-hotels-web/pull/2921
- triple-reviews-web https://github.com/titicacadev/triple-reviews-web/pull/166
- '더보기' 클릭 시 이벤트 버블링으로 인해 '리뷰 내용' 클릭 액션이 트리거 되어 리뷰 상세페이지로 이동하던 부분을 수정해 주었습니다. 
- '리뷰 내용'을 클릭하여 리뷰 상세페이지로 이동 시 더보기가 해제되도록 했습니다. 
- TNA 웹 dev 환경에서 확인할 수 있습니다. [[예시 링크](https://triple-dev.titicaca-corp.com/tna/products/0dfbd6fe-6d4f-4168-8e61-a3392a703aee?type=REGION&regionId=3fc342f5-1900-4352-a35c-91080632dbe7&from=hub&openerId=AA …
=> [TFC-97] 호텔 리뷰 개선 - 더보기 UX 개선

.storybook/preview.js, packages/i18n/src/assets/ja/common-web.ts, packages/i18n/src/assets/ko/common-web.ts, packages/i18n/src/assets/zh/common-web.ts, packages/triple-document/src/elements/tna/product.tsx, packages/triple-document/src/mocks/slots.sample.json, packages/triple-document/src/tna-slot.stories.tsx
- [지라](https://titicaca.atlassian.net/browse/TNA-5591)
- msw가 설정되어 있길래 triple-documet의 tna-slot 부분에 적용하고 중복 삭제했습니다.
- 0원일 때 일시품절 텍스트로 노출되도록 수정합니다.
- [dev](https://triple-dev.titicaca-corp.com/attractions/a86a3f55-9f89-4540-a124-f8c4db07ab34)
=> [triple-document] POI 가격 0원 개선 - 0원일 때 일시품절 텍스트로 노출

packages/react-contexts/src/session-context/browser.tsx, packages/react-contexts/src/session-context/user.ts
- `/api/users/me` API 응답 type을 최신화합니다.
- User타입을 type-definitions 패키지로 옮겨 공통화 관리
=> /api/users/me의 타입을 최신화합니다.

packages/triple-document/src/elements/coupon/coupon-download-buttons.tsx, packages/triple-document/src/elements/coupon/index.tsx, packages/triple-document/src/index.ts, packages/triple-document/src/triple-document.stories.tsx
쿠폰 엘리먼트의 구성요소 색상을 변경할 수 있는 옵션을 제공합니다.
- color 옵션이 주어지지 않으면 DEFAULT_COLOR 를 사용합니다.
- coupon 스토리를 추가합니다.
- triple-document 스토리를 CSF3 형식으로 변경합니다.
아티클 어드민 사용 예시
https://github.com/titicacadev/triple-frontend/assets/37819666/ece005f3-eae3-4eb2-a4dc-0cc98a11adb3
=> triple-document 쿠폰 개선

packages/action-sheet/src/action-sheet.test.tsx, packages/modals/src/modal/modal.test.tsx, packages/popup/src/popup.test.tsx
focus trap 테스트가 랜덤하게 실패하는 현상 수정
- floating 컴포넌트에서 initial focus가 설정되는 것은 비동기적인 동작이라서 focus trap 테스트가 랜덤하게 실패하고 있는 것 같습니다.
- role=dialog DOM이 initial focus로 설정되길 기다리도록 waitFor을 추가합니다.
=> focus trap 테스트가 랜덤하게 실패하는 현상 수정

packages/view-utilities/package.json, packages/view-utilities/src/app-directory/client/convert-search-params-to-query.ts, packages/view-utilities/src/app-directory/client/index.ts, packages/view-utilities/src/app-directory/common/index.ts
- view-utilities에 common, client export 경로를 추가합니다. (fetcher에서 사용하는 view-utilities에서 client 모듈이 혼용되는 것을 방지합니다.)
- [app 디렉토리에서 query를 가져오는 방식이 변경됨](https://nextjs.org/docs/app/api-reference/functions/use-search-params)에 따라 next의 searchParams를 기존 query 형태로 변환하는 유틸 함수를 작성했습니다.
=> view-utilities에 common, client export 경로를 추가하고 query 관련 유틸함수를 작성합니다.

packages/triple-document/src/elements/coupon/index.tsx, packages/triple-document/src/elements/coupon/utils.test.ts, packages/triple-document/src/elements/coupon/utils.ts
기획자분들이 HEX 색상코드를 입력하실 때 `#` 을 포함해서 입력하는게 익숙하지 않다고 하셔서 `#` 를 보정해주는 함수를 추가합니다.
=> 쿠폰 색상 HEX fixation 을 지원합니다.

jest.config.js, package-lock.json, packages/react-contexts/package.json
- firebase v9.23.0 이상의 버전에서 fa 이벤트 기록이 누락되는 이슈가 있습니다. react-contexts의 firebase 버전을 v9.15.0으로 다운그레이드합니다. ([제보 스레드](https://titicaca.slack.com/archives/CEEPB4TDY/p1686560433625159))
- jest config 옵션의 deprecated된 타입을 변경합니다. (`InitialOptionsTsJest` -> `JestConfigWithTsJest`)
=> firebase 버전을 v9.15.0으로 다운그레이드합니다.

packages/view-utilities/src/debounce.ts
debounce에 `leading`, `trailing` 옵션을 추가했습니다.
- as-is: `trailing` 으로 동작
- to-be: 세 번째 인자로 `{ leading: boolean, trailing: boolean }` 옵션을 명시하여 debounce 실행 시점을 컨트롤 할 수 있습니다. 기본 옵션은 `{ leading: false, trailing: true }`입니다.
=> feat: debounce에 leading, trailing 옵션 추가

packages/directions-finder/src/ask-to-the-local.tsx
- 현지에서 길묻기의 ellipsis 옵션을 삭제합니다. (말줄임 제거)
- 글자수가 많아질 경우 전화하기 버튼과 글자가 겹치는 것을 방지하기 위해 margin과 background를 추가했습니다.
|as-is|to-be|
|----|----|
|<img width="399" alt="스크린샷 2023-07-31 오후 4 08 34" src="https://github.com/titicacadev/triple-frontend/assets/37494848/268c69f0-5a60-415b-b195-9df4fa58fa7d">|<img width="399" src="https://github.com/titicacadev/triple-hotels-web/assets/37494848/e8da143b-ba54-4df5-804b-a40bc620dad9">|
=> 현지에서 길묻기 ellipsis 옵션 삭제

.github/workflows/add-label.yaml
릴리즈 PR에 대해선 라벨을 자동으로 붙이지 않도록 하기 위해 기존에는 브랜치 이름이 `release/` 로 시작하는지를 검사했으나, PR에 `release` 라벨이 붙어있는지를 검사하는 방식으로 수정합니다.
=> 라벨 부착 자동화 GHA 실행 조건을 수정합니다.

packages/resource-list-element/src/extended-resource-list-element.tsx
호텔 목록에 광고 또는 협찬이 들어오는 호텔을 목록 최상단에 노출해야하는 상황입니다.
기존의 광고 표기 위치와 디자인이 달라서 이를 수정합니다.
[관련 피그마](https://www.figma.com/file/aicFCSpR2wN5q6evH9edRw/20230704_%EC%88%99%EC%86%8C%2FTNA-%EC%83%81%EC%84%B8%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%83%81%EB%8B%A8-%ED%98%9C%ED%83%9D-%EC%98%81%EC%97%AD-%EA%B0%9C%EC%84%A0?node-id=464%3A91627&mode=dev)
호텔웹에 별도로 추가하는 것보다 기존에 있던 props를 이용하는 것이 효율적이라고 판단되어 이와 같이 작업했습니다.
공통 코드를 수정하다보니, 다른 곳에도 영향이 있을 수 있어서 [스레드](https://interpark.slack.com/archives/C05FJFC4HGS/p1692938760318459)에서 로우와 논의 후에 진행했습니다.
AS-IS
TO-BE
=> [resource-list-element] 광고 표기 위치와 디자인을 수정합니다.

packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat/chat.tsx
chat에 disableUnreadCount props를 추가합니다. 해당 props가 true라면
- 메세지 UI에서 메세지 읽음 숫자를 노출하지 않도록 합니다.
- 마지막 메세지 확인 시 last-message API 호출을 하지 않도록 합니다.
=> Chat에 disableUnreadCount props를 추가합니다.

packages/location-properties/src/location-properties.tsx
LocationProperties 액션시트에서 누락된 주소를 복원합니다. i18n 적용하면서 누락된 듯 합니다. ([제보 스레드](https://interpark.slack.com/archives/C05ERUV2603/p1694482363453889))
|as-is|to-be|
|---|---|
|![img_8552](https://github.com/titicacadev/triple-frontend/assets/37494848/ea81662c-ce77-44ae-9031-7350d0ed2cec)|![screenshot_20230913_090327__dev](https://github.com/titicacadev/triple-frontend/assets/37494848/219af45a-0c41-4bf7-a31b-6be2fc34603a)|
=> [LocationProperties] 액션시트에서 누락된 주소를 복원합니다.

packages/chat/src/chat-bubble/chat-bubble-ui.tsx, packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat/chat.tsx
[Chat] 채팅 리트라이 이벤트를 위한 props를 추가합니다.
- 리트라이 버튼 클릭
- 리트라이 취소 버튼 클릭
=> [Chat] 채팅 리트라이 이벤트를 위한 props를 추가합니다.

packages/map/src/map-view.tsx
구글맵에 언어설정을 할 수 있도록 load option 을 추가합니다.
language 를 지정하지 않으면 브라우저에 지정된 사용자 언어 설정값을 사용합니다.
=> 구글맵 load script 언어 옵션 추가

packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-ui/tsconfig.build.json, packages/tds-ui/tsconfig.json, packages/tds-widget/package.json, packages/tds-widget/tsconfig.build.json, packages/tds-widget/tsconfig.json, pnpm-lock.yaml, tsconfig.test.json
https://github.com/titicacadev/triple-frontend/issues/2130
- tds-ui, tds-widget 패키지를 추가합니다. 빈 패키지만 만들고 코드는 다른 pr에서 옮길 예정입니다.
- 현재 패키지는 feature와 layer의 구분없이 나뉘는데, 이제는 layer 단위로만 구분해보려고 합니다. 과도하게 많고 관계가 복잡한 패키지 개수를 줄이려고 합니다.
- tds-ui는 TDS의 presentational ui를 모은 패키지입니다.
- core-elements, action-sheet, modals, popup 등이 해당되고 이것들을 하나로 합칠 예정입니다.
- tds-widget은 여러개의 tds-ui를 조합한 컴포넌트 패턴입니다.
- query fetch, mutation을 할 수 있습니다.
- i18n 적용된 텍스트를 내장합니다.
- next를 peer dependency로 사용합니다. (app router, page router 둘 다 호환을 위해서 중간 패키지를 별도로 만들어야 할 수도...)
- native app과 통신합니다. (app interface)
=> tds-ui, tds-widget 패키지 추가

packages/chat/src/bubbles/rich.tsx, packages/chat/src/bubbles/text.ts, packages/chat/src/chat-bubble/blinded.tsx, packages/chat/src/chat-bubble/bubble-payload.tsx, packages/chat/src/chat-bubble/chat-bubble-ui.tsx, packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat/chat.tsx, packages/chat/src/types/index.ts, packages/chat/src/types/ui.ts
관리자에 의해 blind된 메세지를 위해 `blinded` 필드를 추가합니다. `Chat` 컴포넌트의 prop으로 `blindedText`를 설정해 넘겨주게 되면 해당 텍스트를 노출하고, `blindedText`가 설정되지 않았을 경우에는 기본 텍스트인 `관리자에 의해 삭제된 메세지입니다.`를 노출합니다.
- `MessageInterface`에 `blinded` 추가
- `Chat` 컴포넌트 prop에 `blindedText` 추가
message의 blind가 true일 때
- `blindedText` 설정 시
- `blindedText` 미설정 시
=> [Chat] message에 blinded 필드를 추가합니다.

packages/chat/src/types/index.ts
RoomMetadata의 타입을 변경합니다.
- 채팅 공지사항을 faq가 아닌 article로 관리함에 따라 RoomMetadata의 faqId가 articleId로 변경되었습니다.
- RoomMetadata는 room의 type이 event일 때만 존재하므로 옵셔널 값으로 변경합니다.
=> [Chat] RoomMetadata의 타입을 변경합니다.

packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat/chat-container.tsx, packages/chat/src/chat/chat.tsx, packages/chat/src/chat/reducer.ts, packages/chat/src/types/index.ts
기존 코드에서 전송 실패한 메시지를 재전송할 때 정상 메시지들이 모두 없어지는 오류가 있었습니다. 현재는 reducer의 `messages` 내에서 정상 메시지들과 전송 실패 메시지들을 한 번에 다루고 있습니다. 전송 실패 메시지를 재전송 후 전송이 성공했을 때, 재전송에 성공한 메시지를 필터링하는 과정에서 조건이 잘못 걸려 이전 메시지들이 모두 사라지고 있었습니다. 
필터링 조건의 간소화와 가독성, 메시지들의 유지 보수의 간편화를 위해 reducer에 `failedMessages` 상태를 추가하고, `REMOVE_FROM_FAILED` 액션을 추가했습니다.
- `onRetry`, `onCancel` 적용
- `reducer`에 failed 메시지 관련 상태 및 액션 추가
=> [Chat] 전송 실패 메시지 처리 방식 변경

package.json, pnpm-lock.yaml, renovate.json
chore: downgrade nx-cloud
nx-cloud runner가 원래는 access token이 없으면 default runner로 동작했었는데 
16.5.0 버전부터 access token이 필수가 되어버린 것 같습니다.
CI에는 토큰이 설정 되어 있지만 로컬에서 개발할 때는 토큰 설정 없이 default runner를 써야하기 때문에 16.4.0으로 고정해서 써봅니다.
=> downgrade nx-cloud

packages/chat/src/chat/chat.tsx, packages/chat/src/chat/reducer.ts
- https://inpk.atlassian.net/browse/TPB-2034
- ~~채팅창 초기접속 > 유저채팅 프론트에서 자동메시지 보여짐 > 유저가 첫 메시지를 전송하기 전까지는 프론트에만 존재함 > 유저가 첫 메시지를 전송하면 서버에 전송된 메시지로 변경~~
- ~~위 흐름을 createdAt 을 기준으로 필터링해야 메시지가 두개씩 보이는 현상이 사라집니다.~~
- 프론트 화면에서만 가지고 있는 채팅을 구분짓기 위해 chat reducer에 `ChatActions.BEFORE_SEND` 타입과 `beforeSentMessages` 상태를 추가합니다.
- `beforeSentMessages` 는 Chat 컴포넌트의 prop으로 받아서 저장하는 역할로 두었습니다.
- 연관 PR: https://github.com/titicacadev/triple-chat-web/pull/268
- dev, staging 테스트 완료
https://github.com/titicacadev/triple-frontend/assets/30427711/c35751e1-bfb4-464b-846c-e10f6c16ec5b
=> [chat] 채팅 인입 후 메시지 전송시 상품/예약정보 중복노출

packages/chat/src/chat/chat.tsx
- 파트너센터 채팅에서 예약건으로 랜딩되지 않는 이슈를 수정합니다.
- 지라: https://inpk.atlassian.net/browse/TPB-2044
- prop의 default value가 배열이나 객체일 경우 useEffect에서 같은 값으로 인식하지 못하고 계속 감지하여 루프에 빠지는 현상이 있습니다.
- 전송 후 비워주는 코드를 추가하고 초기 값만 받아서 업데이트하도록 수정합니다.
=> [chat] beforeSentMessages 초기 props만 저장하도록 수정

packages/chat/src/chat/chat.tsx
- 이전PR의 리뷰를 반영합니다
- https://github.com/titicacadev/triple-frontend/pull/2969#discussion_r1377054464
- reducer에서 beforeSentMessages의 기본 상태값이 빈 배열이기 때문에 기본값 불필요하여 제거합니다.
=> [chat] beforeSentMessages 기본값 불필요하므로 제거

packages/footer/src/award-footer.tsx
triple.guide에 노출되는 award-footer 내 인증마크 및 설명(툴팁)을 변경합니다.
- [참고 문서](https://inpk.atlassian.net/wiki/spaces/SPC/pages/426902243/2023.10+-)
- dev : https://triple-dev.titicaca-corp.com/
- staging : https://triple-staging.titicaca-corp.com/
=> [footer] Award Footer의 인증마크 변경

packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat/chat.tsx, packages/chat/src/types/index.ts, packages/chat/src/utils/constants.ts
[Chat] Message에 sender 정보를 포함하는 api 변경에 대응합니다.
- userInfo를 제거하고 각 message에 sender 정보가 포함되도록 수정합니다. (행사챗에서 사용자수가 1000명이 넘어가니 감당이 안되는군요😂)
- userInfo 대신 유저의 정보(me)를 받도록 수정합니다.
=> [Chat] Message에 sender 정보를 포함하는 api 변경에 대응합니다.

packages/chat/src/chat/chat.tsx, packages/chat/src/chat/reducer.ts
- beforeSendMessage를 리듀서에서 제거하여 postMessageAction 시 메세지가 중복 노출되는 현상을 방지합니다. ([관련 스레드](https://interpark.slack.com/archives/C05EVPMGL13/p1699329762625319?thread_ts=1697008302.408819&cid=C05EVPMGL13))
=> [chat] beforeSendMessages를 리듀서에서 제거합니다.

.github/workflows/cd.yaml, packages/standard-action-handler/package.json, packages/standard-action-handler/src/converse.tsx, packages/standard-action-handler/src/index.ts, pnpm-lock.yaml
API 호출 및 응답을 모달로 확인할 수 있는 기능을 추가합니다. 
자세한 내용은 [스펙 문서](https://inpk.atlassian.net/wiki/spaces/dev/pages/418580571/API)에서 확인하실 수 있습니다.
`fetch-api`는 호출만 담당하지만 `converse`는 API 반환 값을 이용해 모달을 노출하는 기능까지 포함되어있습니다.
어드민에서 응답을 받고싶은 API endpoint를 입력합니다.
형식 : `/web-action/converse?path={인코딩된 API endpoint}`
예시 : `/web-action/converse?path=%2Fapi%2Fbenefit%2Ftna-promotions%2Ffirst-buy`
- TNA 첫 구매 대상자 쿠폰 발급 API
API 응답 일반화 노출 기능을 추가합니다.
https://github.com/titicacadev/triple-frontend/assets/38130934/f65f77dc-e5a2-4b98-a01d-21cecdc1318e
=> API 응답 일반화 노출 기능을 추가합니다.

packages/poi-list-elements/src/carousel-element.tsx, packages/poi-list-elements/src/compact-poi-list-element.tsx
서울콘용으로 영문 POI 데이터를 페이지에 노출하는 작업을 진행중입니다.
영문 데이터에는 제목과 리전의 대표어값(Primary)에 항상 영문 데이터를 넣도록 약속되어 있습니다.
따라서 가이드 상세페이지에 노출되는 POI 리스트에서, 이름과 리전명에 대표어값이 가장 우선적으로 표기되도록 합니다.
- 영문 가이드 샘플 : https://triple-dev.titicaca-corp.com/content/seoul-con/articles/6082feee-99ac-494b-85b1-6ffa176de7aa?lang=en
=> [Poi-list-elements] POI의 이름과 리전명 영역에 대표어값이 가장 우선적으로 표기되도록 함

packages/poi-detail/src/image-carousel/carousel-section.tsx, packages/poi-detail/src/image-carousel/carousel.tsx, packages/poi-detail/src/image-carousel/index.tsx, packages/poi-detail/src/image-carousel/placeholder.tsx
'서울콘' 행사 대응용 작업입니다. POI 상단 이미지 캐러셀에서, '서울콘' 행사 유저들에게 특정 UI 및 한정적 컨텐츠를 제공합니다.
- [서울콘 관련 문서](https://inpk.atlassian.net/wiki/spaces/SPC/pages/341443028)
- [컨텐트웹에서 숨겨야 하는 영역 및 기능 목록 시트](https://docs.google.com/spreadsheets/d/1HN9_vul_qMcLjHGXf5c5I9hKVcU2HIGA3ewTzb7Jeg8/edit#gid=1763643502)
'guestMode' 네이밍이 적절한지 https://github.com/titicacadev/triple-frontend/pull/2990 이곳에서 논의하여 동일하게 적용하려고 합니다.
'서울콘' 행사를 통해 컨텐트웹(triple-content-web)의 페이지로 유입된 사용자들은 모두 비로그인 상태이며, 로그인이 필요한 기능을 사용할 수 없습니다. 더불어 트리플앱으로의 연결을 유도하는 루트도 보지 않아야 합니다.
- 서울콘 행사 유저의 접근을 구분하기 위해 'guestMode'라는 플래그를 추가했습니다.
- guestMode가 true인 경우
- 사진을 최대 5장까지만 노출합니다.
- 따라서 기존 6장째 사진에서 노출되는 '트리플 앱에서 사진 더 보기' 영역이 나타나지 않습니다.
- 사진 인덱스(ex. 1/5)의 총 사진 수가 최대 5장까지만 나타나도록 합니다.
- 등록된 사진이 없을 시, '사진 등록' 아이콘이 아닌 POI 타입별 디폴트 아이콘을 노출합니다.
- 일반 POI …
=> [Poi-detail] image carousel 서울콘 대응

packages/poi-list-elements/src/carousel-element.tsx, packages/poi-list-elements/src/compact-poi-list-element.tsx, packages/poi-list-elements/src/types.ts, packages/triple-document/src/elements/pois.tsx, packages/triple-document/src/index.ts, packages/triple-document/src/prop-context/guest-mode.ts, packages/triple-document/src/triple-document.tsx, packages/triple-document/src/types.ts
POI 리스트에서 스크랩 버튼을 숨길 수 있도록 합니다. '서울콘' 행사 대응용 작업입니다. 
- [서울콘 관련 문서](https://inpk.atlassian.net/wiki/spaces/SPC/pages/341443028)
- [컨텐트웹에서 숨겨야 하는 영역 및 기능 목록 시트](https://docs.google.com/spreadsheets/d/1HN9_vul_qMcLjHGXf5c5I9hKVcU2HIGA3ewTzb7Jeg8/edit#gid=0)
'서울콘' 행사를 통해 컨텐트웹(triple-content-web)의 페이지로 유입된 사용자들은 모두 비로그인 상태이며, 로그인이 필요한 기능을 사용할 수 없습니다. 더불어 트리플앱으로의 연결을 유도하는 루트도 보지 않아야 합니다.
- 그래서 Triple Document에 포함된 `Pois` 컴포넌트(POI list) 내 로그인 및 앱과의 연결과 관련된 부분들을 특정한 값을 기준으로 분기하기 위하여, `guestMode` 값을 받을 수 있도록 추가했습니다.
- `guestMode`가 `true`인 경우, POI list의 스크랩 버튼을 숨깁니다.
'페이지에서 로그인이 필요한 동작(스크랩, 리뷰쓰기)등이 불가능하며, 앱으로 연결되는 루트에 접근할 수 없음'이라는 기획을 적용하기 위해, 관련 기능을 분기하는 기준 플래그를 `guestMode`라고 이름붙였습니다.
서울콘 `seoulcon` 이라고 이름붙일지 고민했으나, Triple Document에 특정 이벤트 이름이 들어가는것이 적절하지 않을 수 있겠다고 생각했어요. 하지만 아직 서울콘 외에 다른 비슷한 이벤트는 …
=> [Poi-list-elements] POI 리스트에서 스크랩 버튼을 숨길 수 있도록 함

packages/chat/src/bubble/blinded.tsx, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.tsx, packages/chat/src/bubble/product.tsx, packages/chat/src/bubble/rich.tsx, packages/chat/src/bubble/type.ts, packages/chat/src/chat/chat-context.ts, packages/chat/src/chat/chat.tsx, packages/chat/src/utils/constants.ts
`BubbleUI`는 들어오는 타입에 따라 알맞는 Bubble을 렌더링하는 역할을 합니다. 기존에는 type에 맞는 prop들만 넘길 수 있게 되어있었으나, 컴포넌트의 목적과 사용의 편리함을 위해 버블의 타입에 상관없이 종합적으로 필요한 prop을 모두 받아 `BubbleUI` 내부에서 각 Bubble에 맞는 prop을 넘기는 형태로 수정합니다.
=> [Chat refactor] BubbleUI의 prop 변경

.github/workflows/ci.yaml
ci의 test job이 coverage의 maxWorker가 4일 때 fail하고 있습니다. maxWorker를 2로 고정합니다. ([관련 스레드](https://interpark.slack.com/archives/C05EUG8UYP6/p1699322851538249))
=> ci의 test coverage의 maxWorker를 2로 고정합니다.

packages/chat/src/bubble-container/bubble-container.tsx, packages/chat/src/bubble/altered.tsx, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.tsx, packages/chat/src/bubble/constants.ts, packages/chat/src/bubble/type.ts, packages/chat/src/messages.stories.tsx, packages/chat/src/messages.tsx, packages/chat/src/types/index.ts, packages/chat/src/utils/image.ts
메시지 리스트를 렌더링하는 Messages 컴포넌트 생성합니다. `messages`, `pendingMessages`, `failedMessages`를 prop으로 전달 시 각 메시지들을 타입에 맞는 Bubble과 함께 렌더링합니다.
- `ContainerBaseProp` 타입 생성
- `BlindedBubble`에서 `AlteredBubble`로 변경
-  블라인드 된 / 삭제한 / 차단한 사용자의 메시지의 UI를 한 번에 처리하기 위해 `AlteredBubble`로 변경
- `Messages` 컴포넌트 생성
- `CustomBubble`로 prop 전달 시 TF에서 제공하는 `'text' | 'images' | 'rich' | 'product'`가 아닌 type의 메시지도 렌더링 가능. 스토리북 참고
-
=> [Chat refactor] 메시지 리스트를 렌더링하는 Messages 컴포넌트 생성

packages/chat/package.json, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/image.tsx, packages/chat/src/bubble/text.tsx, packages/chat/src/bubble/type.ts, packages/chat/src/i18n.d.ts, packages/chat/src/messages.tsx, packages/chat/src/utils/a-tag-navigator.ts, packages/chat/src/utils/image.ts, packages/chat/src/utils/index.ts, pnpm-lock.yaml
`ImageBubble`과 `TextBubble, RichBubble` 내의 a tag의 default click 이벤트를 설정합니다. `ImageBubble`의 경우 앱 내에서 이미지를 클릭 시 이미지 확대뷰를 노출합니다. `TextBubble, RichBubble` 내의 a tag 클릭 시 해당 링크를 오픈합니다. 
`a-tag-navigator.ts` 기능을 개발하면서 사용한 router 패키지에서 `i18n.d.ts` 파일을 요구해 이를 추가합니다. 해당 파일에서 import 중인 패키지들을 devDependency에 추가합니다.
`Messages` 컴포넌트에서 onRetry, onRetryCancel 클릭 이벤트를 전달합니다.
=> [Chat refactor] Bubble의 default click 설정

packages/tds-widget/src/poi-detail/image-carousel/provider.tsx, packages/tds-widget/src/poi-detail/image-carousel/reducer.ts, packages/tds-widget/src/poi-detail/index.ts
react-contexts/images-context를 poi-detail/ImageCarouselProvider로 이동
- react-contexts/images-context는 사실상 poi-detail/ImageCarousel과 한 세트기 때문에 images-context를 poi-detail로 옮기고 `ImageCarouselProvider`로 이름을 바꿉니다.
- `useImagesContext`를 `useImageCarousel`로 이름을 바꿉니다.
- hoc를 제거합니다.
=> [v14] react-contexts/images-context를 poi-detail/ImageCarouselProvider로 이동

packages/tds-widget/src/ad-banner/content-details-banner.tsx, packages/tds-widget/src/ad-banner/list-top-banners.tsx, packages/tds-widget/src/image-carousel/video-content.tsx, packages/tds-widget/src/review/components/review-element/media/video.tsx
`DeviceContext`를 `useGeolocation`과 `useClientApp`로 대체합니다.
=> [v14] useDeviceContext를 useGeolocation과 useClientApp로 대체합니다.

packages/tds-widget/src/footer/company-info.tsx, packages/tds-widget/src/review/reviews-shorten.stories.tsx, packages/tds-widget/src/review/reviews.stories.tsx, packages/triple-document/src/elements/coupon/coupon-download-buttons.tsx, packages/triple-web/src/hooks/session/use-login.ts, packages/ui-flow/package.json, packages/ui-flow/src/use-session-callback.test.tsx, packages/ui-flow/src/use-session-callback.ts, pnpm-lock.yaml
기존 `react-contexts`의 `session` 코드를 `triple-web`의 `session` 코드로 변경합니다.
```tsx
// AS-IS
const { login, logout } = useSessionControllers()
/// TO-BE
const login = useLogin()
const logout = useLogout()
```
`@titicaca/react-contexts` -> `@titicaca/triple-web`
Session decorator를 제거했습니다.
- 추후에 decorator를 한번에 정리할 예정입니다.
`@titicaca/ui-flow`에 `@titicaca/triple-web`을 설치했습니다.
=> [v14] session-context 마이그레이션

packages/react-contexts/src/event-tracking-context/event-metadata-context.tsx, packages/react-contexts/src/event-tracking-context/event-tracking-context.tsx, packages/react-contexts/src/event-tracking-context/types.ts
- 틱톡 픽셀 이벤트를 EventTrackingContext에 추가합니다.
- [틱톡 픽셀 api 문서](https://ads.tiktok.com/gateway/docs/index?identify_key=2b9b4278e47b275f36e7c39a4af4ba067d088e031d5f5fe45d381559ac89ba48&language=ENGLISH&doc_id=1701890973258754#item-link-Track%20an%20event%20based%20on%20page%20load) 
v14에는 기존 pixel 항목이 facebookPixel로 변경될 예정입니다.
=> [react-contexts] 틱톡 pixel 이벤트를 추가합니다.

packages/chat/src/chat-bubble/bubble-info.tsx, packages/chat/src/chat-bubble/chat-bubble-ui.stories.tsx, packages/chat/src/chat-bubble/chat-bubble-ui.tsx, packages/chat/src/chat-bubble/chat-bubble.tsx, packages/chat/src/chat-bubble/thanks.tsx, packages/chat/src/chat/chat.tsx, packages/chat/src/chat/reducer.ts, packages/chat/src/types/index.ts, packages/chat/src/utils/constants.ts
이벤트챗에서 사용될 좋아요 기능을 추가합니다. [관련 위키](https://inpk.atlassian.net/wiki/spaces/SPC/pages/462717087)
좋아요 버튼 추가
- 좋아요, 좋아요 취소 가능
- blind된 메세지에는 노출되지 않음
좋아요 기능은 이벤트챗에서만 사용되지만 챗의 종류에 상관없이 API에서 `reactions` 값을 넘겨주기 때문에 기본챗(파트너센터)의 메세지들에서 thanks를 undefined로 넘겨주려고 했습니다. 그러나 과거 메세지 fetch가 TF 내에서 일어나고 있어서 chat-web에서 undefined로 바꿔주기 + TF에서 undefined로 바꿔주기 모두 필요한 상황이었습니다. 현재 리팩토링도 진행되고 있기 때문에 당장은 좀 더 간단한 로직을 갖고가기 위해 `ChatBubble`에서 `ChatBubbleUI`로 넘겨줄 때 채팅방의 타입을 구분해 값을 넘겨주기로 하였습니다.
=> [Chat] 좋아요 기능 추가

packages/router/package.json, packages/router/src/navigate/index.test.ts, packages/router/src/navigate/index.ts, packages/standard-action-handler/src/hook.ts, packages/tds-widget/src/ad-banner/content-details-banner.tsx, packages/tds-widget/src/ad-banner/list-top-banners.tsx, packages/tds-widget/src/booking-completion/index.tsx, packages/tds-widget/src/nearby-pois/poi-entry.tsx, packages/tds-widget/src/replies/list/reply.tsx, packages/tds-widget/src/replies/reply.test.tsx, packages/tds-widget/src/review/services/use-client-actions.tsx, packages/tds-widget/src/social-reviews/social-review.tsx, packages/triple-document/src/elements/coupon/modals.tsx, packages/triple-document/src/elements/itinerary.tsx, packages/triple-document/src/elements/itinerary/use-handle-add-pois-to-trip.ts, packages/triple-document/src/elements/tna/slot.tsx, packages/triple-document/src/triple-document.tsx, packages/triple-header/src/frame/frame.tsx, pnpm-lock.yaml
기존 history-context의 openWindow를 router의 navigate로 이동합니다.
기존의 useNavigate는 사용시 디스트럭쳐링이 필요하게 됩니다.
(https://github.com/titicacadev/triple-frontend/pull/3027 에서 이동했습니다.)
```tsx
// before
const navigate = useNavigate()
// after
const { navigate, openWindow } = useNavigate()
```
=> [v14] history-context의 openWindow를 router의 navigate으로 이동합니다.

packages/resource-list-element/src/extended-resource-list-element.stories.tsx, packages/resource-list-element/src/extended-resource-list-element.tsx
- `ExtendedResourceListElement`에 `badge` 영역을 추가합니다. 
https://triple-dev.titicaca-corp.com/tna/products?from=hub&type=CITY&cityId=d-f1bc8e2c-6a91-4660-a0fe-f604895c88e5&categoryIds=9120
=> ExtendedResourceListElement에 badge 영역 추가

packages/triple-header/package.json, packages/triple-header/src/frame/effects/common.ts, packages/triple-header/src/frame/effects/flying.tsx, packages/triple-header/src/frame/effects/rotate.tsx, packages/triple-header/src/frame/effects/types.ts, packages/triple-header/src/frame/effects/zoom.tsx, packages/triple-header/src/frame/frame.tsx, packages/triple-header/src/frame/image.tsx, packages/triple-header/src/frame/text.tsx, packages/triple-header/src/layer/layer.tsx, packages/triple-header/src/layer/transitions/fade-in-out.tsx, packages/triple-header/src/layer/transitions/slide.tsx, pnpm-lock.yaml
리뷰를 위해 트리플 헤더 기능에 대해 간략하게 설명드리면, 트리플 헤더는 크게 레이어와 프레임이라는 개념을 사용합니다.
레이어는 z 축을 기반으로 액자형식으로 여러 이미지를 겹칠 수 있도록 하고, 각 레이어는 한 개 또는 여러 개의 프레임을 사용할 수 있습니다.
트리플 헤더에서 사용하는 애니메이션은 크게 두 종류로 구분할 수 있는데 요약하면 다음과 같습니다.
1. 프레임이 여러 개인 경우 프레임 간의 전환 시 발생하는 애니메이션 - 기본 전환, 페이드 인 아웃 등
2. 각 프레임이 노출되는 경우 발생하는 애니메이션 - 확대하기, 회전하기, 날라오기 등
이번 PR은 프레임이 여러 개인 경우 기본 전환 시, 프레임 전환 간 깜빡임 현상이 해결합니다. 그리고 추가적으로 다음 문제들을 해결합니다.
- 기본 전환, 페이드인아웃 전환 시, 프레임 효과를 한 번만 실행으로 설정해도 계속 실행되었던 문제를 해결합니다.
- 프레임이 여러 개인 경우, 각 프레임이 노출될 때 발생하는 애니메이션의 옵션을 한 번만 실행으로 설정 시, 한 번만 실행됩니다.
- 프레임 날라오기 효과를 계속 실행으로 설정 시, 다른 프레임 효과와 동일한 시간 텀을 가지고 실행하도록 합니다.
- 기존에는 0.3초마다 실행되고 있습니다.
- 기존에는 프레임 간 기본 전환 시 렌더링 할 프레임을 매번 변경하여, 각 프레임이 새롭게 렌더링 되었을 때 애니메이션을 실행하는 방식이었습니다. 모든 프레임을 렌더링하고 opacity로 노출할 프레임을 조절하고, index와 총 프레임 개수를 이용해서 `delay`, `repeatDelay`를 조절하는 방식으로 …
=> [TFC-52] 트리플 헤더 블링크 이슈

packages/chat/src/chat/scroll-context.tsx
scroll context에 스크롤 방지 옵션을 추가합니다.
- setScrollY, setScrollBy의 역스크롤 현상을 방지하는 데 사용합니다.
- 스크롤이 걸린 로직의 예외처리를 할 때 사용합니다.(예시: 부모 메세지 preview를 닫을 때 default 스크롤 방지)
=> [chat refactor] scroll context에 스크롤 방지 옵션을 추가합니다.

packages/router/package.json, packages/router/src/navigate/use-navigate.test.ts, packages/standard-action-handler/package.json, packages/tds-widget/package.json, packages/tds-widget/src/poi-detail/detail-header-v2/index.test.tsx, packages/tds-widget/src/poi-detail/detail-header/index.test.tsx, packages/tds-widget/src/replies/list/index.tsx, packages/tds-widget/src/review/components/filter-context.tsx, packages/tds-widget/src/review/components/infinite-list/infinite-list.tsx, packages/tds-widget/src/review/components/my-review-action-sheet.tsx, packages/tds-widget/src/review/components/review-element/index.tsx, packages/tds-widget/src/review/components/reviews-shorten.tsx, packages/tds-widget/src/review/components/reviews.tsx, packages/tds-widget/src/review/components/shorten-list/reviews-list.tsx, packages/tds-widget/src/review/components/sorting-context.tsx, packages/tds-widget/src/review/services/use-client-actions.tsx, packages/tds-widget/src/review/services/use-reviews.ts, packages/tds-widget/src/scrap/use-scrap.ts, packages/tds-widget/src/user-verification/verified-message.spec.ts, packages/tds-widget/src/user-verification/verified-message.ts, packages/triple-document/package.json, packages/triple-header/package.json, packages/triple-web/src/hooks/client-app/index.ts, packages/ui-flow/package.json
useClientAppActions import path 수정
- useClientAppActions import path 수정
- react-triple-client-interfaces 흔적 제거
=> [v14] useClientAppActions import path 수정

packages/directions-finder/package.json, packages/directions-finder/src/direction-buttons.tsx, pnpm-lock.yaml
grab 호출 버튼에 Intersecting Observer를 추가하고 onCallGrabButtonIntersecting props를 추가합니다.
=> [directions-finder] grab 호출 버튼에 Intersecting Observer를 추가합니다.

packages/i18n/src/assets/en/common-web.ts, packages/i18n/src/assets/ja/common-web.ts, packages/i18n/src/assets/ko/common-web.ts, packages/review/src/components/review-element/badges.tsx, packages/review/src/components/review-element/index.tsx, packages/review/src/components/review-element/purchaseInfo.tsx, packages/review/src/components/review-element/user.tsx, packages/review/src/data/graphql/generated.ts, packages/review/src/data/graphql/query.graphql, packages/review/src/mocks/review-element.duo-images.json, packages/review/src/mocks/review-element.mono-image.json
[후기에 예약한 상품의 상세 정보 노출 위키](https://inpk.atlassian.net/wiki/spaces/BUS/pages/425885752/2310)
현재 후기에서는 작성자가 구매자인지 비구매자인지 구분할 수 없습니다. 또한 유저가 실제로 상품을 구매 후 리뷰를 작성했다고 해도 리뷰를 통해서는 어떤 상품을 구매했는지도 알 수 없습니다. 이를 개선하기 위해 리뷰에 예약 상품 상세 정보를 노출합니다.
- 유저가 구매한 상품을 연결한 경우 해당 정보를 노출
- `최근 여행` 뱃지 UI 수정
-  `구매 인증 리뷰` 뱃지 추가
<table>
<tr>
<th>AS-IS</th>
<th>TO-BE</th>
</tr>
<tr>
<td><img width="300" alt="image" src="https://github.com/titicacadev/triple-frontend/assets/43779313/f2d7a31f-7b82-46be-b44f-c95a57d1e54c"></td>
<td><img width="300" alt="image" src="https://github.com/titicacadev/triple-frontend/assets/43779313/a443ec61-bdb8-46a6-8a31-2f4e5c9a0d7d"></td>
</tr>
</table>
=> [Review] 예약 상품 상세 정보 노출

packages/triple-document/src/elements/itinerary.tsx, packages/triple-document/src/elements/itinerary/save-to-itinerary.tsx, packages/triple-document/src/elements/itinerary/use-computed-itineraries.ts, packages/triple-document/src/elements/itinerary/use-handle-add-pois-to-trip.ts, packages/triple-document/src/mocks/triple-document.itinerary.json
기존에는 `내 일정으로 담기` 버튼 클릭 시에 추천일정에 포함된 첫번째 POI의 regionId 값을 앱으로 전달했습니다. 그러나 해당 값은 백엔드에서 강제 할당했던 값으로, `geotag`가 도입된 이후에는 강제 할당 로직을 실행하지 않아 `regionId` 값이 업데이트되지 않은 POI가 존재합니다. 이럴 경우, `내 일정으로 담기` 버튼을 클릭하더라도 아무런 동작이 취해지지 않는 현상이 발생합니다.
또한 `zone` 역시 앱으로 전달하는 것이 가능한데 해당 로직은 현재 빠져있습니다. 
`내 일정으로 담기` 기능을 정상적으로 실행하기 위해 로직을 수정했습니다. `Itinerary` element에 `geotag` prop을 추가해 `내 일정으로 담기` 버튼 클릭 시 해당 값을 우선적으로 참조합니다. 이 값이 없는 경우에는 추천 일정의 POI들을 참조합니다.
- `Itinerary` element에 `geotag` prop 추가했습니다
- `geotag` prop이 없는 경우 POI 참조합니다
- 기존에는 첫번째 POI의 값만 참고했지만, `regionId`를 찾지 못할 가능성을 낮추기 위해 `find` 메소드를 적용했습니다
- 앱으로 전달할 수 있는 리전/존의 값이 존재하는 경우에만 `내 일정으로 담기` 버튼을 노출합니다
- `SaveToItinerary` 컴포넌트를 분리했습니다
=> [triple-document] 추천 일정의 '내 일정으로 담기' 로직을 수정합니다.

packages/replies/src/register.tsx, packages/replies/src/replies.stories.tsx, packages/replies/src/replies.tsx
유저가 댓글을 작성하고 삭제할 때 해당 이벤트를 외부에서 알 수 있도록 함수를 추가합니다. 
[관련 스레드](https://interpark.slack.com/archives/C05ERUV2603/p1703652133870889)
- `onCompleteReplyAdd`, `onCompleteReplyDelete` 함수 prop 추가
- 스토리북에서 댓글 작성 기능을 테스트할 수 있도록 수정
- 댓글 작성은 `Session`이 available해야하기 때문에 `SessionContextProvider`를 override
=> 댓글 작성, 삭제 handle function prop을 추가합니다

packages/chat/src/chat/messages-reducer.ts
- messagesReducer에 hasPrevMessage, hasNextMessage를 설정할 수 있는 액션을 추가합니다.
- messagesReducer에 PENDING, FAILED, REMOVE 액션에 들어가는 메세지 타입을 수정합니다.
=> [Chat Refactor] MessagesReducer의 액션을 추가하고 타입을 수정합니다.

packages/review/src/components/review-element/index.tsx, packages/review/src/services/use-reviews.ts
[제보 스레드](https://interpark.slack.com/archives/C061LUEUP8A/p1705979266405729)
리뷰에서 좋아요 버튼을 여러번 클릭했을 때, 이전 요청이 처리되지 않은 상태에서 새로운 요청들이 들어가며 좋아요/좋아요 취소 handler가 여러번 실행되고 있었습니다. 이를 방지하기 위해 요청이 처리되고 있는 상황에서는 버튼이 클릭되지 않도록 했습니다. 
또한 좋아요/좋아요 취소 로직에서 본인 리뷰 쿼리 데이터가 업데이트에서 빠져있어 본인 리뷰를 좋아요/좋아요 취소할 경우 반영되지 않고 있어 handler에 추가했습니다. 
문제 상황
https://github.com/titicacadev/triple-frontend/assets/43779313/0459ee0d-b8c5-43b4-8cd4-65ebc7c591fb
=> [review] 좋아요 카운트 버그 수정

packages/router/src/links/use-open-inlink.ts, packages/triple-web-nextjs-pages/src/build-triple-web-props.ts, packages/triple-web-nextjs-pages/src/event-metadata-provider.tsx, packages/triple-web-nextjs-pages/src/event-tracking-provider.tsx, packages/triple-web-nextjs-pages/src/get-session-availability.ts, packages/triple-web-nextjs-pages/src/helpers/index.ts, packages/triple-web-nextjs-pages/src/hooks/use-lang.ts, packages/triple-web-nextjs-pages/src/index.ts, packages/triple-web-nextjs-pages/src/triple-web.tsx, packages/triple-web-nextjs/src/build-triple-web-props.ts, packages/triple-web-nextjs/src/event-metadata-provider.tsx, packages/triple-web-nextjs/src/event-tracking-provider.tsx, packages/triple-web-nextjs/src/hooks/index.ts, packages/triple-web-nextjs/src/index.ts, packages/triple-web-nextjs/src/triple-web.tsx
TripleWeb 사용 편의성 보완
- utm prop을 전달하지 않아도 되는 EventMetadataProvider, EventTrackingProvider를 triple-web-nextjs, triple-web-nextjs-pages에 추가
- BuildTripleWebResult 타입 추가
- 현재 사용자 언어를 가져오는 기능이 내장된 TripleWeb을 triple-web-nextjs, triple-web-nextjs-pages에 추가
- triple-web-nextjs에도 buildTripleWebProps 추가
=> [v14] TripleWeb 사용 편의성 보완

packages/modals/src/transition-modal.tsx, packages/review/src/components/my-review-action-sheet.tsx, packages/review/src/components/review-element/index.tsx, packages/review/src/services/use-reviews.ts
- [제보 스레드](https://interpark.slack.com/archives/C05FBAEJPJM/p1706087418447099)
- 리뷰 삭제 시 호출되는 web to app 이벤트 `notifyReviewDeleted`가 중복 호출되고 `resourceType`이 `null`로 전달되는 이슈를 수정합니다.
- 웹에서 리뷰 메뉴(쓰리닷) 선택 시 앱 설치 유도 팝업이 노출되지 않는 이슈를 수정합니다.
https://github.com/titicacadev/triple-frontend/assets/133629020/fe9ba214-c55f-4d39-b685-6c64b6a59958
=> [Review] notifyReviewDeleted 중복 호출 제거 및 리뷰 메뉴 선택 시 앱 설치 유도팝업 노출

packages/chat/package.json, packages/chat/src/bubble-container/bubble-container.tsx, packages/chat/src/bubble-container/bubble-info.tsx, packages/chat/src/bubble-container/elements.tsx, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.tsx, packages/chat/src/bubble/product.tsx, packages/chat/src/messages.tsx, packages/chat/src/messages/date-divider.tsx, packages/chat/src/messages/index.tsx, packages/chat/src/messages/messages.stories.tsx, packages/chat/src/messages/type.ts, packages/chat/src/messages/utils.ts, pnpm-lock.yaml
- 버블 스타일을 수정합니다. 디자인을 지오챗과 통일하기 위해 css를 수정했습니다.
- 날짜 및 시간 표기, 프로필 생략 기능을 추가합니다. 동일한 유저가 보낸 메세지일 경우 프로필이 생략되며, 하단 메세지와 날짜와 시간이 같은 경우 시간 표시가 생략됩니다.
- moment를 삭제하고 date-fns를 사용하도록 변경합니다.
- messages.tsx 파일을 messages/index.tsx 경로로 이동하고, messages 관련 유틸 함수, 타입 파일을 분리했습니다.
=> [chat] 버블 스타일을 수정하고 날짜 및 시간 표기, 프로필 생략 기능을 추가합니다.

packages/poi-detail/src/actions/actions.stories.tsx, packages/poi-detail/src/actions/actions.tsx, packages/poi-detail/src/actions/review-tooltip.tsx, packages/poi-detail/src/index.ts
`useLocalStorage` hook을 사용하게 되면서 `REVIEW_TOOLTIP_EXPOSED` 의 초기값이 항상 `null`로 저장되어 리뷰 영상 툴팁이 항상 노출되고 있었습니다. 이를 방지하기 위해 `ReviewTooltip` 컴포넌트를 따로 만들어 해당 컴포넌트를 클라이언트 사이드에서만 렌더링하도록 수정했습니다. 
오프라인 패키지에서는 `Actions` 컴포넌트를 렌더링하지 않으므로 영향이 없습니다.
- `actions` 폴더 생성
- `ReviewTooltip` 컴포넌트 생성
- `ReviewTooltip` 컴포넌트 dynamic import로 수정
=> [poi-detail] 리뷰 영상 관련 툴팁 노출 버그를 수정합니다

packages/chat/src/bubble-container/bubble-container.stories.tsx, packages/chat/src/bubble-container/bubble-container.tsx, packages/chat/src/bubble/altered.tsx, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.stories.tsx, packages/chat/src/bubble/bubble.tsx, packages/chat/src/bubble/parent/parent-message.tsx, packages/chat/src/bubble/parent/parent-ui.tsx, packages/chat/src/bubble/parent/parent.stories.tsx, packages/chat/src/bubble/product.tsx, packages/chat/src/bubble/rich.tsx, packages/chat/src/bubble/text.tsx, packages/chat/src/bubble/type.ts, packages/chat/src/messages/messages.stories.tsx, packages/chat/src/utils/profile.ts
ParentMessage UI를 추가합니다. 
- chat에서 볼 때는 부모 메세지의 경우 없거나/있거나 둘 중 하나이지만, 파트너챗과 같은 서비스에서는 부모 메세지가 존재하지 않으므로 null과 undefined 모두 가능하도록 했습니다. 
- MessageParent UI의 css는 ParentMessage의 prop으로 전달합니다.
BubbleUI를 Messages 컴포넌트 내에서 렌더링하기 때문에  Bubble은 Messages의 Prop으로 전달하지만, ParentMessageUI 컴포넌트를 Bubble의 children으로 렌더링하기 때문에 이처럼 정했습니다. Bubble과의 통일성을 위해서는 Messages의 prop으로 전달하는 것이 맞을 것 같은데, 의견 부탁드립니다. 물론 이럴 경우에도 Bubble에서 ParentMessageUI를 렌더링할 때 prop으로 전달하게 됩니다.
```
export type ParentMessageUIProp = (TextParentMessage | ImageParentMessage) & {
blinded: boolean
style?: {
css?: CSSProp;
titleColor?: string;
previewTextColor?: string;
}
}
```
```
bubbleStyle?: {
received?: {
css?: CSSProp;
alteredTextColor?: string;
};
sent?: {
css?: CSSProp;
alteredTextColor?: string;
};
parentMessageCss?: {
css?: CSSProp; …
```
=> [chat] 부모 메세지 UI를 추가합니다

packages/standard-action-handler/README.md, packages/standard-action-handler/src/hook.ts, packages/standard-action-handler/src/index.ts, packages/standard-action-handler/src/require-triple-client.tsx, packages/standard-action-handler/src/types.ts
`web-action/requireTripleClient?url=[URL]`을 실행하면 트리플 앱 내에서 열린 페이지의 경우 url로 이동하고, 그렇지 않은 경우에는 앱 설치 유도 모달을 띄웁니다.
[`TransitionModal`을 열 때 실행되는 로직들](https://github.com/titicacadev/triple-frontend/blob/main/packages/modals/src/transition-modal.tsx#L187-L203)이 있기 때문에 이 로직이 `web-action`에서도 동일하게 동작할 수 있도록 `showTransitionModal` 값을 option으로 받도록 했습니다. 
또한 `url`이 `web-action`인 경우에도 동작이 실행될 수 있도록 handler로 실행되도록 했습니다. 
- `standard-action-handler`에 `requireTripleClient` web-action을 추가합니다
https://triple-dev.titicaca-corp.com/articles/fc936557-fb52-44ea-8779-0ffb2fe433b3
=> [standard-action-handler] requireTripleClient 함수 추가

packages/triple-document/src/elements/tna/price-policy-coupon-info.tsx, packages/triple-document/src/elements/tna/product.tsx, packages/triple-document/src/mocks/slots.sample.json
tna slot의 타이틀을 두 줄로 노출하도록 수정하고, 간격 조정 등 디자인을 수정합니다. ([관련 스레드](https://interpark.slack.com/archives/C05FBAEJPJM/p1707192636278089))
=> [triple-document] tna slot의 타이틀을 두줄 노출하도록 수정

packages/chat/src/bubble/altered.tsx
삭제되거나 가려지는 등 AlteredBubble이 렌더링되는 경우에는 Parent Message가 노출되지 않도록 수정합니다.
|AS-IS|TO-BE|
|---|---|
|![스크린샷 2024-02-13 오후 4 58 28](https://github.com/titicacadev/triple-frontend/assets/43779313/c62d49f2-be90-47c7-aa0b-827d3d311359)|![스크린샷 2024-02-13 오후 4 58 14](https://github.com/titicacadev/triple-frontend/assets/43779313/1d62d31b-3dd2-4a10-8021-1ad1e7a5c345)|
=> [geochat] AlteredBubble에서는 부모 메시지 노출하지 않도록 변경

packages/chat/src/bubble-container/bubble-container.tsx, packages/chat/src/bubble-container/elements.tsx, packages/chat/src/bubble-container/icons.tsx
리트라이 관련 아이콘을 TF chat 패키지 내부에 저장해 오프라인 상태에서도 아이콘이 보일 수 있도록 합니다.
=> [geochat] 리트라이 아이콘을 추가합니다

packages/nearby-pois/src/nearby-pois.tsx, packages/nearby-pois/src/reducer.ts
더보기 버튼을 여러번 클릭할 경우 poi가 중복 노출되는 이슈를 수정합니다. ([관련 스레드](https://interpark.slack.com/archives/C05GCN0AYSZ/p1708294659165219))
- 기존 fetching status를 수정하는 액션(fetchPois)이 선언만 되어 있고 사용하지 않은 문제를 수정합니다. api 호출과 변수명이 겹쳐 setFetchingStatus로 변경합니다.
- fetching 상태를 변경해 더보기 버튼을 disable 처리해도 느린 네트워크 환경에서는 api의 중복 호출이 가능한 것 같습니다. api의 응답값을 리듀서에서 머지할 때 중복을 제거하도록 수정합니다.
=> [nearby-pois] 더보기 버튼 클릭 시 api 호출이 중복되는 이슈 수정

packages/nearby-pois/src/reducer.ts
#3140 에서 받은 피드백을 적용합니다([코멘트](https://github.com/titicacadev/triple-frontend/pull/3140#discussion_r1496745679)). deduplicateAndMergePoiList의 중복 제거 로직을 filter에서 Map 객체로 수정합니다.
=> [nearby-pois] pois 중복을 제거하는 로직을 수정합니다.

packages/chat/src/bubble/altered.tsx
`bubbleStyle`에 기본 텍스트 컬러를 설정하면 대체 텍스트 컬러에 `alteredTextColor`가 적용되지 않는 버그를 수정합니다.
|AS-IS|TO-BE|
|------|-------|
|<img width="260" alt="image" src="https://github.com/titicacadev/triple-frontend/assets/43779313/2bf368d7-da53-47f9-b1e2-effab63be2e8">|<img width="281" alt="스크린샷 2024-03-07 오후 4 24 54" src="https://github.com/titicacadev/triple-frontend/assets/43779313/44e11d60-400d-4efd-b353-1b26c8514348">|
=> [geochat] 대체 말풍선 컬러 버그 수정

packages/view-utilities/src/find-folded-position.ts
엔터가 많이 포함된 댓글에서 말줄임이 제대로 되지 않는 버그를 수정합니다. 
- 빈 줄이 많이 포함되어 있는 경우 `rest>line.length`에 조건문이 걸리지 않아 말줄임이 제대로 이루어지지 않고 있습니다. 이에 빈줄이 많은 경우도 조건문을 추가합니다.
|AS-IS|TO-BE|
|-----|-------|
|![스크린샷 2024-03-11 오후 5 31 08](https://github.com/titicacadev/triple-frontend/assets/43779313/9a9eddbc-8221-428b-84a5-e4f5efdd8b88)|![스크린샷 2024-03-11 오후 5 31 23](https://github.com/titicacadev/triple-frontend/assets/43779313/031c61ec-45e4-400a-b1ba-0781c88610f1)|
|AS-IS|TO-BE|
|-----|-------|
|![스크린샷 2024-03-13 오후 5 26 35](https://github.com/titicacadev/triple-frontend/assets/43779313/2d92a7e3-1bac-4c20-9729-24b4a06b86b2)|![스크린샷 2024-03-13 오후 5 26 55](https://github.com/titicacadev/triple-frontend/assets/43779313/b66b2c29-b21e-4189-a2d5-87f1010000f3)|
=> [view-utilities] 말줄임 함수 수정

packages/view-utilities/src/routelist/routelist.ts
- 항공 시세 페이지를 routelist에 추가합니다. (인링크와 web_expand 옵션을 통해 앱이 아닌 웹으로 이동할 수 있습니다.) 
- [관련 스레드](https://interpark.slack.com/archives/C05GCN0AYSZ/p1710467691146349)
=> [view-utilities] 항공 시세 페이지를 routelist에 추가합니다.

packages/modals/src/login-cta-modal.tsx
loginCtaModal에서 노출 이벤트 뿐 아니라 로그인 클릭 이벤트에도 리퍼럴 이벤트를 기록하도록 수정합니다.
=> [modals] loginCtaModal의 로그인 클릭시에도 리퍼럴 이벤트를 기록하도록 수정합니다.

packages/modals/src/transition-modal.tsx, packages/review/src/components/full-list-button.tsx, packages/review/src/components/review-element/index.tsx, packages/review/src/services/use-client-actions.tsx, packages/view-utilities/src/routelist/routelist.ts
[WATF-42] 웹에서도 리뷰 더보기 버튼을 통해 리뷰 상세 페이지에 접근할 수 있도록 수정합니다.
- 기존 더보기 버튼에 있는 useAppCallback을 제거합니다.
- navigate하는 인링크 주소를 웹 주소로 변경합니다.
- routelist에 리뷰 리스트 페이지를 추가합니다.
[WATF-42]: https://inpk.atlassian.net/browse/WATF-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [review] 웹에서도 리뷰 더보기 버튼을 통해 리뷰 상세 페이지에 접근할 수 있도록 수정합니다.

packages/review/src/components/reviews-shorten.tsx, packages/review/src/customized-schedule-banner.tsx
가이드/관광지/맛집 페이지에서 맞춤 일정 추천 페이지로 랜딩하는 맞춤일정 배너를 리뷰 타이틀 아래에 노출합니다. 
https://inpk.atlassian.net/browse/WATF-48
- `Review` 컴포넌트를 렌더링하는 페이지를 구분하기 위해 `resourceType`에 타입을 설정했습니다.
https://triple-staging.titicaca-corp.com/attractions/d2d8ca79-1a9a-4c4b-9bff-7495e5d28046
=> [review] 맞춤 일정 배너를 노출합니다

package.json, packages/image-viewer/package.json, packages/image-viewer/src/detail-viewer/detail-viewer.stories.tsx, packages/image-viewer/src/detail-viewer/index.tsx, packages/image-viewer/src/image-viewer.stories.tsx, packages/image-viewer/src/image-viewer.tsx, packages/image-viewer/src/index.ts, packages/image-viewer/src/styled.d.ts, pnpm-lock.yaml
웹에서도 이미지를 확대해서 볼 수 있도록 이미지 뷰어 패키지를 생성합니다.
https://inpk.atlassian.net/browse/WATF-67
- `ImageViewerPopup` 생성
-  `imageIndex`가 있을 경우 확대뷰를 노출합니다.
- PC에서는 좌우 버튼으로, 모든 환경에서 슬라이드로 이전/다음 사진으로 이동할 수 있습니다.
=> [image-viewer] 이미지 확대뷰 팝업을 생성합니다

packages/image-viewer/package.json, packages/image-viewer/src/detail-viewer/image.tsx, packages/image-viewer/src/detail-viewer/index.tsx, pnpm-lock.yaml
이미지 확대뷰 팝업에서 이미지는 핀치 줌이 가능하도록 기능을 적용합니다. [react-zoom-pan-pinch](https://github.com/BetterTyped/react-zoom-pan-pinch) 라이브러리를 사용했습니다. 
https://inpk.atlassian.net/browse/WATF-83
- `react-zoom-pan-pinch` 라이브러리를 적용해 핀치 줌 적용
- PC에서의 확대는 막기 위해 `wheel` 이벤트는 disable했습니다.
- pan 기능 적용 시 슬라이드 기능이 제대로 작동하지 않을 수 있으므로 disable했습니다.
https://github.com/titicacadev/triple-frontend/assets/43779313/d05cea08-1613-44d8-a786-99477e8fb068
=> [image-viewer] 이미지 확대뷰에서 핀치 줌 기능을 적용합니다

packages/review/src/components/review-element/user.tsx
photo가 존재하지 않지만 badge가 존재하는 유저인 경우 뱃지가 이상한 위치에 있는 경우가 있습니다.
이를 해결하기 위해 photo가 없을 경우 디폴트 프로필을 설정합니다.
|as-is|to-be|
|-----|-----|
|<img width="268" alt="스크린샷 2024-04-02 오후 2 16 51" src="https://github.com/titicacadev/triple-frontend/assets/37494848/0cf4b904-b750-4258-9d81-469f6292d5b4">|<img width="248" alt="스크린샷 2024-04-02 오후 2 16 34" src="https://github.com/titicacadev/triple-frontend/assets/37494848/f2483940-aee3-46ef-a752-a2d196ca1efc">|
=> [reviews] 유저 photo가 없을 때 디폴트 프로필을 설정합니다.

packages/triple-document/package.json, packages/triple-document/src/elements/itinerary.tsx, packages/triple-document/src/elements/itinerary/icons.tsx, pnpm-lock.yaml
triple-document itinerary의 transportation 타입에 bike를 추가합니다.
([관련 스레드](https://interpark.slack.com/archives/C05FT7UHU7N/p1711527724887739))
- triple-content v8.23.0을 설치합니다.
- bike 아이콘을 추가하고 렌더링합니다.
=> [triple-document] itinerary의 transportation 타입에 bike를 추가합니다.

packages/image-viewer/src/image-viewer.tsx
이미지 인덱스가 0일 때 이미지 팝업이 제대로 보이지 않는 이슈를 해결합니다.
관련 스레드](https://interpark.slack.com/archives/C06FLC344Q0/p1712886342576499
https://triple-staging.titicaca-corp.com/attractions/37cd28e1-ef29-4ac5-8821-3bbdc8d52908
=> [image-viewer] 첫번째 이미지를 클릭했을 때 비정상적으로 작동하는 버그를 수정합니다.

packages/triple-document/src/elements/sticky-tabs.tsx
triple-document의 animaion 컴포넌트가 탭 컴포넌트보다 상위로 올라오는 이슈를 수정
=> [triple-document] sticky-tabs의 z-index 수정

packages/core-elements/src/elements/form-field/form-field-error.tsx, packages/core-elements/src/elements/form-field/form-field-label.tsx, packages/core-elements/src/elements/select/select.tsx
https://inpk.atlassian.net/browse/INTTNA-321
TNA 예약폼의 textarea 추가 과정에서 오류 메세지의 컬러 변경을 요청 받았는데 [트리플 컴포넌트에서 컬러 변경이 필요한 작업으로 파악](https://interpark.slack.com/archives/C06SJ6275L1/p1716339641867819?thread_ts=1715307472.107509&cid=C06SJ6275L1) 했습니다.
=> feat: form field error color 변경

packages/core-elements/src/elements/input/input.tsx
#3234 작업에서 input의 border-color 변경을 누락하여 추가합니다.
=> fix: input error border-color 변경

.storybook/main.ts, packages/triple-web/src/session/use-session-callback.mdx, stories/introduction.mdx
스토리북 문서 개선
close https://github.com/titicacadev/triple-frontend/issues/2343
- Introduction 문서 추가
- stories 폴더의 스토리 파일을 읽도록 컨픽 수정
- HTML prop, CSS prop을 controls에서 필터링
- useSessionCallback 설명 추가
=> 스토리북 문서 개선

packages/review/src/components/full-list-button.tsx, packages/review/src/services/use-client-actions.tsx
regionId 파라미터가 null string으로 넘어오는 케이스가 존재하고 있고, null string을 가지고 데이터 조회가 이뤄질때 문제가 발생하는 이슈를 수정
관련 쓰레드: [https://interpark.slack.com/archives/C05ES9XF883/p1716947868363169](https://interpark.slack.com/archives/C05ES9XF883/p1716947868363169)
- null처리 코드 추가
=> [review] 리뷰 상세 딥링크의 regionId 파라미터 null처리 추가

packages/ab-experiments/package.json, packages/constants/package.json, packages/fetcher/package.json, packages/i18n/package.json, packages/intersection-observer/package.json, packages/meta-tags/package.json, packages/middlewares/package.json, packages/react-hooks/package.json, packages/router/package.json, packages/scroll-to-element/package.json, packages/standard-action-handler/package.json, packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-widget/package.json, packages/triple-document/package.json, packages/triple-email-document/package.json, packages/triple-fallback-action/package.json, packages/triple-header/package.json, packages/triple-web-nextjs-pages/package.json, packages/triple-web-nextjs/package.json, packages/triple-web-test-utils/package.json, packages/triple-web-utils/package.json, packages/triple-web/package.json, packages/type-definitions/package.json, packages/view-utilities/package.json, vite.config.mts
ES Module 빌드
- vite 컨픽을 esm 빌드가 가능하도록 수정했습니다.
- package.json에 module, sideEffects 필드를 추가합니다.
triple-newsletter-web 기준으로 아래만큼 tree shaking이 적용된 결과입니다.
기존
```
Route (pages)                                 Size     First Load JS
┌   /_app                                     0 B             452 kB
├ λ /404                                      1.06 kB         454 kB
├ λ /api/health-check                         0 B             452 kB
├ λ /articles                                 494 B           548 kB
├ λ /articles/[articleId]                     302 B           548 kB
├ λ /lists/[listId]/[subscriptionId]/confirm  345 B           453 kB
├ λ /lists/[listId]/[subscriptionId]/error    334 B           453 kB
├ λ /lists/[listId]/subscribe                 24.9 kB         488 kB
├ λ …
```
=> ES Module 빌드

packages/react-contexts/src/session-context/user.ts
[react-hooks] user 타입에 email 필드를 추가합니다.
- GET /users/me API 응답값으로 email 필드가 추가되었습니다. ([관련 스레드](https://interpark.slack.com/archives/C05F55SBPJ5/p1720074623701829))
=> [react-hooks] user 타입에 email 필드를 추가합니다.

packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.tsx, packages/chat/src/bubble/image.tsx, packages/chat/src/bubble/images.stories.tsx, packages/chat/src/bubble/parent/parent-message.tsx, packages/chat/src/bubble/parent/parent-ui.tsx, packages/chat/src/bubble/text.tsx, packages/chat/src/bubble/type.ts, packages/chat/src/messages/index.tsx
지오챗 버블 버그를 수정합니다. 
- 이미지 버블에도 onLongPress 적용
- 이미지 버블에도 id값을 추가하여 메세지 스크롤이 가능하도록 설정
- altered text가 노출되지 않는 문제 수정
- 부모메세지 onClick 추가
=> [chat] 지오챗 버블의 기능을 추가합니다.

packages/tds-widget/src/image-carousel/video-content.tsx, packages/tds-widget/src/location-properties/location-properties.tsx, packages/tds-widget/src/poi-detail/image-carousel/carousel.tsx
- `ImageCarousel`관련 prop type이 수정되었다가 원상복구되었는데, 그 때 원복되지 않은 prop 부분을 원복합니다(이미지 height가 적용되지 않고 있었음).
- PC 웹 환경에서 비디오가 autoplay 되도록 설정합니다.
`LocationProperties`의 prop 타입 중 `onCopy`가 html div element의 prop 타입과 중복되어 제대로 추론되지 않는 부분을 수정합니다.
=> [v14] POI 대표 이미지 오류 수정

packages/tds-widget/src/scrap/context.ts, packages/tds-widget/src/scrap/provider.tsx, packages/tds-widget/src/scrap/use-scrap.ts
기존 v13에서 제공되던 `beforeScrpaedChange` prop을 복구합니다.
=> [v14] beforeScrapedChange prop 복구

packages/footer/src/award-footer.tsx, packages/footer/src/default-footer.tsx, packages/footer/src/triple-korea-link.tsx
[footer] 푸터에 트리플 코리아 링크를 추가합니다. ([관련 스레드](https://interpark.slack.com/archives/C06FLC344Q0/p1725240597158199))
- 인트로용 AwardFooter에는 트리플 코리아 링크 상시 노출, 이외 DefaultFooter는 props로 노출 여부를 선택할 수 있도록 작성했습니다.
=> [footer] 푸터에 트리플 코리아 링크를 추가합니다.

packages/react-contexts/src/images-context/index.tsx, packages/react-contexts/src/images-context/reducer.ts, packages/react-contexts/src/images-context/types.ts, packages/react-contexts/src/images-context/use-fetch-images.tsx
images-api v2를 `ImagesContext`에 적용합니다. v2에서는 컨텐츠 이미지 API와 리뷰 이미지 API가 분리됨에 따라 상황에 맞게 엔드포인트를 설정해 fetch 합니다. [API 문서](https://inpk.atlassian.net/wiki/spaces/dev/pages/480903530/API)
- `defaultImages` 설정
- 현재 대부분의 사용부에서는 `ImagesProvider`의 `images` prop에 대표 이미지를 넣어주고 있습니다. 기존에는 API에 `categoryOrder` 쿼리가 없었기 때문에 모든 카테고리의 이미지를 불러왔었습니다. 따라서 `ImagesProvider`에 대표 이미지를 `images`에 넣어주어도 provider 내에서 실행되는 fetch의 응답에 포함되는 것을 막을 방법이 없었습니다. 하지만 V2에서는 `categoryOrder`을 설정할 수 있게 되었습니다. 따라서 기존 사용부의 코드를 변경하지 않으며 대표 이미지는 다시 fetch 하지 않을 수 있도록 기본 `categoryOrder`에는 대표 이미지를 제외하였습니다. 
- `useFetchImages` hook 분리
- 데이터를 fetch해오는 부분을 hook으로 분리하여 이미지를 다루는 부분과 fetch하는 부분의 관심사를 나누었습니다. 따라서 Provider 내부에서는 fetch end point를 신경 쓸 필요 없이 `fetchImages` 함수를 사용하면 됩니다.
=>  [react-contexts] images-api v2 적용

packages/review/src/components/infinite-list/services.ts, packages/review/src/components/reviews-shorten.tsx, packages/review/src/components/shorten-list/services.ts, packages/review/src/services/use-reviews.ts
`react-query`에서는 새 데이터를 보장하기 위해 화면에 포커싱이 되면 refetch를 하는 `refetchOnWindowFocus`를 기본으로 `true`로 설정합니다. 화면이 렌더링된 이후 화면을 누르면 해당 옵션이 실행되어 gql 쿼리가 새로 실행됩니다. 각 상세 페이지들의 리뷰 컴포넌트에서는 항상 새로운 리뷰를 보장할 필요는 없으므로 해당 옵션을 `false`로 설정하여 refetch를 방지합니다.
`Review-Shorten` 컴포넌트 내에서 사용되는 쿼리들에 `refetchOnWindowFocus` 옵션을 `false`로 설정합니다.
`Review-Infinite` 컴포넌트 내에서 사용되는 쿼리들에 `refetchOnWindowFocust` 옵션을 `false`로 설정합니다.
- 적용했습니다.
https://triple-dev.titicaca-corp.com/attractions/37cd28e1-ef29-4ac5-8821-3bbdc8d52908
https://triple-dev.titicaca-corp.com/reviews/list?_triple_no_navbar&region_id=71476976-cf9a-4ae8-a60f-76e6fb26900d&resource_id=37cd28e1-ef29-4ac5-8821-3bbdc8d52908&resource_type=attraction&recent_trip=false&sorting_type=poi&sorting_option=recommendation&has_media=false
=> [KLZT-103] 리뷰 컴포넌트 렌더링 버그를 수정합니다.

packages/react-contexts/src/scraps-context/api-client.ts, packages/react-contexts/src/scraps-context/scraps-context.tsx
[react-contexts] ScrapProvider에서 스크랩 실패 시 콜백함수를 props로 받습니다.
=> [react-contexts] ScrapProvider에서 스크랩 실패 시 콜백함수를 props로 받습니다.

CHANGELOG.md, lerna.json, packages/ab-experiments/package.json, packages/constants/package.json, packages/fetcher/package.json, packages/i18n/package.json, packages/intersection-observer/package.json, packages/meta-tags/package.json, packages/middlewares/package.json, packages/react-hooks/package.json, packages/router/package.json, packages/scroll-to-element/package.json, packages/standard-action-handler/package.json, packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-widget/package.json, packages/triple-document/package.json, packages/triple-email-document/package.json, packages/triple-fallback-action/package.json, packages/triple-header/package.json, packages/triple-web-nextjs-pages/package.json, packages/triple-web-nextjs/package.json, packages/triple-web-test-utils/package.json, packages/triple-web-utils/package.json, packages/triple-web/package.json, packages/type-definitions/package.json, packages/view-utilities/package.json
Release v14.0.1
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- i18next 제거 & triple-web에 i18n context 추가 [#3387](https://github.com/titicacadev/triple-frontend/pull/3387)
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- i18next 제거 & triple-web에 i18n context 추가 [#3387](https://github.com/titicacadev/triple-frontend/pull/3387)
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- 스토리북 8 업그레이드 [#3341](https://github.com/titicacadev/triple-frontend/pull/3341)
- i18next 제거 & triple-web에 i18n context 추가 …
=> Release v14.0.1

packages/review/src/components/sorting-options.tsx
리뷰 정렬 옵션을 변경하면 focusable한 첫번째 element로 포커싱이 되어 outline이 보이는 버그가 있었습니다. 이는 리뷰 정렬 옵션 모달을 여는 클릭커블 element가 focusable하지 않아 모달이 닫혔을 때 모달이 열리기 전 포커싱이 되었던 target (FocusEvent의 relatedTarget)을 찾을 수 없기 때문에 발생한 현상입니다. 
위의 현상을 해결하기 위해서는 `SortingOptions` 컴포넌트에 `tabindex`를 설정하거나, `SortingOptions`를 focusable한 element로 변경하는 두 가지 방법이 있습니다. 
`SortingOptions`는 버튼의 역할을 하고 있기 때문에 후자의 방법을 선택했습니다. 
- `SortingOptions` 컴포넌트 최상위 element를 `button`으로 변경
https://github.com/user-attachments/assets/1d340da4-8322-4f7e-a2d8-32ed8da1f6f1
https://github.com/user-attachments/assets/15d16c88-cc02-4735-bbd4-199dfb93fc3b
=> [KLZT-655] 리뷰 정렬 옵션 변경 시 무관한 element로 포커싱이 되는 버그를 수정합니다. 

packages/triple-web/src/client-app/use-client-app-callback.mdx, packages/triple-web/src/client-app/use-client-app-callback.test.tsx, packages/triple-web/src/client-app/use-client-app-callback.ts
useClientAppCallback의 fn, appInstallCtaModalOptions 파라미터 순서 변경
[triple-web]
useClientAppCallback의 fn 파라미터는 필수고, appInstallCtaModalOptions 파라미터는 optional이므로 서로 순서를 바꿉니다.
=> useClientAppCallback의 fn, appInstallCtaModalOptions 파라미터 순서 변경

packages/modals/src/modal/modal-actions.tsx, packages/standard-action-handler/src/converse.tsx
converse에서 fetch하는 API가 400, 401 statusCode를 응답하는 경우, 로그인 유도 모달을 노출합니다. 
[관련 스레드](https://interpark.slack.com/archives/C05GCN0AYSZ/p1729488212013569?thread_ts=1728976527.666029&cid=C05GCN0AYSZ)
- API의 response status가 400, 401일 경우 로그인 유도 모달을 노출
- `Children.count(children)`를 `Children.toArray(children).length`로 변경
- `Children.count(children)`의 경우에는 Empty Node인 경우에도 children으로 간주해 숫자에 포함합니다. Empty Node는 children에서 제외하기 위해 `Chilren.toArray` 메소드로 변경했습니다. 
https://triple-dev.titicaca-corp.com/articles/5aa78dc9-07a6-46ec-b662-38a3fbcb7c1f
=> [KLZT-663] converse에 로그인 유도 모달을 추가합니다

packages/tds-widget/src/scrap/provider.tsx
`ScrapsProvider`에 `onScrapeFailed` prop을 넘길 수 있도록 추가합니다.
v13 변경분을 v14에 업데이트시 누락된것으로 보입니다.
- 관련 PR : https://github.com/titicacadev/triple-frontend/pull/3418/files
=> ScrapsProvider에 onScrapeFailed prop 넘길 수 있도록 추가

packages/react-contexts/package.json, packages/search/package.json, packages/standard-action-handler/package.json, pnpm-lock.yaml
아래 패키지들의 triple-web-to-native-interfaces 패키지를 의존성으로 설치되어 있고, v1.9.0 -> v1.10.0으로 업데이트
standard-action-handler
react-context
search
=> triple-web-to-native-interfaces 패키지 버전업 대응

packages/tds-ui/src/components/carousel/carousel.stories.tsx, packages/tds-ui/src/components/carousel/carousel.tsx
tds-ui의 Carousel 컴포넌트도 tds-widget의 FlickingCarousel과 동일하게 containerPadding, margin prop을 받도록 합니다.
[tds-ui]
- Carousel containerPadding, margin prop 복구
=> Carousel containerPadding, margin prop 복구

packages/react-contexts/src/images-context/index.tsx, packages/react-contexts/src/images-context/use-fetch-images.tsx
- 호텔 POI의 경우 이미지 카테고리가 'images' 한가지로 되어있어 `category_order`가 적용되지 않아 `defaultImage`와 fetch된 이미지 일부가 중복되는 오류가 발생하고 있었습니다. 첫 호출 시 `defaultImage`와 중복되는 이미지가 필터링 될 수 있도록 수정합니다. 
- review 이미지가 존재하지 않는 경우 페이지네이션이 동작하지 않는 오류를 수정합니다. [7912983](https://github.com/titicacadev/triple-frontend/pull/3474/commits/7912983b2f31099af328e1b715207544a9eccb5a)
- as-is
https://github.com/user-attachments/assets/e37e4809-cdf4-48ae-9714-90fe9ac98979
- to-be
https://github.com/user-attachments/assets/3202555c-02b7-48b0-87c6-bb9f604e9847
=> [INTHOTEL-2407] defaultImage와 중복되는 이미지 필터링

CHANGELOG.md, lerna.json, packages/ab-experiments/package.json, packages/constants/package.json, packages/fetcher/package.json, packages/i18n/package.json, packages/intersection-observer/package.json, packages/meta-tags/package.json, packages/middlewares/package.json, packages/react-hooks/package.json, packages/router/package.json, packages/scroll-to-element/package.json, packages/standard-action-handler/package.json, packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-widget/package.json, packages/triple-document/package.json, packages/triple-email-document/package.json, packages/triple-fallback-action/package.json, packages/triple-header/package.json, packages/triple-web-nextjs-pages/package.json, packages/triple-web-nextjs/package.json, packages/triple-web-test-utils/package.json, packages/triple-web-utils/package.json, packages/triple-web/package.json, packages/type-definitions/package.json, packages/view-utilities/package.json
- triple-web 테스트 추가 [#3472](https://github.com/titicacadev/triple-frontend/pull/3472)
- Link 컴포넌트에서 불필요한 inline style 제거 [#3482](https://github.com/titicacadev/triple-frontend/pull/3482)
- 타입 에러 수정 [#3471](https://github.com/titicacadev/triple-frontend/pull/3471)
- Card radius prop 이름 변경 [#3463](https://github.com/titicacadev/triple-frontend/pull/3463)
- Carousel containerPadding, margin prop 복구 [#3470](https://github.com/titicacadev/triple-frontend/pull/3470)
- 타입 에러 수정 [#3471](https://github.com/titicacadev/triple-frontend/pull/3471)
- ScrapsProvider에 onScrapeFailed prop 넘길 수 있도록 추가 [#3469](https://github.com/titicacadev/triple-frontend/pull/3469)
- 타입 에러 수정 [#3471](https://github.com/titicacadev/triple-frontend/pull/3471)
- 13.35.0 - 13.36.0 변경사항을 14에 반영 …
=> Release v14.0.4

packages/tds-widget/src/scrap/use-scrap.ts
[관련 스레드](https://nol-universe.slack.com/archives/C05EUG8UYP6/p1732856084450209) 기존에 `content-web`에서 앱 외부에서도 스크랩할 수 있는 기능이 있었으므로 앱 외부에서도 스크랩이 가능하도록 수정합니다. 
앱 외부에서도 스크랩이 가능하도록 `onScrape`과 `onUnscrape`에 `scrapableInApp` 옵션을 추가합니다.
=> 앱 외부에서도 스크랩이 가능하도록 옵션 추가

packages/router/src/links/use-open-native-link.ts, packages/triple-web-nextjs-pages/src/providers/client-app.ts, packages/triple-web-nextjs/src/providers/client-app.ts, packages/triple-web-utils/src/check-client-app.test.ts, packages/triple-web-utils/src/regex.ts, packages/triple-web/src/i18n/context.ts
https://nol-universe.slack.com/archives/C05EUG8UYP6/p1732686467091999
client user agent regex 수정
- capture group을 Triple-iOS / Triple-Android로 수정합니다. 
- global modifier를 제거합니다. test 호출마다 true false를 반복했는데 일정한 결과를 반환하게 합니다. session provider에서 isClientApp 체크가 정상적으로 통과하게 됩니다.
client app provider 함수의 metadata.name 수정
- string 대신 enum이 전달되게 합니다.
open native link의 페이지 이동이 두번 호출되는 문제 수정
- 원인은 모르겠는데 self가 아니라 blank로 이동하면 해결이 됩니다.
i18n context에 `'use client'` 추가
- 	next 13에서 app router 지원
=> 앱에서 navigate 동작 수정

CHANGELOG.md, lerna.json, packages/ab-experiments/package.json, packages/constants/package.json, packages/fetcher/package.json, packages/i18n/package.json, packages/intersection-observer/package.json, packages/meta-tags/package.json, packages/middlewares/package.json, packages/react-hooks/package.json, packages/router/package.json, packages/scroll-to-element/package.json, packages/standard-action-handler/package.json, packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-widget/package.json, packages/triple-document/package.json, packages/triple-email-document/package.json, packages/triple-fallback-action/package.json, packages/triple-header/package.json, packages/triple-web-nextjs-pages/package.json, packages/triple-web-nextjs/package.json, packages/triple-web-test-utils/package.json, packages/triple-web-utils/package.json, packages/triple-web/package.json, packages/type-definitions/package.json, packages/view-utilities/package.json
- [view-utilities, router] routelist에 라운지홈을 추가합니다. useNavigate에서 deeplink 이동 로직을 추가합니다 [#3486](https://github.com/titicacadev/triple-frontend/pull/3486)
- 앱에서 navigate 동작 수정 [#3487](https://github.com/titicacadev/triple-frontend/pull/3487)
- 앱 외부에서도 스크랩이 가능하도록 옵션 추가 [#3489](https://github.com/titicacadev/triple-frontend/pull/3489)
- 앱에서 navigate 동작 수정 [#3487](https://github.com/titicacadev/triple-frontend/pull/3487)
- LoginCtaModal 기본 return url에서 hash 제거 [#3488](https://github.com/titicacadev/triple-frontend/pull/3488)
- 앱에서 navigate 동작 수정 [#3487](https://github.com/titicacadev/triple-frontend/pull/3487)
- 앱에서 navigate 동작 수정 [#3487](https://github.com/titicacadev/triple-frontend/pull/3487)
- 앱에서 navigate 동작 수정 [#3487](https://github.com/titicacadev/triple-frontend/pull/3487)
- …
=> Release v14.0.5

packages/triple-web/README.md, packages/triple-web/src/event-tracking/libs/firebase-analytics.ts, packages/triple-web/src/event-tracking/use-set-firebase-user-id.ts, packages/triple-web/src/event-tracking/utils/track-event.ts, packages/triple-web/src/event-tracking/utils/track-screen.ts, packages/triple-web/src/providers/event-tracking-provider.tsx
[triple-web] firebaseAnalytics 인스턴스를 가져오지 못하는 이슈를 해결합니다. ([관련 스레드](https://nol-universe.slack.com/archives/C05EUG8UYP6/p1733205629592129))
- trackEvent에서 firebaseAnalytics 인스턴스를 가져오지 못해 FA 이벤트를 로깅하지 못하는 이슈를 해결합니다.
- getFirebaseAnalytics 함수를 만들어 trackEvent 시 인스턴스를 get 혹은 initialize하도록 수정했습니다.
- **각 레포에서 initializeApp(firebase)과 initializeAnalytics를 같이 해주어야합니다.**
=> [triple-web] firebaseAnalytics 인스턴스를 가져오지 못하는 이슈를 해결합니다.

packages/triple-web-nextjs/src/event-tracking-provider.tsx, packages/triple-web/src/providers/event-tracking-provider.tsx
[triple-web-nextjs] 모달을 띄울 때 trackScreen이 호출되는 문제를 해결합니다.
hash값이 변할 때마다 next의 searchParams가 영향을 받아 trackScreen이 호출되고 있습니다.
trackScreen이 걸린 useEffect에 걸린 utm 디펜던시를 삭제합니다.
=> [triple-web] 모달을 띄울 때 trackScreen이 호출되는 문제를 해결합니다.

packages/triple-web/src/modal/components/login-cta-modal.tsx
AOS 브라우저에서 로그인 모달이 정상적으로 동작하지 않는 이슈를 해결합니다. `Confirm` 컴포넌트에서는 `onClose`가 있는 경우, `onConfirm`과 `onClose` 함수 실행 이후에 `onClose`를 실행합니다. [AOS에서는 `removeUriHash` 실행 시 `back`](https://github.com/titicacadev/triple-frontend/blob/main/packages/triple-web/src/hash-router/context.tsx#L65-L67)이 실행됩니다. 따라서 로그인 모달에서 아래와 같은 동작이 발생합니다.
- `취소` 클릭 시
- `removeUriHash`가 두 번 실행되어 페이지가 뒤로 이동  
- `확인` 클릭 시
-  `window.location.href` 동작 후 `removeUriHash`가 실행되어 페이지 이동 없음
이를 방지하고 정상적으로 동작하게 하기 위해 `return true`를 추가합니다. [`Confirm` 컴포넌트 내에서 `return false`로 간주](https://github.com/titicacadev/triple-frontend/blob/main/packages/tds-ui/src/components/confirm/confirm.tsx#L27-L33)되어 `onClose`가 동작하지 않습니다. 
- `LoginCtaModal`의 `onConfirm`과 `onCancel`에 `return true` 추가
- 위와 같이 수정 후 로그인 페이지로 이동했다가 뒤로가기로 원 페이지에 복귀 시 hash 값이 지워지지 …
=> [triple-web] 로그인 모달 버튼 함수 수정

packages/middlewares/README.md, packages/middlewares/src/constants.ts, packages/middlewares/src/session-cookie.ts
`/users/me`와 `/session/token`은 관련 쿠키가 없는 경우에도 401 응답을 반환합니다. 따라서 세션과 관련한 쿠키가 있는 경우에만 sessionCookieMiddleware 로직이 실행되도록 수정합니다. 
path type을 regex로 변경합니다 .
=> [middleware] 세션 쿠키 리프레시 로직을 수정합니다. 

packages/triple-media/src/triple-media.tsx, packages/type-definitions/src/image.ts
컨텐츠 어드민 (POI, Article)에서 영상 업로드시 "videoInitiallyMuted"라는 상태값을 추가하는 변경을 작업하는 중입니다.
각 도메인의 payload의 이미지들이 이제 영상일 경우 선택적으로 "videoInitiallyMuted"라는 플래그를 갖게 되며, 만약 이 플래그가 
True일 경우 영상재생시 기본 음소거 상태가 되어야합니다. 
[요구사항 링크](https://docs.google.com/spreadsheets/d/154kcdWRellyrPQbsAC8WXreJgV0fVaRtlXnQdR6C20g/edit?gid=0#gid=0)
필드가 옵셔널이기 때문에, API의 동작여부와 별개로 영향도가 존재하지 않습니다.
tds-widget의 Media Component에서 initiallyMuted 플래그가 있을 시 영상을 재생해도 기본 음소거가 되어야합니다.
tds-widget은 리뷰/트리플도큐먼트에서 모두 사용하는 것으로 확인되었습니다.
현재 기준으로 이 음소거는 유저의 행동에 의해 해제될 수 있습니다.
=> KLZT-766 영상기본음소거

packages/triple-web/src/event-tracking/utils/track-event.ts
기존에 웹뷰에서는 웹 이벤트 로깅을 하지 않도록 하는 로직을 복구합니다. 
https://github.com/titicacadev/triple-frontend/blob/v13/packages/react-contexts/src/event-tracking-context/event-tracking-context.tsx#L113-#L125
=> [triple-web] web track event는 클라이언트 웹뷰가 아닐 때만 로깅하도록 수정합니다. 

packages/triple-email-document/src/elements/heading.tsx, packages/triple-email-document/src/elements/index.ts, packages/triple-email-document/src/elements/links.test.tsx, packages/triple-email-document/src/elements/links.tsx, packages/triple-email-document/src/links.stories.tsx
컨텐츠 어드민 개선사항으로 다음과 같은 작업을 진행합니다.
- default 링크 스타일을 추가합니다. ([관련 스레드](https://nol-universe.slack.com/archives/C05ES3E2VL2/p1734679277134149))
- triple-document의 default 링크 스타일을 triple-email-document에도 추가합니다. 스타일 외 기능은 동일합니다.
- 스크롤 포커싱 이슈를 해결합니다.
- triple-email-document의 element로 id값이 주입되지 않는 문제를 해결합니다.
=> [triple-email-template] default 링크 스타일을 추가하고, 스크롤 포커싱 이슈를 해결합니다.

packages/tds-ui/src/components/tabs/tab-base.tsx, packages/tds-ui/src/components/tabs/tabs-context.tsx, packages/tds-ui/src/components/tabs/tabs.tsx
~~`onClick`과 `onFocus` 모두에서 `onChange` 함수를 실행하고 있어 클릭 이벤트 발생 시 `onChange`가 두 번 실행되고 있습니다. 이에 `onFocus`에서만 실행하도록 수정합니다.~~
하단 논의사항에 대한 코멘트들을 참고하여 `onChange` 함수를 `Tabs` 컴포넌트에서 실제 선택된 값이 바뀌었는지 확인 후 실행하도록 수정했습니다. 
페이지를 벗어났다가 다시 접속해서 새로운 탭을 클릭하는 등의 상황에서도 `onFocus`가 실행됩니다. 이 때문에 사용자가 탭과 직접 인터렉션을 하지 않아도 `onChange`가 실행되게 됩니다. 이는 `value`가 바뀌었을 때 실행되어야 하는 `onChange` 함수의 의도와는 다른 시점에 실행되고 있습니다. 그러나 `Tab`의 상위에서 `value`를 관리하는 로직이 아니기 때문에 현재로서는 `Tabs`에 넘겨주는 `onChange` 내에서 구분하는 방법을 사용하는 것이 최선인데요, 더 나은 방법이 있을까요?
=> [tds-ui] onChange 함수가 중복 실행되지 않도록 수정합니다. 

CHANGELOG.md, lerna.json, packages/ab-experiments/package.json, packages/constants/package.json, packages/fetcher/package.json, packages/i18n/package.json, packages/intersection-observer/package.json, packages/meta-tags/package.json, packages/middlewares/package.json, packages/react-hooks/package.json, packages/router/package.json, packages/scroll-to-element/package.json, packages/standard-action-handler/package.json, packages/tds-theme/package.json, packages/tds-ui/package.json, packages/tds-widget/package.json, packages/triple-document/package.json, packages/triple-email-document/package.json, packages/triple-fallback-action/package.json, packages/triple-header/package.json, packages/triple-web-nextjs-pages/package.json, packages/triple-web-nextjs/package.json, packages/triple-web-test-utils/package.json, packages/triple-web-utils/package.json, packages/triple-web/package.json, packages/type-definitions/package.json, packages/view-utilities/package.json
- App router에서 use client 문제 수정 [#3514](https://github.com/titicacadev/triple-frontend/pull/3514)
- [tds-ui] onChange 함수가 중복 실행되지 않도록 수정합니다. [#3532](https://github.com/titicacadev/triple-frontend/pull/3532)
- App router에서 use client 문제 수정 [#3514](https://github.com/titicacadev/triple-frontend/pull/3514)
- v13.39.0 수정사항을 반영합니다. [#3519](https://github.com/titicacadev/triple-frontend/pull/3519)
- App router에서 use client 문제 수정 [#3514](https://github.com/titicacadev/triple-frontend/pull/3514)
- triple-web-nextjs-pages에 ssr-utils 추가 [#3518](https://github.com/titicacadev/triple-frontend/pull/3518)
- App router에서 use client 문제 수정 [#3514](https://github.com/titicacadev/triple-frontend/pull/3514)
- triple-web-nextjs-pages에 ssr-utils 추가 [#3518](https://github.com/titicacadev/triple-frontend/pull/351 …
=> 🚀 Release v14.0.9

packages/triple-web/src/event-tracking/utils/track-screen.ts
https://github.com/titicacadev/triple-frontend/pull/3507 에 이어 trackScreen도 웹뷰일 때와 일반 웹일 때를 분리해 로깅하도록 수정합니다. 
https://github.com/titicacadev/triple-frontend/blob/v13/packages/react-contexts/src/event-tracking-context/event-tracking-context.tsx#L203-L210
=> [triple-web] 웹뷰에서는 nativeTrackScreen만 실행하도록 수정합니다. 

CHANGELOG.md, packages/tds-widget/src/footer/company-info.tsx
v13.40.0 변경사항을 적용합니다.
- https://github.com/titicacadev/triple-frontend/pull/3544
=> v13.40.0 변경사항을 적용합니다.

MIGRATION.md, packages/chat/package.json, packages/chat/src/bubble/bubble-ui.tsx, packages/chat/src/bubble/bubble.stories.tsx, packages/chat/src/bubble/image.tsx, packages/chat/src/bubble/images.stories.tsx, packages/chat/src/bubble/text.tsx, packages/chat/src/bubble/type.ts, packages/chat/src/chat/chat-scroll-container.tsx, packages/chat/src/utils/a-tag-navigator.ts, packages/chat/src/utils/image.ts, pnpm-lock.yaml
chat 패키지 내부의 트리플 앱 기반 동작을 제거하고 외부에서 주입하도록 합니다.
현재 chat 패키지는 트리플 앱 기반의 서비스(triple-chat-web) 뿐만 아니라 파트너센터에서도 사용되고 있으며, 
triple-chat-web은 타 도메인(ex. 인터파크)에서도 사용될 수 있도록 확장하는 작업을 진행중입니다.
- ChatScrollContainer 내부에서 트리플-iOS 앱인 경우 스크롤 시 키보드를 닫아주는 동작 => [onIosTouchMove](https://github.com/titicacadev/triple-frontend/pull/3554/files#diff-beb4ce88859ddfa26624b02913bccd91864058351412b2d9b490be9fc38d5ba4R16) 프롭스로 전환 
- TextBubble 내부에서 a 링크 이동시 사용하는 @titicaca/router 동작 => `onTextBubbleLinkClick` 프롭스로 전환하고, 해당 프롭이 없는 경우 `window.open` 실행
- ImageBubble 클릭 시 이미지 뷰어로 이동하는 동작 => `onImageBubbleClick`로 전환
- [마이그레이션 가이드](https://yanoljagroup.atlassian.net/wiki/spaces/dev/pages/1762068097/triple-frontend+13+13.42.0)
=> (chat) 트리플 앱 디펜던시 제거

packages/router/src/navigate/use-navigate.ts
[openNativeLink](https://github.com/titicacadev/triple-frontend/blob/main/packages/router/src/links/use-open-native-link.ts#L13-L16)는 인자로 href가 아닌 path를 받고, 내부에서 appUrlScheme을 추가해주고 있습니다.
반면 이를 사용하는 useNavigate 내의 navigateInApp에서는 openNativeLink에 appUrlScheme을 포함하는 href를 인자로 넣어주고 있어 appUrlScheme이 중복해서 들어가는 이슈가 있습니다. 
openNativeLink에서 href가 아닌 path를 param으로 넘겨주도록 수정합니다.
=> [router] openNativeLink에서 href가 아닌 path를 param으로 넘겨주도록 수정

.storybook/decorators.tsx, .storybook/main.ts, packages/footer/src/award-footer.stories.tsx, packages/footer/src/award-footer.tsx, packages/footer/src/company-info.tsx, packages/footer/src/default-footer.tsx, packages/footer/src/extra-link-group.tsx, packages/footer/src/extra-link.tsx, packages/footer/src/footer.json, packages/footer/src/footer.stories.tsx, packages/footer/src/link-group.tsx, packages/footer/src/type.ts, packages/footer/src/use-company-info.tsx, packages/footer/src/use-footer-info.tsx, packages/react-contexts/src/env-context/index.tsx
[footer] footer를 json으로 받아올 수 있도록 수정합니다.
[react-contexts] webAssetsUrl 환경변수를 추가합니다. 🚨 푸터를 사용하는 레포에서는 EnvContext에 해당 변수를 추가해야 합니다.
- footer를 json 형식으로 web-assets에서 받아올 수 있도록 수정 ([관련 PR](https://github.com/titicacadev/triple-web-assets/pull/302))
- link의 css 변경 (단어 줄바꿈 방지)
- storybook 빌드 이슈로 middleware 패키지를 스토리북 빌드에서 제외합니다.
=> [footer, react-contexts] 푸터 정보를 footer.json으로 관리하도록 수정합니다.

packages/tds-widget/src/chat/bubble/bubble-ui.tsx, packages/tds-widget/src/chat/bubble/bubble.tsx, packages/tds-widget/src/chat/bubble/parent/index.ts, packages/tds-widget/src/chat/bubble/parent/parent-ui.tsx, packages/tds-widget/src/chat/bubble/text.tsx, packages/tds-widget/src/chat/bubble/type.ts
TF 14 마이그레이션 중, 누락된 타입 export 및 props를 추가합니다.
- bubble/parent index 파일 추가
- FullTextView 관련 프롭스 추가
https://github.com/user-attachments/assets/06348fd4-dadf-4d42-a302-133be201032d
=> (Chat) 누락된 타입 export 및 props 추가

packages/react-contexts/package.json, packages/react-contexts/src/middlewares/chain.ts, packages/react-contexts/src/middlewares/constants.ts, packages/react-contexts/src/middlewares/index.ts, packages/react-contexts/src/middlewares/old-triple-ios-cookie.ts, packages/react-contexts/src/middlewares/refresh-session.ts, packages/react-contexts/src/middlewares/set-web-device-id.ts, packages/react-contexts/src/middlewares/types.ts, packages/react-contexts/src/middlewares/utils/get-triple-app.ts, packages/react-contexts/src/user-agent-context/utils.ts, pnpm-lock.yaml
- 쿠키에 x-triple-web-device-id가 없다면 추가하는 setWebDeviceIdMiddleware를 작성했습니다.
- 기존 chain 함수가 마지막 middleware만 적용되는 문제가 있었습니다. 모든 middleware가 적용될 수 있도록 수정했습니다.
=> [react-contexts] 트리플 deviceId를 추가하는 미들웨어를 작성합니다.

packages/tds-widget/src/chat/bubble-container/bubble-container.tsx, packages/tds-widget/src/chat/bubble-container/bubble-info.tsx, packages/tds-widget/src/chat/messages/date-divider.tsx, packages/tds-widget/src/chat/messages/index.tsx
- 채팅 버블 부가정보(dateDivider, unreadCount, dateTime, profile, thanks)의 스타일을 커스텀할 수 있도록 합니다.
|기본|커스텀|
|---|---|
|![스크린샷 2025-03-10 오후 1 56 50](https://github.com/user-attachments/assets/507b199f-1a29-4ad8-b903-0b6a0cc5767b)|![스크린샷 2025-03-10 오후 1 43 23](https://github.com/user-attachments/assets/02ecf801-97db-4a85-a46e-96864b9e906e)|
=> (Chat) 채팅 버블 부가 정보 커스텀 스타일 프롭스 추가

packages/public-header/src/side-menu/profile.tsx, packages/react-contexts/src/session-context/index.tsx, packages/react-contexts/src/session-context/user.ts, packages/ui-flow/src/auth-guard/index.ts
NOL 연동 회원의 경우 웹 사이드바 프로필에서 auth provider(카카오톡, 네이버 등) 정보 대신 `NOL 멤버스 계정` 문구를 노출합니다.
|기존 회원|NOL 연동 회원|
|-----|-----|
|<img width="325" alt="스크린샷 2025-03-11 오후 2 34 15" src="https://github.com/user-attachments/assets/c9d75fda-ad89-437d-b204-3159c8292ac9" />|<img width="325" alt="tobe" src="https://github.com/user-attachments/assets/fe438b01-9538-4e83-8a49-7ae66a4e687d" />|
=> [public-header, react-contexts] NOL 연동 회원의 경우 웹 사이드바 프로필에서 provider를 노출하지 않습니다.

packages/tds-widget/src/chat/chat/chat-scroll-container.tsx
- tds-widget/chat에서 triple-web 디펜던시를 제거합니다.
- `onIosTouchMove` => `onTouchMove`로 변경하고, ChatScrollContainer 내부에서 os 확인하는 로직을 제거합니다.
- 이에따라, 외부에서 os를 확인하여 프롭스를 전달해야 합니다.
https://github.com/user-attachments/assets/0c7a1276-5ee7-4dd9-bbc2-5536cdda8959
=> tds-widget/chat에서 triple-web 디펜던시를 제거

packages/view-utilities/src/routelist/routelist.spec.ts, packages/view-utilities/src/routelist/routelist.ts
[view-utilities] routelist의 static-pages 정규식을 수정하고 테스트 코드를 추가합니다. (테스트 코드의 중요성..😂)
- 기존 정규식 `/^\/pages\/?$/`은 `/pages/` 경로만 허용합니다. (하위 경로 허용x)
- `/pages`, `/pages/` 및 `/pages/` 이하의 하위경로까지 포함하는 regex로 수정합니다.
=> [view-utilities] routelist의 static-pages 정규식을 수정합니다.

packages/react-contexts/src/middlewares/set-web-device-id.ts
[react-contexts] setWebDeviceId 미들웨어에 domain을 추가합니다.
- 도메인이 없으면 API 호출시 x-triple-web-device-id가 중복되어 보내지는 이슈가 있습니다. 도메인을 설정하여 쿠키가 중복되지 않도록 합니다.
=> [react-contexts] setWebDeviceId 미들웨어에 domain을 추가합니다.

packages/public-header/src/side-menu/profile.tsx, packages/react-contexts/src/session-context/index.tsx, packages/react-contexts/src/session-context/user.ts
[public-header] provider 타입 추가에 따른 프로필 변경
- NOL 회원 통합으로 provider에 'INVALID' 타입이 추가되었습니다. 이에 따라 NOL 연동 회원의 경우 기존에 선언되었던 아이콘과 라벨을 찾지 못해 아이코가 뜨는 문제가 있습니다. 
- UI에서는 INVALID 타입을 사용하지 않으며, nolConnected 여부로 UI를 판단하도록 수정했습니다.
=> [public-header] provider 타입 추가에 따른 프로필 변경

packages/tds-widget/src/chat/chat/chat-room-messages/chat-api-service.ts, packages/tds-widget/src/chat/chat/chat-room-messages/chat-message-context.tsx, packages/tds-widget/src/chat/chat/chat-room-messages/messages.tsx, packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/chat/chat-room-messages/use-unread-messages.ts, packages/tds-widget/src/chat/chat/messages-reducer.ts, packages/tds-widget/src/chat/chat/room-context.tsx, packages/tds-widget/src/chat/types/message.ts, packages/tds-widget/src/chat/types/room.ts, packages/tds-widget/src/chat/types/unread.ts, packages/tds-widget/src/chat/types/user.ts, packages/tds-widget/src/chat/utils/image.ts, packages/tds-widget/src/chat/utils/index.ts, packages/tds-widget/src/chat/utils/user.ts
- id로 사용자를 특정할 수 없도록 하기 위하여 채팅 룸, 메시지의 member 정보에서 id, identifier, code 등을 제거합니다.
- 기존 룸 내부에서 메시지의 sender와 유저(나)를 구분자로 member.id를 사용하던 부분을 `roomMemberId` 필드를 사용합니다.
- nol-chat의 room 조회 reponse가 [변경됨](https://github.com/titicacadev/nol-chat/pull/138#issuecomment-2742979291)에 따라 해당 타입을 마이그레이션 합니다. 
-  생성된 룸: [ChatRoomDetailInterface](https://github.com/titicacadev/triple-frontend/pull/3601/files#diff-e55122b1b80ad8814a2c708c4685afbf13ca82929e67e210563eacd9478485efR111)
- direct/userType/userIdentifier로 진입 시 생성되지 않은 룸: [PreDirectRoomInterface](https://github.com/titicacadev/triple-frontend/pull/3601/files#diff-e55122b1b80ad8814a2c708c4685afbf13ca82929e67e210563eacd9478485efR89)
- invitation으로 진입 시 생성되지 않은 룸: [InvitationRoomInterface](https://github.com/titicacadev/triple-frontend/pull/3601/fi …
=> (Chat) [DMTALK-51] 사용자 식별자 제외 API 응답 마이그레이션

packages/tds-widget/src/chat/chat/chat-room-messages/chat-api-service.ts, packages/tds-widget/src/chat/chat/chat-room-messages/chat-message-context.tsx, packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/chat/messages-reducer.ts
- nol-chat getMessages 응답 인터페이스가 변경되어 migration합니다.
- triple-chat: ChatMessageInterface[]
- nol-chat: { messages: ChatMessageInterface[], hasPrev: boolean }
=> (Chat) nol-chat getMessages 응답값 migration

packages/ab-experiments/src/triple-ab-experiment-context/context.tsx, packages/ab-experiments/src/triple-ab-experiment-context/service.ts, packages/ad-banners/src/api.ts, packages/date-picker/src/service.ts, packages/date-picker/src/use-public-holidays.ts, packages/fetcher/package.json, packages/fetcher/src/factories.ts, packages/fetcher/src/index.ts, packages/fetcher/src/session-refresh.ts, packages/nearby-pois/src/service.ts, packages/poi-detail/src/recommended-articles/api-client.ts, packages/react-contexts/src/images-context/use-fetch-images.tsx, packages/react-contexts/src/scraps-context/api-client.ts, packages/react-contexts/src/scraps-context/scraps-context.tsx, packages/replies/src/hook.tsx, packages/replies/src/list/reply.tsx, packages/replies/src/replies-api-client.ts, packages/review/src/components/shorten-list/services.ts, packages/review/src/data/graphql/client.ts, packages/review/src/services/use-reviews.ts, packages/triple-document/src/elements/tna/index.tsx, packages/triple-header/src/service.ts, packages/ui-flow/src/auth-guard/index.ts, packages/user-verification/src/confirmation-services.ts, pnpm-lock.yaml
클라이언트에서의 세션 갱신을 위한 로직을 구현합니다. 
- `fetcher`의 기본 methods를 사용하고 있던 부분을 `authGuardedFetchers`로 변경하고 해당 메소드의 return 값에 맞게 로직을 수정합니다.
- `NEED_LOGIN` string을 리턴하는 경우를 처리합니다. 
- TF 내부에서 응답을 처리하는 부분은 기존 로직과 변경된 점이 없어야 합니다. 
- ReactQuery를 사용해 API를 fetch하는 `Review` 컴포넌트의 경우 queryFn에 들어가는 로직을 함수로 감싸 session refresh 로직이 실행되도록 했습니다. 
- API 응답에서 status code가 401인 경우 body를 통해 세션 만료인지, 로그인이 필요한 API인지 구분할 수 있도록 변경되었습니다. 이 부분은 해당 PR 리뷰 이후 적용 예정입니다.
=> [react-contexts] 클라이언트 세션 갱신 로직을 추가합니다. 

packages/core-elements/src/elements/accordion/accordion-content.tsx, packages/footer/src/award-footer.tsx, packages/footer/src/button-area/button.tsx, packages/footer/src/button-area/dropdown.tsx, packages/footer/src/button-area/index.tsx, packages/footer/src/company-info.tsx, packages/footer/src/constants.ts, packages/footer/src/default-footer.tsx, packages/footer/src/footer.json, packages/footer/src/footer.stories.tsx, packages/footer/src/type.ts
- 푸터에 패밀리 사이트 드롭다운이 필요해지면서, 푸터의 버튼, 링크, 드롭다운을 triple-web-assets의 footer.json에서 받아올 수 있도록 합니다. ([피그마 링크](https://www.figma.com/design/MyEtr4Y2RUToFU86k3Gu4e/%EC%9B%B9-footer-%EA%B0%9C%EC%84%A0?node-id=702-138&p=f&t=btC21vPpf1dJW8j4-0))
- 드롭다운 기능을 추가합니다.
- 푸터의 정보를 받아오는 동안 스켈레톤을 구현합니다.
=> [footer] 푸터에 버튼, 링크, 드롭다운을 원격으로 설정할 수 있도록 수정합니다.

packages/tds-widget/src/chat/chat/chat-room-messages/chat-api-service.ts, packages/tds-widget/src/chat/chat/chat-room-messages/chat-message-context.tsx, packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/chat/messages-reducer.ts
- getMessages 인터페이스 변경에 대응합니다.
- `hasNext` => `nextToken`
- 현재 backward만 사용하므로 서버로 부터 받은 nextToken을 prevToken으로 변환합니다. 추후 backward=false 사용이 추가된다면, 분기처리가 필요합니다.
=> [DMTALK] get messages 응답 인터페이스 변경 대응

packages/react-contexts/src/middlewares/refresh-session.ts
`/users/session/verify` API의 응답값을 구분하여 세션 갱신 로직을 실행합니다. 
- https://github.com/titicacadev/triple-user/pull/523
- https://github.com/titicacadev/triple-user/pull/555
- `/users/session/verify` 의 응답값이 403인 경우 세션 갱신 로직을 수행하지 않습니다. 
- 모든 응답의 `set-cookie`를 NextResponse에 적용합니다.
=> [react-contexts] session verify API의 403 status 처리를 추가합니다. 

packages/tds-widget/src/chat/preview/elements.tsx, packages/tds-widget/src/chat/preview/preview.tsx, packages/tds-widget/src/chat/preview/utils.ts
Preview 날짜 표기 기본 방식 util을 추가합니다.
시간에 따라 다르게 표기되는 formatRelativeTime 함수를 추가합니다.
- 당일 : 시간
- 7일 이내 : ~일전
- 7일 이후 : 날짜
적용을 원하면 CreatedAt prop으로 설정이 필요합니다.
```tsx
import { formatRelativeTime } from '@titicaca/tds-widget'
...
CreatedAt={({ createdAt }) => (
<ChatRoomCreatedAt
createdAt={createdAt}
convertDateTime={formatRelativeTime}
/>
)}
```
=> [DMTALK] Preview 날짜 표기 방식 util 추가

packages/react-contexts/src/middlewares/refresh-session.ts
당분간 x-soto-session을 유지하기로 했으므로 x-soto-session을 제외하는 로직을 삭제합니다.
미들웨어의 에러 트래킹을 위해 `captureHttpError`를 추가합니다.
=> middleware 내부에서 httpError 로깅 추가 및 x-soto-session 제거 로직 삭제

packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts
- 첫 메시지 전송 시 룸을 생성하고 룸멤버 정보를 받아오는 시간이 소요되어 화면에 내용이 보이지 않는 이슈를 수정하기 위해 첫메시지 전송 시 pending message화 합니다.
- https://github.com/titicacadev/triple-chat-web/pull/479
=> [DMTALK-126] 첫 메시지 전송 시 룸 생성 전 pending message 처리

packages/tds-widget/src/chat/reservation-info/elements.tsx, packages/tds-widget/src/chat/reservation-info/reservation-info.tsx
=> [DMTALK-135] 예약정보 UI 디자인 수정 반영

packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/chat/chat-room-messages/use-scroll.tsx, packages/tds-widget/src/chat/scroll-buttons-area/index.tsx
[DMTALK-133]
사용부(파센, 챗웹)에서 경우에 따라 실행플로우가 달라집니다.
- `my=true`인 경우 -> 상태를 변경시킨 후 effect로 변경하기 때문에 딜레이가 걸림 + dispatch로 상태변경 없음
- `my=false`인 경우 -> dispatch로 상태변경 + 바로 scrollToBottom 호출// 상태변경이 반영이 안된 상태에서 스크롤이 아래로 내려졌던 것일 수 있음
`useChatMessages` 속 다른 `dispatch` 실행 후 실행하는 코드들은 **상태로 저장되거나 딜레이가 있어** 상태 반영 후 실행이 되어 문제가 없었던 것으로 보입니다.
따라서 `onButtonClick`에서도 상태를 변경시켜 스크롤을 변경하는 `triggerScrollToBottom`가 실행되도록 변경합니다.
기존에 `scrollBehavior` 값을 다르게 받고 있었기 때문에 `scrollOptions`를 추가로 받을 수 있도록 수정합니다.
반영 PR
- https://github.com/titicacadev/tna-partners-web/pull/2275
- https://github.com/titicacadev/triple-chat-web/pull/485
https://github.com/user-attachments/assets/27fbe104-1fa6-4454-a701-61e30034b5a1
[DMTALK-133]: https://yanoljagroup.atlassian.net/browse/DMTALK-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5 …
=> [DMTALK-133] 상대방 메시지 실시간 받을 경우 스크롤이 올라가도록 수정

packages/review/src/services/use-reviews.ts
`getReviewsCount` 쿼리의 queryFn에서 return을 하지 않아 data가 undefined가 되는 문제를 해결합니다. 이전에 `content-web`에서 테스트했을 때에는 리뷰 개수를 노출하지 않아 미처 발견하지 못했습니다. 🥲
- queryFn의 반환값을 추가합니다. 
- 불필요하고 잘못된 타입을 제거합니다.
=> [review] queryFn return 추가

packages/fetcher/package.json, packages/fetcher/src/index.ts, packages/fetcher/src/server-fetch.ts, packages/middlewares/package.json, packages/middlewares/src/index.ts, packages/middlewares/src/refresh-session.ts, packages/middlewares/src/refresh-session/index.ts, packages/middlewares/src/refresh-session/next-13.ts, packages/middlewares/src/refresh-session/next-14.ts, packages/middlewares/src/set-web-device-id.ts, packages/middlewares/src/utils/get-domain.ts, pnpm-lock.yaml
next14에 맞게 middleware를 수정하고 서버 컴포넌트에서 사용할 `serverFetcherize` 함수를 추가합니다. 
- next14에서는 미들웨어에서 `response.cookies.set` 함수를 사용할 경우 `set-cookie` 뿐 아니라 response의 cookie에도 적용이 되므로 이를 위해 사용했던 `applySetCookie` 함수를 제거합니다. 
- v13 참고 : https://github.com/titicacadev/triple-frontend/pull/3592 
- v13에서는 기존 코드를 사용하기 위해 `constructMiddlewareNext13`을 분리했습니다. next14 버전 이상으로 모든 레포가 업데이트 되면 없어질 예정이기 때문에 따로 next14 함수와 공통 부분을 분리하지 않고 복사해 코드를 작성했습니다. 
- invalid한 쿠키값을 제외하고 요청을 보낼 수 있도록 `removeInvalidCookies` 함수를 적용합니다.
- `severFetcherize` 함수에서는 기본적으로 적용합니다.
- next14로 업데이트되면서 middleware에서 변경된 쿠키 값을 적용해도 빈값을 넣어주면 `undefined`로 값이 인식되므로 명시적으로 invalid한 값들을 제거하는 과정을 추가합니다. invalid한 쿠키 값은 빈값(null, undefined)이거나 길이가 0인 string입니다.
- next 13
```
// middlware.ts
import { constructMiddlewareNext13 } from …
```
=> [middlware] 세션 갱신 로직을 수정합니다.

packages/tds-widget/src/chat/input-area/nol-input-area-ui/index.tsx, packages/tds-widget/src/chat/scroll-buttons-area/index.tsx
- 인터파크 안드로이드 앱에서 키보드 appear/disappear 에 따른 스크롤 위치 조정 및 scrollToBottom delay가 필요하여 관련 프롭스를 추가합니다.
- 관련 PR https://github.com/titicacadev/triple-chat-web/pull/492
=> [DMTALK-130] 안드로이드 스크롤 오류 관련 프롭스 추가

packages/tds-widget/src/chat/bubble/nol/styles.ts, packages/tds-widget/src/chat/messages/messages.stories.tsx, packages/tds-widget/src/chat/reservation-info/reservation-info.stories.tsx
[TPB-3001]
- 네트워크 없는 경우에도 실패 아이콘이 노출되도록 svg를 가지고 있도록 수정합니다.
- 스토리북에 놀 메시지를 추가합니다.
https://617b7c4431c922004a42c7cc-igrtthjywu.chromatic.com/?path=/story/tds-widget-chat-messages--nol-messages
[TPB-3001]: https://yanoljagroup.atlassian.net/browse/TPB-3001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DMTALK] 네트워크 없을 경우 실패 아이콘 미노출되는 이슈 수정

packages/tds-widget/src/chat/reservation-info/elements.tsx, packages/tds-widget/src/chat/reservation-info/reservation-info.tsx
[TPB-3003]
- 채팅창 상세에서 상품/예약정보 접기펼치기 영역을 타이틀 영역까지 확대합니다.
[TPB-3003]: https://yanoljagroup.atlassian.net/browse/TPB-3003?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DMTALK] 채팅창 상세에서 상품/예약정보 접기펼치기 영역 확대

packages/react-contexts/package.json, packages/react-contexts/src/middlewares/refresh-session.ts, packages/react-contexts/src/middlewares/set-web-device-id.ts, packages/react-contexts/src/middlewares/utils/get-domain.ts, pnpm-lock.yaml
로컬호스트에서 갱신된 세션을 사용할 수 있도록 합니다. 
next13에서는 `getSetCookie()` 메소드 사용 시 전체 `set-cookie`가 하나의 스트링으로 인식되어 배열에 요소가 하나만 생기는 이슈가 있어 `get('set-cookie')`로 전체 set-cookie를 스트링으로 받아오는 것을 보장해 이를 파싱하는 방법을 사용했습니다.
=> 로컬호스트에서의 세션 관련 로직을 처리합니다. 

packages/triple-web-nextjs-pages/src/initializers/session.ts
웹뷰/웹에 관계없이 TP_TK, TP_SE를 사용하는 인증 로직을 사용하는 것으로 변경되어 웹뷰/웹 구분 없이 로직을 통일합니다.
=> [triple-web-nextjs-pages] 앱/웹 구분 없이 authFetcherize를 추가합니다. 

packages/tds-widget/src/chat/types/room.ts
취소 후 만료 정책이 추가됨에 따라 이를 ExpirePolicy에 반영합니다.
만료 정책의 응답 값 수정을 반영합니다.
https://nol-chat-api.proxy.dev.triple.zone/docs/swagger-ui/index.html#/room-external-controller/getRoom
- ExpirePolicyBase 필드 추가
- AfterDateOfUsePolicy 삭제된 필드 반영
- type AFTER_CANCEL, AfterCancelPolicy 추가
=> [DMTALK] 취소 후 만료정책 추가

packages/tds-widget/src/review/components/review-element/index.tsx, packages/tds-widget/src/review/components/review-element/pinned-message.tsx, packages/tds-widget/src/review/mocks/review-element.duo-images.json, packages/triple-document/package.json, packages/triple-document/src/elements/coupon/coupon-download-buttons.tsx, packages/view-utilities/package.json, packages/view-utilities/src/timestamp.ts, pnpm-lock.yaml
moment 라이브러리를 사용하고 있던 코드를 date-fns를 사용하도록 수정합니다. `date-picker`의 경우 `date-picker` 패키지의 업데이트가 필요하여 @dongoc 이 따로 작업 중이십니다.
`formatTimestamp` 함수를 사용할 경우 기존에 `한 시간 전` 이라고 표기되던 것이 `1시간 전`으로 표기됩니다.
=> moment 라이브러리를 date-fns로 변경합니다. 

packages/tds-widget/src/chat/icons/ExclamationMarkIcon.tsx
- 아이콘 fill 오류를 수정합니다.
- stroke, fill 분리
=> [DMTALK-184] 아이콘 오류 수정

packages/router/src/links/use-open-native-link.ts, packages/tds-widget/src/review/components/review-placeholder-with-rating.tsx
- `navigate`로 인앱 페이지 이동 시 iOS에서 두번 이동되는 오류를 수정합니다.
- `window.location.href`, `window.open`이 중복 실행됨
- 리뷰 리스트 > '전체 리뷰 보기' 버튼 클릭 시 이벤트 버블링으로 인해 페이지 이동이 중복해서 발생하는 오류를 수정합니다.
- as-is
|전체보기 페이지|유저 프로필|
|--|--|
|iOS: 3번 이동, Android: 2번 이동|iOS: 2번 이동, Android: 정상|
|https://github.com/user-attachments/assets/2e03e02d-ef62-4d93-a645-578c1df4adf0|https://github.com/user-attachments/assets/55b1dd00-bd4b-45ed-ab5e-b6647c00efa0|
- to-be
https://github.com/user-attachments/assets/2a668dc5-dcd2-425a-87fa-81f88d7f2709
=> [DMTALK-183] 링크 두번 열리는 오류 수정

packages/tds-ui/src/components/drawer-button/drawer-button.tsx, packages/tds-ui/src/components/drawer/drawer.tsx, packages/tds-widget/src/date-picker/day-picker.tsx, packages/tds-widget/src/date-picker/range-picker-v2/range-picker.tsx, packages/tds-widget/src/date-picker/range-picker.tsx, packages/tds-widget/src/date-picker/use-disabled-days.ts
[tds-widget] react-day-picker의 props를 받을 수 있도록 추가 
- range picker에서 받을 수 있는 props를 추가하여 상위에서 커스텀할 수 있도록 수정합니다.
- drawer-button의 경우 drawer button이 아닌 drawer container에 rest props를 연결하여 상위에서 전체 css를 조정할 수 있도록 수정합니다.
=> [tds-widget] react-day-picker의 props를 받을 수 있도록 추가

packages/tds-ui/src/components/checkbox/checkbox-base.tsx, packages/tds-ui/src/components/checkbox/checkbox.tsx
체크박스의 체크 위치를 조절합니다. px 단위로 설정해두어 오른쪽으로 약간 치우지는 현상을 발견해 가운데로 위치할 수 있도록 % 및 transform을 사용하도록 수정했습니다. 
|AS-IS|TO-DO|
|-----|------|
|<img width="92" alt="스크린샷 2025-05-09 오후 3 48 29" src="https://github.com/user-attachments/assets/d4071814-aafb-4e6b-8a5a-fa3c8be77973" />|<img width="99" alt="스크린샷 2025-05-09 오후 3 49 48" src="https://github.com/user-attachments/assets/2bc4e24d-f217-410c-afba-252296007db2" />|
=> [tds-ui] 체크박스 체크 위치 수정

packages/tds-widget/src/chat/chat/chat-room-messages/messages.tsx, packages/tds-widget/src/chat/index.ts, packages/tds-widget/src/chat/messages/index.tsx, packages/tds-widget/src/chat/messages/type.ts, packages/tds-widget/src/chat/types/message.ts
- message payload 내 extra 노출합니다.
- https://github.com/titicacadev/nol-chat-center/pull/63
- message payload 내 extra 노출할 수 있도록 ExtraBubble props를 추가합니다.
- message.payload 내 extra 필드를 활용하여 버블에 커스텀 UI를 추가합니다.
- BubbleContainer export 오류를 수정합니다.
=> [DMTALK-316] message payload 내 extra 노출

packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/messages/index.tsx
- pendingMessages와 failedMessages 사이에 상태를 보여주는 영역이 필요하여 `interactionStatusSlot`을 추가합니다. 
https://github.com/titicacadev/triple-chat-web/pull/519
=> [DMTALK-317] interactionStatusSlot 추가

packages/triple-web/README.md, packages/triple-web/src/hash-router/context.tsx
Multiple hash를 지원합니다. 같은 값의 hash가 두 번 이상 추가될 경우 로컬 환경에서 워닝을 띄웁니다. 
- `addUriHash`가 여러 hash 값을 지원하도록 수정
- 현재 hash 뒤에 새로운 hash 값을 `&`로 연결해 덧붙입니다. 
- `removeUriHash`가 여러 hash 값을 지원하도록 수정
- 일단 hash를 뒤에서부터 제거하는 방식을 선택했습니다.
- `hasUriHash` 메소드 추가
- Readme.md 수정 및 추가
기존 프로젝트에서 `hasUriHash`를 사용하는 방식을 적용하지 않으면 정상적으로 동작하지 않기 때문에 minor version update로 마일스톤을 할당했습니다. HashRouter의 동작과 관련해 `uriHash`는 value에서 제외하는 것이 좋을까요? 제거하면 기존 프로젝트에서 오류가 발생할 것이라 빠짐없이 수정이 가능할 것이라.. 🤔
URL : ~~~~#open.memo-modal&action-sheet.memo-more-actions 이면
=> [triple-web] multiple hash 지원

packages/tds-widget/src/chat/input-area/nol-input-area-ui/use-input-resize-observer.ts
- input resize observer 옵션을 border-box로 변경합니다.
=> [DMTALK-425] input resize observer 옵션 변경

packages/middlewares/src/refresh-session/next-14.ts
next v14용 미들웨어에도 `applySetCookie`를 적용해 페이지 request에 갱신된 세션이 적용될 수 있도록 합니다.
=> [middleware] next14용 미들웨어에 applySetCookie 적용

packages/tds-widget/src/chat/chat/chat-room-messages/chat-message-context.tsx, packages/tds-widget/src/chat/chat/chat-room-messages/use-chat-room-messages.ts, packages/tds-widget/src/chat/chat/messages-reducer.ts
- welcomeMessage 전송 시 UI 오류를 수정합니다.
- `triple-chat`에서는 message의 id가 string로 사용되고, `nol-chat`에서는 number로 사용되고 있으며, pusher의 `onSendMessageEvent`를 통해 전달되는 message의 id는 string 형이라, `nol-chat`에서는 message-context에서 가지고 있는 message id 형이 달라, 메시지 중복이 발생하고 있어 같은 타입으로 변환하는 로직을 추가합니다. 
- 웰컴 메시지의 경우 `onSendMessageEvent` 이벤트로 부터 `message`에 추가되는 타이밍에 `pendingMessage`에서 제거되지 않아 중복 노출되는 케이스가 있어 filtering 로직을 추가합니다.
- as-is
https://github.com/user-attachments/assets/b4546244-fee4-4fcc-a605-1332e85bf70b
- to-be
https://github.com/user-attachments/assets/b79669ac-0a1b-4025-a687-444b5bb54b6b
=> [DMTALK-217] welcomeMessage 전송시 UI 오류 수정
